# Major acts and regulations

## Acts and laws of Nepal

\begin{solution}
\begin{enumerate}
\item Nepali Language Publication Corporation Act, 2021 (1964)
\item Nepal Ship (Registration and Logbook) Act, 2027 (1971)
\item Nepal Special Service Act, 2042 (1985)
\item Non-resident Nepali Act, 2064
\item Passports Act, 2024 (1967)
\item The Consumer Protection Act, 2075 (2018)
\item Work Operation Fund Act, 2043 (1986)
\item Water Tax Act, 2023 (1966)
\item Nepal Treaty Act, 2047 (1990)
\item Supreme Court Act, 2048 (1991)
\item Regional Development Plans (Implementation) Act,2013 (1956)
\item Rajya Rajauta (Petty States and Rulers) Act, 2017 (1961)
\item Periodic Tax Recovery Act, 2012 (1955)
\item The University Grants Commission Act, 2050 (1993 A.D.)
\item The Stamp Duty Act, 2019 (1963)
\item The Pesticides Act, 2048 (1991)
\item Radio Act, 2014 (1957)
\item Act Restricting Investment Abroad, 2021(1964)
\item Act to Provide for Enhancement of the Circulation of Nepalese Currency, 2014(1957)
\item The Administrative Procedures (Regulation) Act, 2013 (1956)
\item Animal Health and Livestock Services Act, 2055 (1999)
\item Animal Slaughterhouse and Meat Inspection Act, 2055(1999)
\item Anti Defection Act, 2054 (1997)
\item Contingency Fund Act, 2016 (1959)
\item Drugs Act, 2035, (1978)
\item Nepal Tourism Board Act, 2053
\item Public Security Act, 2046 (1989)
\item Associations Registration Act, 2034 (1977)
\item AUDIT ACT, 2048 (1991)
\item banking-offence-and-punishment-act-2064-2008
\item Child Labor (Prohibition and Regulation) Act, 2056 (2000)
\item Commissions of Inquiry Act, 2026 (1969)
\item Infectious Disease Act, 2020(1964)
\item Immovable Property Requisition Act, 2013 (1956)
\item Human Trafficking and Transportation (Control) Act, 2064
\item The Copyright Act, 2059 (2002)
\item Development Board Act, 2013 (1956)
\item Domestic Postal Goods (Insurance) Act, 2019 (1962)
\item Foreign Investment Tax Act, 2019 (1963)
\item Judicial Fund Act, 2043 (1986)
\item Nepal Citizenship Act, 2063 (2006)
\item Essential Services Operation Act, 2014 (1957)
\item Export and Import (Control) Act, 2013 (1957)
\item Essential Goods Protection Act, 2012 (1955)
\item Extradition Act, 2045 (1988)
\item Legal Aid Act, 2054 (1997)
\item Nepal Agency Act 2014
\item International Financial Transactions Act, 2054 (1998)
\item National Judicial Academy Act, 2063 (2006)
\item Mother's Milk Substitutes (Control of Sale and Distribution) Act, 2049 (1992)
\item Compensation Relating to Torture Act, 2053 (1996)
\item Multimodal Transportation of Goods Act, 2063(2006).
\item National Trust for Nature Conservation Act, 2039 (1982)
\item Electricity Act, 2049 (1992)
\item Interpretation of Laws Act, 2010(1954)
\item Lottery Act, 2025 (1968)
\item Nepal Electricity Authority Act, 2041 (1984)
\item Constitutional Council (Functions, Duties, Powers and Procedures) Act, 2066 (2010)
\item Feed Act, 2033 (1976)
\item Jhora Area Land Act, 2028 (1971)
\item National Parks and Wildlife Conservation Act, 2029 (1973)
\item National Guidance Act, 2018 (1961)
\item Loan and Guarantee Act, 2025(1968)
\item Narcotic Drugs (Control) Act, 2033 (1976)
\item Motor Vehicle Tax Act, 2031 (1974)
\item Nepal Health Research Council Act, 2047 (1991)
\item Competition Promotion and Market Protection Act, 2063 (2007)
\item Evidence Act, 2031
\item Money Laundering Prevention Act, 2063 (2008)
\item Motion Picture (Production, Exhibition and Distribution) Act, 2026 (1969)
\item Arbitration Act, 2055 (1999)
\item Domestic Violence (Offence and Punishment) Act, 2066 (2009)
\item Donations Act, 2030 (1973)
\item National Cooperatives Development Board Act, 2049 (1992)
\item Insurance Act, 2049 (1992)
\item Aquatic Animal Protection Act, 2017(1960)
\item National Dairy Development Board Act, 2048(1992)
\item Explosives Act, 2018 (1961)
\item Essential Commodities Control (Authorization) Act, 2017 (1961)
\item Impeachment (Regulation of Procedure) Act, 2059 (2002)
\item Birth, Death and Other Personal Events (Registration) Act, 2033 (1976)
\item The Foreign Investment and Technology Transfer Act, 2019 (2075)
\item House and Land Tax Act, 2019 (1962)
\item The Industrial Enterprises Act, 2049 (1992)
\item Nepal Standards (Certification Mark) Act, 2037 (1980)
\item National Tea and Coffee Development Board Act, 2049 (1993)
\item Bonded Labour ( Prohibition )Act, 2058 (2002)
\item Diplomatic Privilege and Immunities of the Foreign States and Representatives Act, 2027 (1970)
\item The National Broadcasting Act, 1993
\item Industrial Enterprises Development Institute Act, 2053 (1996)
\item Lumbini Development Trust Act, 2042 (1985)
\item Act Prohibiting the Charging and Taking of Amount (Bhatti Charsa etc.) by Birta-holder on Birta, 2015 (1958)
\item Act Relating to Institutions Acting as Financial Intermediary, 2055 (1999)
\item Act Relating to Land of Jhora Area, 2028 (1971)
\item Nepal Agricultural Research Council Act, 2048(1992)
\item Agriculture and Forestry University Act, 2067 (2010)
\item Nepal Water Supply Corporation Act, 2046 (1989)
\item Nepal Trust Act, 2064 (2008)
\item Nepal Pharmacy Council Act, 2057 (2000)
\item Nepal Nursing Council Act, 2052 (1996)
\item Nepal Rastra Bank Act, 2058 (2002)
\item Nepal Medical Council Act, 2020 (1964)
\item Nepal Health Professional Council Act, 2053
\item Nepal Bar Council Act, 2050 (1993)
\item Nepal Law Commission Act, 2063 (2007 )
\item Nepal Airlines Corporation Act, 2019 (1963)
\item National Human Rights Commission Act, 2068 (2012)
\item National Insurance Corporation Act, 2025 (1968)
\item Nepal Administrative Staff College Act, 2020 (1982)
\item National News Agency Act, 2019 (1962)
\item National Foundation for Upliftment of Aadibasi/Janjati Act, 2058 (2002)
\item Nepal Music and Dance Academy Act, 2064 (2007)
\item Mines and Minerals Act, 2042 (1985)
\item Mediation Act, 2068 (2011)
\item Archives Preservation Act, 2046 (1989)
\item International Finance Corporations Membership Acquisition Act, 2022 (1965)
\item Corporations Act, 2021 (1964)
\item Black Marketing and Some Other Social Offenses and Punishment Act, 2032 (1975)
\item Caste Based Discrimination and Untouchability Offence and Punishment Act, 2068 (2011)
\item Forest Act, 2049 (1993)
\item Construction Business Act, 2055 (1999)
\item Bretton Woods Agreement Act, 2018 (1961)
\item Far-western University Act, 2067 (2010)
\item Negotiable Instruments Act, 2034 (1977)
\item Mid-western University Act, 2067 (2010)
\item Gorkhapatra Corporation Act, 2019 (1963)
\item Hotel Management and Sale and Distribution of Liquors (Control) Act, 2023 (1966)
\item The B. P. Koirala Institute of Health Sciences Act, 2049 (1993)
\item The Greater Janakpur Area Development Council Act, 2055 (1998)
\item Iodized Salt (Production, Sale and Distribution) Act, 2055(1998)
\item Amount and Governmental Contract Arrangement Act, 2020(1963)
\item Insolvency Act, 2063 (2006)
\item Land Acquisition Act, 2034 (1977)
\item Kathmandu University Act, 2048 (1991)
\item International Development Association's Membership Acquisition Act, 2019 (1962)
\item Land Revenue Act, 2034 (1978)
\item Martyr Gangalal National Heart Disease Centre Act, 2057 (2000)
\item Lumbini Bouddha University Act, 2067 (2006)
\item Land (Survey and Measurement) Act, 2019 (1963)
\item Local Administration Act, 2028 (1971)
\item Local Development Training Academy Act, 2049 (1993)
\item International Centre for Integrated Mountain Development Act, 2040 (1983)
\item The Human Body Organ Transplantation (Regulation and Prohibition) Act, 2055 (1998)
\item The Guthi Corporation Act, 2033 (1976)
\item Ancient Monument Preservation Act, 2013 (1956)
\item The Electronic Transactions Act, 2063 (2008)
\item Armed Police Force Act, 2058 (2001)
\item Arms and Ammunition Act, 2019 (1962)
\item Ayurveda Medical Council Act, 2045 (1988)
\item The B.P. Koirala Memorial Cancer Hospital Act, 2053(1997)
\item Birta Abolition Act, 2016 (1959)
\item The Building Act, 2055
\item Nepal Chartered Accountants Act, 2053 (1997)
\item Citizen Investment Trust Act, 2047 (1991)
\item Commission for the Investigation of Abuse of Authority Act, 2048 (1991)
\item Communication Corporation Act, 2028 (1972)
\item Compensation Act, 2019 (1963)
\item The Lands Act, 2021(1964)
\item Construction Business Act, 2055 (1999)
\item Corporations Act, 2021 (1964)
\item Customs Act, 2064 (2007)
\item Decorations Act, 2064 (2007)
\item Education Act, 2028 (1971)
\item Electricity Theft Control Act, 2058 (2002)
\item Excise Duty Act, 2058 (2002)
\item Nepal Fine Arts Academy Act, 2064 (2007)
\item Privatization Act, 2050 (1994)
\item Water Resources Act, 2049 (1992)
\item Private Forests Nationalization Act, 2013 (1957)
\item The Social Welfare Act, 2049 (1992)
\item Notary Public Act, 2063
\item Right to Information Act, 2064 (2007 )
\item Trade Union Act, 2049 (1992)
\item Tax Settlement Commission Act, 2033 (1976)
\item Telecommunications Act, 2053 (1997)
\item Statistics Act, 2015 (1958)
\item Working Journalists Act, 2051(1993)
\item Wealth Tax Act, 2047 (1990)
\item Water Tariff Fixation Commission Act, 2063 (2006)
\item Water Supply Management Board Act, 2063 (2006)
\item Nepal Veterinary Council Act, 2055 (1999)
\item Ukhada Act, 2021 (1964)
\item Tribhuvan University Act, 2049(1992)
\item Town Development Fund Act, 2053 (1997)
\item Town Development Act, 2045 (1998)
\item Road Board Act, 2058 (2002)
\item Postal Act, 2019 (1963)
\item Partnership Act, 2020 (1964
\item Police Act, 2012 (1955)
\item The Patent, Design and Trade Mark Act, 2022 (1965)
\item Special Court Act, 2059 (2002)
\item [The] Kathmandu Valley Development Authority Act, 2045 B.S. (1988)
\item Technical Education and Vocational Training Council Act, 2045 (1988)
\item Summary Procedures Act, 2028 (1972)
\item Standard Measurement and Weight Act, 2025 (1968)
\item Sports Development Act, 2048 (1992)
\item Some Public Documents Authentication (Procedures) Act, 2063 (2006)
\item Solid Waste Management Act, 2068 (2011)
\item Soil and Watershed Conservation Act, 2039(1982)
\item Social Practices (Reform) Act, 2033 (1976)
\item Ship Registration Act, 2027 (1971)
\item Senior Citizens Act, 2063 (2006)
\item Seeds Act, 2045 (1988)
\item Tourism Act, 2035 (1978)
\item Tobacco Products (Control and Regulatory) Act, 2068 (2011)
\item [The] Ownership of Joint Housing Act, 2054 B.S. (1997)
\item Security of the Health Workers and Health Organizations Act, 2066 (2010)
\item Secured Transaction Act, 2063 (2006)
\item Scholarships Act, 2021 (1964)
\item Revenue Tribunal Act, 2031 (1974)
\item Securities Act, 2063 (2007)
\item Press Council Act 2048 (1992) 
\item Patan Academy of Health Sciences Act, 2064 (2008)
\item The Prevention of Corruption Act, 2059 (2002 A.D)
\item Purwanchal University Act, 2050 (1994)
\item Public Service Commission Act, 2066 (2010)
\item Public Roads Act, 2031 (1974)
\item The Public Procurement Act, 2063 (2007)
\item Public Debt Act, 2059 (2002)
\item Prisons Act, 2019 (1963)
\item Remuneration, Conditions of Service and Facilities of the Authorities of the Constitutional Bodies Act, 2053 (1997)
\item Press and Publication Act, 2048 (1991)
\item Poverty Alleviation Fund Act, 2063 (2006)
\item Pokhara University Act, 2053 (1996)
\item Plant Protection Act, 2064 (2007)
\item Nepal Petroleum Act, 2040 (1983)
\item Pasture Land Nationalization Act, 2031 (1974)
\item Mutual Legal Assistance Act, 2070 (2014)
\item Judicial Council Act, 2073 (2016)
\item Employee Provident Fund Act, 2019 (1962)
\item An Act to Regulate and Control International Trade in Endangered Wild Fauna and Flora
\item Administration of Justice Act, 2073 (2016)
\item Pashupati Area Development Trust Act, 2044 (1987)
\item Karnali Academy of Health Sciences Act, 2068 (2011)
\item Nepal Health Service Act, 2053 (1997)
\item Army Act, 2063 (2006 )
\item Civil Service Act, 2049 (1993)
\item Motor Vehicles and Transport Management Act, 2049 (1993)
\item Passports Act, 2024 (1967)
\item The Crime Victim Protection Act, 2075 (2018)
\item The Privacy Act, 2075 (2018)
\item The Public Health Service Act, 2075 (2018)
\item The Right to Employment Act, 2075 (2018)
\item The Act Relating to Rights of Persons with Disabilities, 2074 (2017)
\item The Right to Food and Food Sovereignty Act, 2075 (2018)
\item The Right to Housing Act, 2075 (2018)
\item The Right to Safe Motherhood and Reproductive Health Act, 2075 (2018)
\item The Social Security Act, 2075 (2018)
\item The Act Relating to Children, 2075 (2018)
\item The Act Relating to Compulsory and Free Education, 2075 (2018)
\item Bank and Financial Institution Act, 2073 (2017)
\end{enumerate}
\end{solution}

## Right to information

\begin{questions}

\question What are the provisions in Nepal relating on the "Right to Information" ? Discuss in detail.

\begin{solution}
Government of Nepal enacted the Right to Information Act, 2064 (2007)

\textbf{Preamble}

1. To make the functions of the state open and transparent in accordance with the democratic system and to make responsible and accountable to the citizen
2. To make the access of citizens simple and easy to the information of public importance held in public bodies
3. To protect sensitive information that could make adverse impact on the interest of the nation and citizen, and for the necessity to have legal provisions to protect the right of the citizen to be well-informed and to bring it into practice.

\textbf{Right to information}

1. Every citizen shall have the right to information subject to RTI act.
2. Every citizen shall have access to the information held in the public bodies.

\textbf{Provision regarding commission}

1. An independent national information commission will be established for the protection, promotion and practice of right to information.
2. A Chief Information Commissioner and two other information commissioners will be in the commission.
3. In order to appoint Chief Information Commissioner and Information Commissioners, there will be a committee comprised as follows:
  a. The speaker -- Chairman
  b. Minister of state minister for information and commission -- Member
  c. President, federation of Nepalese journalists -- Member
4. The Government of Nepal on the recommendation of the Committee under Sub-Section (3), will appoint a Chief Information Commissioner and Information Commissioners; while appointing in this way, at least one female will have to be included.
5. The Committee in accordance with Sub-Section (3) will follow inclusive principles as much as possible with recommending for appointment of Chief Information Commissioner and Information Commissioners.
6. The procedures of recommendation in accordance with Sub-Section (3) will be as determined by the Recommendation Committee itself.

Why RTI

RTI Act 2007 gives you the right to ask for and receive information about any activity from a public body. Public bodies include the following entities:

1. Bodies formed under the constitution
2. Bodies established by the Act
3. Bodies constituted by the government of Nepal
4. Public service provider organizations or foundations established as per the law
5. Political party and organization registered under prevalent laws
6. Organized institutions under the full or partial ownership or under control of the GoN, or organized bodies receiving grants from the GoN
7. Organized institutions formed by the Bodies established by the GoN or any other agencies lawfully formed through an agreement
8. NGOs/Institutions directly or indirectly funded by the GoN or foreign government or international organizations/institutions
9. Other bodies or institutions defined as public bodies by the GoN through a notice published in Nepal gazette.

The seeker of information has to submit a written application to the concerned information officer. It is important for the applicant to clearly specify the information sought. Unclear requests make things difficult to provide correct information. Hence, requests for information should be as clear and specific as possible.

No fees will be charged for the first half hour of monitoring in public bodies or getting information from work place, getting records, or undertaking records inspection and observation. After that the charge in Rs 50 per person, per hour. Likewise, there are no fees for inspection in public libraries and public places where information is made available.

Public bodies will nominate a staff as an information officer for the public's ease of access to information. The head of the office should provide information to the PIO to disseminate it in accordance to sub-section (I) of RTI act. An information section will be set up in all public bodies to disseminate information. The PIOs regularly update their information and keeps records regarding their work plans, expenditure, financial transactions, rules, regulations, laws, and directives. The RTI act anticipates that public bodies store (archive) their information going as far back as 20 years from the commencement of the RTI act. Unless there are resonable and sufficient grounds to validate those exceptions, public bodies cannot evade the responsibility to disclose information. Following information, however, shall not be obliged to be made available:

1. Information harmful to soverignty, integrity, national security public security, law and order of the country; and information that can jeopardize international relations;

2. Information that could have direct bearing on research, investigation and prosecution of a criminal case

3. Information harmful to economic, financial, monetary wellbeing or posing threat to someone's intellectual property rights, as also to banking and financial secrecy.

4. Information that could jeopardize the harmonious realations subsisting between various castes and communities.

5. Information posing threat to a person's right to privacy, personal security, health and property.


In case decision rendered by the Chief of Public body is not satisfactory, one can file the appeal (within 35 days of decision received) to the commission either by directly approaching the commission office or getting it registered in the concerned office or through the concerned District Administration Office. Alternatively, one can also mail the appeal directly to NIC, via any postal services.

Centre for Law and Democracy, Canada has published a comparative study report on existing RTI laws of 111 countries in the world, in which Nepal has been ranked 27th in the world with the score of 104 out of 150. The worldwide experience shows that RTI supports good governance and helps to reduce corruption. The National Information Commission had completed its first RTI Audit in 2016 through ex-secretaries of the government. The second RTI Audit was completed in 2017 through senior journalists.

After analysing all aspects, it was found that 11 ministries (35\%) were found working as per law. Similarly, 20 ministries (65\%) were partially satisfactory. The commission has made 10 suggestions, including adding "imparting information" in Article 27 of the constitution, taking out of the word "secret" from the employees' oath, amongst other, to the government on the basis of the results of this RTI audit.

\end{solution}

\end{questions}

## Army Act, 2063

\begin{questions}

\question According to Army Act, 2063 what are the punishment provisioned through Court Marshall ?

\begin{solution}
According to the Army Act, 2063 (Chapter-11; Section (dafa) 101), 

1. Following penalties may be imposed by court marshall:

\begin{itemize}
\item Life imprisonment along with confiscation of entire property,
\item Confiscation of his or her entire share of ancestral property,
\item Imprisonment of upto Fourteen years,
\item Removing from service without prejudicing eligibility for any governmental service in the future, or dismissing with ineligibility for any governmental service in the future,
\item Demotion to a lower rank,
\item Freezing of promotion for Five years,
\item Deduction of salary and allowances for Three months in case the offence has been committed in the course of military action,
\item Freezing of salary and allowances until the recovery of compensation,
\item Freezing of salary increments for a period not exceeding Two years,
\item Warning (Nasihat).
\end{itemize}

2. The following penalties shall be imposed for the following offences:

\begin{enumerate}
  \item Life imprisonment along with confiscation of entire property for the commission of offences as referred to in Section 38, 39 or Clause (a) of Sub-section (1) of Section 42.
  \item A maximum Fourteen years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Section 40,
    \item Offences provided in Section 41 and Clause (a) of Section 45 during a military operations,
    \item Offences provided in Section 43 or 46 if committed intentionally,
    \item Offences provided in Clause (a) or (b) of Section 44 committed against a person while discharging his/her duties during a military operation,
    \item Offences provided in Section 47.
  \end{enumerate}
  \item A maximum Ten years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Clauses (a) or (b) of Section 44 committed against a person not during the military operation,
    \item Offences provided in Section 48, 49 or 50, (3) Offences provided in Clause (a) of Section 51 or Clause (a) of Section 52.
  \end{enumerate}
  \item The penalty of confiscation of entire property or maximum of Seven years of imprisonment shall be imposed for the commission of offences provided in Clause (b) of Sub-section (1) of Section 42.
  \item A maximum of Seven years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Section 41 committed not during military operation,
    \item Offences provided in Section 46 that are committed unintentionally,
    \item Offences provided in Clauses (b), (c), (d), (e), (f) or (g) of Section 52,
    \item Offences provided in Section 43, 54 or 63.
  \end{enumerate}
  \item A maximum of Five years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Clause (c) of Section 44, (2) Offences provided in Clause (a) of Section 45 committed not during the period of a military operation,
    \item Offences provided in Clauses (b) or (c) of Section 51 or Sections 45, 56 or 57.
  \end{enumerate}
  \item A maximum Three years of imprisonment shall be imposed for the commission of offences provided in Clauses (c) or (d) of Sub-section (1) of Section 42 or Sections 58, 59 or 60.
  \item A maximum of Two years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Clauses (e), (f), (g) or (h) of Sub-section (1) of Section 42,
    \item Offences provided in Clause (b) of Section 45,
    \item Offences provided in Clause (h) of Section 52 committed by personnel below the rank of officer while discharging duties during a military operation,
    \item Offences provided in Section 43 that are committed unintentionally,
    \item Offences provided in Section 61.
  \end{enumerate}
  \item A maximum of Six months imprisonment shall be imposed if a personnel below the rank of officer commits offences provided in Clause (h) of Section 52 except in the period of military operation or while on duty.
  \item A person who commits offences provided in Clauses (i) and (j) of Section 52 shall be removed from the service.
  \item A person who commits offences provided in Clause (k) of Section 62 shall be barred from Two salary increments or promotion for Two years.
  \item A person who attempts to commit such offences as referred to in Chapter-7 or induces another person to commit such offences shall, unless there is specific provision in this Act, be imposed the following penalties:
  \begin{enumerate}
    \item A maximum of Fourteen years of imprisonment for attempting to commit an offence for which a penalty of life imprisonment along with confiscation of entire property may be imposed, and half of the maximum (range) imprisonment for other offences which have been attempted,
    \item Equal penalty for inducement (incitement) to commit an offence as imposed for committing an offence,
    \item A maximum of Fourteen years of imprisonment for inducement to commit an offence which has not been committed (completed), and half of the maximum (range) punishment for inducement to commit any other offence which had not actually been committed (completed).
    \item If a person who committed an offence provided in Clause (b) of Sub-section (1) of Section 42 has absconded and is not found (traced) does not produce him/herself within Thirty Five days, his/her partition share to ancestral property shall be frozen from being transacted. If such person does not appear him/herself or could be found through making a search within Three years, his/her partition share to ancestral property shall be confiscated and auctioned, and the money therefrom shall be deposited to the Government Treasury.
    \item After confiscation of partition share to ancestral property, if the  offender is found, he/she may be imposed life imprisonment along with confiscation of the entire property.
    \item A person who is dismissed from service and disqualified for any governmental job in future pursuant to Clause (j) of Sub-section (2), shall not be paid his/her remaining salary or allowances and pension which he/she is entitled and other facilities except the money accumulated in his/her provident fund.
  \end{enumerate}
\end{enumerate}

Besides these there is Battlefield penalty (Section 104) and Departmental action (Section 105) and Collective fine (Section 107).

\end{solution}

\end{questions}

## Forest Act, 2049

\begin{questions}

\question What provisions and guidelines have Forest act, 2049 set for utilization and management of forest in Nepal? Mention.

\begin{solution}

The Forest Act, 1992, defines national forest, state-managed forest, protected forest, community forest, leasehold forest, religious forest and private forest as well as ownership of different types of forest, and their management. The Act encourages people to own and to use forest, rather than depend on national or state-owned forest. The Forest Regulation, 1994, fixes users' price rates for timber, fuel-wood, medicinal plants and herbs, flowers and furs, fruits and seeds, bark, logs, and allied forest products. Likewise, charges for animal and cattle grazingare also fixed by the regulation.

Similarly, separate regulations for national parks such as the Royal Chitwan National Park and Royal Bardia National Park make it possible to charge different fees for entrance and recreational activities such as safari, hunting game species and fishing. Another milestone in the forestry sector is the Buffer Zone Management Regulation, 1995, which aims to harmonize relation between national parks and the people around those parks. This regulation also encourages the communities around parks to form users' groups so that they can mange and use the buffer zone resources.

\end{solution}

\end{questions}

## The National Civil (Code) Act, 2017 (2074)

Whereas, it is expedient to make timely the civil provisions contained in the country code and other laws, by also amending and consolidating such provisions, in order to maintain morality, decency, etiquette and convenience as well as economic interest of the public by maintaining law and order in the country and maintain harmonious relationship between various castes, races and communities, by making just provisions in the economic, social and cultural field;

Now, therefore, the Legislature-Parliament under clause (1) of Article 296 of the consitution of Nepal has enacted this act. 

- There are a total of 721 sections.

Part-1 Preliminary

Chapter-1 Preliminary statements

Chapter-2 General principles of civil law

- Principles and provisions applicable generally
- Ignorance of law not to be excused
- Act against public interest not to be carried out
- Act contrary to law to be invalid
- A wrongdoer to bear liability for loss or damage
- Act causing nuisance to other not to be done
- Not to enjoy benefit of wrong
- Act against interest to be invalid
- Personality to be recognized
- Good neighborhood to be maintained
- Not to be relieved from civil liability
- Custom or tradition contrary to law not to be recognized
- Applicable to foreigners as well

Chapter-3 Provisions relating to civil rights

- To be equal before law
- Discrimination not to be made
- Discrimination not to be deemed where special provision is made
- Guarantee of freedoms and rights
- Right to privacy deemed to be violated
- Right to make contract
- No taxation except in accordance with law
- No to employ in work against will
- Property not to be acquired, requisitioned, auctioned or forfeited
- Complaint may be filed
- Compensation to be awarded
- Compensation for filing false complaint
- Statute of limitation

Part-2 Law relating to persons

Chapter-1 Provisions relating to natural persons

Chapter-2 Provisions relating to legal persons

Chapter-3 Provisions relating to bankruptcy of natural persons

Part-3 Family law

Chapter-1 Provisions relating to marriage

Chapter-2 Provisions relating to consequence of marriage

Chapter-3 Provisions relating to divorce

Chapter-4 Provisions relating to relationship of parents and children

Chapter-5 Provisions relating to maternal and paternal authority

Chapter-6 Provisions relating to guardianship

Chapter-7 Provisions relating to curatorship

Chapter-8 Provisions relating to adoption

Chapter-9 Provisions relating to inter-country adoption

Chapter-10 Provisions relating to partition

Chapter-11 Provisions relating to succession

Part-4 Law relating to property

Chapter-1 General provisions relating to property

Chapter-2 Provisions relating to ownership and possession

Chapter-3 Provisions relating to use of property

Chapter-4 Provisions relating to cultivation, possession and registration of land

Chapter-5 Provision relating to government, public and community property

Chapter-6 Provision relating to trusts

Chapter-7 Provision relating usfruct

Chapter-8 Provisions relating to servitudes

Chapter-9 Provisions relating to house rent

Chapter-10 Provisions relating to gift and donation

Chapter-11 Provisions relating to transfer and acquisition of property

Chapter-12 Provisions relating to mortgage of immovable property

Chapter-13 Provisions relating to registration of deeds

Chapter-14 Provisions relating to transactions

Part-5 Provision relating to contracts and liabilities

Chapter-1 Provisions relating to obligations

Chapter-2 Provisions relating to formation of contracts

Chapter-3 Validity of contracts

Chapter-4 Provision relating to performance of contracts

Chapter-5 Provision relating to breach of contract and remedies

Chapter-6 Provision relating to contracts of sales of goods

Chapter-7 Provisions relating to contracts of guarantee

Chapter-8 Provisions relating to contracts of bailment

Chapter-9 Provisions relating to contracts of pledge or deposit

Chapter-10 Provisions relating to contracts of agency

Chapter-11 Provisions relating to contracts of carriage of goods

Chapter-12 Provisions relating to contracts of lease

Chapter-13 Provisions relating to Hire-purchase contracts

Chapter-14 Provisions relating to wages

Chapter-15 Provisions relating to indirect or quasi contracts

Chapter-16 Provisions relating to unjust enrichment

Chapter-17 Provisions relating to torts

Chapter-18 Provisions relating to liability for defective products

Part-6 Provisions relating to private international law

## Civil service act, 2049

Date of authentification and publication: 2050-02-04 (May 17, 1993)

1. Nepal health services act, 2053 (1997)
2. Civil service act (First amendment), 2055 (1998)
3. Some Nepal acts amendment act, 2057 (2000)
4. Parliament secreteriat act, 2058 (2001)
5. Civil service act (Second amendment), 2064 (2007)
6. Federal reinforcement and some national act amending acts, 2066
7. Civil service act (Third amendment), 2070
8. Civil service act (Forth amendment), 2072

Chapter-1 Preliminary

Chapter-2 Constitution of civil services

1. Relating to central employee administration agency
2. Organization of civil services
  - Nepal engineering service
  - Nepal agricultural service
  - (Nepal judicial service)
  - Nepal foreign service
  - Nepal audit service
  - Nepal forestry service
  - Nepal miscellenaous service
  - Nepal education service

3. Classes of civil service
  - Gazetted: Special, first, second, third
  - Non-gazetted: First, second, third, forth, fifth

Chapter-3 Fulfilment of vacancy of civil service

Chapter-4 Transfer and promotion

Chapter-5 Salary, allowance, dashain expenses and other facilities

Chapter-6 Retirement, gratuity and pension

Chapter-7 Conduct

- Timeliness/punctuality and regularity
- Discipline and obedience
- Political impact should not be made
- Non participiation in politics
- Government should not be protested against
- Publication/reporting on government activities is prohibited
- Should not accept grant, present and donations
- Cannot establish company and/or business enterprise
- Cannot participate in election
- Cannot parttake in other employment or services
- Cannot seek permit for permanent residence
- Cannot parttake in demonstration and strikes
- Cannot partake in any activities that refrain from government carrying out activities
- Cannot represent trade union
- Provisions relating to organization of a trade union
- Should disclose his/her property details
- Cannot engage in torturing and extortion
- Other conduct
- Conduct towards public
- May be issued warning

Chapter-8 Service security

Chapter-9 Punishment and appeal

Chapter-10 Miscellaneous
