# Development planning

## Planned development history in Nepal 

We were awakened when the world has started to move, now the world is running and we are walking. The pace of Nepal race for development lacks significance with reference to (Most Developed Countries (MDC). Still Nepal holds some majestic and unbelievable achievement in emancipation and people oriented development mechanism. Nepal's commitment for people oriented development, response to grass root people and empowerment of marginalized people still holds reliability. It is often said "Underdeveloped nations does not lacks resources but lacks good management." When we simply make SWOT analysis of Nepal's Development four major points for each becomes enough to indicate the reality. 

Strength: Wonderful and well appreciated mechanism of development exists in Nepal. (Perfect Hardware)

Weakness: The mechanism and setup of Development are non functional due to Socio-political insensitiveness and lack of Culture. (Non Functional Software)

Opportunities: Potentially Nepal can achieve a sustainable development very soon and proactively. (People Oriented Development soon)

Threats: A common commitment and functional interest of political and social entity. (Harmonization/Participation).

Nepal development practice has been a victim of pseudo participation. This has misled development and has destructed culture of institutional thinking.

Nepal is a nation of diversities. Vertical and horizontal diversity exist in society. Economical, cultural and social stratification in Nepalese society is both the creator of dynamism and obstacles in Nepal development. Dynamism is exposed in form of community initiatives, religious harmony and others, Obstacles are out laid as conflicts and non conducive environment. Recently the conflicts in the society have come to the surface. Nepalese society is struggling for transformation. The dominating issue is that weather present transition can be managed to direct and achieve desired outputs of Nepalese societies or not. Prevailing scenarios signify a search for direction and identified efforts to nation building. Immersed in long transition from 07BS till these days Nepal Development pace lacks efficiency to lead societies to enriched processing capacity. Centralized state has failed to adjust the demand and supply of the people needs at suburbs. Thus urge for decentralization has soared high. Poverty still exists at 31%. 1 Inflation rate is double digit. 

National economy is founded by remittance hindering local resources utilization. Industrialization and mega developmental project are empty. Peace and security has lost its existence. Mass depression and many health hazards with natural disasters are striking regularly. Increasing loans and operating cost, disturbance of productive sectors and immature political culture are today's reality. Beside Nepal also possess the context same to other that of LDC's. Good Governance and its issues are frequently talked but the indicator remorse. Beside these realities people emancipation and institutionalizations are few achievements.

Basic facilities in spite of low quality are becoming accessible. Development is in operation and people have felt about the change in the scenario.

## Private sector in development

\begin{questions}

\question Discuss in brief the role of private sector in economic development of Nepal. 

\end{questions}

**Nature of private sector**

(MESI ko CC PAPER)

- Market oriented
- Efficiency
- Strategic
- Innovative
- Competitive
- Customer driven
- Profit oriented
- Accountability
- Performance management
- Economy
- Result oriented

Private sector in 15th plan

- Play a major role in overall development process
- Contribute to national development in the way envisaged by the constitution of Nepal.
- Play a role as supportive actor in achievement of the objectives related to government's vision, policy, goals and plan.
- Create investment friendly environment
- Collaborate with government and public to form PPP
- Enhance cometitiveness of production as well as service sector
- Creation of jobs and entreprenurial opportunities
- Build human capital and physical infrastructure
- Generate revenue for government

The role of the private sector in accelerating the pace of economic growth in Nepal started afterthe newly formed democratic government adopted liberalized economic policies in 1990. Earlier, the government itself operated major large industries in the country and patronized few business houses from the private sector. Over the last 25 years, the private sector has thrived in Nepal; the GDP has increased to US\$ 19. 40 billion in 2013 from US\$ 3.6 billion in 1991; the dependence on agriculture for employment has come down to 74\% in 2008 from 83\% in 1991.

The unemployment rate of Nepal is 46\% in 2012. The employment in Nepal is 54\% with the contribution of private sector in only about 25\%. For the reference, 70\% of employment is from Agriculture sector. As per World Bank report - 2011, the private sector contributes 16.34\% of GDP of Nepal. Agriculture remains Nepal's principal economic activity, employing 70\% of the population and providing 37\% of GDP. Agriculture in Nepal is mostly at the subsistence level. However, there is a vast potentiality to commercialise it through modernization and commercialization of comparative advantage products. Government of Nepal (GoN) is committed to promote private sector for national economic development. In this context, GoN has promulgated Industrial Policy 2010 with the purpose of facilitating investment by private sector in the industrial sector. For the first time GoN has given high priority in the policy to Micro-Enterprise Sector as the means of poverty alleviation targeting the Women, Poor and Excluded in rural areas and later linking them with small, medium and large enterprises for their scale up. GoN has also drafted the Industrial Enterprise Act and its By Laws that is in the process of approval by the newly formed parliament. Likewise, other several policies and acts are drafted and in the process of approval such as Special Economic Zones Act, Foreign Direct Investment Act, Investment Policy, Intellectual Property Act, revision in Company Act, Nepal Standard Act, National Trade Integrated Strategy, etc. Likewise, GoN has created several funds such as Micro, Cottage and Small Industry Fund, Women Entrepreneurs Development Fund and Technology Transfer Fund to provide direct support to Micro, Cottage and Small Enterprises (MSEs). All these initiatives taken by the government are for the purpose of creating conducive environment for economic development through enterprise development. In spite of having tremendous potentialities of enterprise development based on locally available resources (raw materials) from community forest, agriculture, mines, water, etc. the enterprise sector development in Nepal has been sluggish in the absence of low and mid level trained manpower in the specialised area. Realising the fact GoN has established Council for Technical Education and Vocational Training (CTEVT) to produce such manpower needed in different enterprise sector. CTEVT runs several courses in about 21 Training Centres and more than 500 private training centres are affiliated to CTEVT that are running different vocational training course.

After adopting economic liberalization policy and entry into World Trade Organisation (WTO), a fast and significant development has been observed in financial service sector. Before adopting economic liberalization, GoN had only three government owned Banks but now about 247financial institutions2 such as Private Banks, Finance Companies, Micro-Finance Institutes, Financial NGOs (FINGOs) and Co-Operatives which are affiliated to the central Bank and operating financial transaction all over the country. Therefore, there is no dearth of access to finance opportunities for micro and small enterprises. However, still there are policy issues to be addressed to resolve the problems of easy access of credits by micro and small enterprises.

Apart from Government and donor agencies many NGOs and INGOs are also working in Nepal for the promotion of micro and small enterprises focusing to strengthen the private sector for employment creation and for economic growth of Nepal. In order to do so, I/N/GOs have focused on upgrading the occupational skills of the youth of Nepal based on curriculums of Council of Technical Education and Vocational Training (CTEVT) and others. About 3% women and men have been upgraded skills in last one decade. To accelerate private sector, the government has also adopted policies to provide facilities to the financial institutions in the rural areas and has created a number of initiatives to support such initiatives. Numerous of them are youth self-employment fund, Rural Self Reliance Fund, Fund for Women Entrepreneurs, etc. The government has formed Investment Board to facilitate the large scale projects in the country. Recent government efforts and policies have increasingly recognized the role of private sector for employment generation and to accelerate economic growth.

Nepal is one of the poorest countries in the world, but the demand for infrastructure and capital investment is enormously high. 143 out of 144, second last from 144 countries surveyed, this is the rank of Nepal in Infrastructure as given by the Global Competitiveness Report 2012-2013 produced by the World Economic forum. Therefore, Government of Nepal (GON) has given high priority on PPPs for infrastructure development in all sectors, for instance road, transport, energy, communication, agriculture, tourism industry, production industries, etc. In order to strengthen and sustain the PPPs strategy and lure investment in Nepal, Government established 'Investment Board Nepal' in November, 2011as a one window solution for foreign investors.

Public-Private Partnerships (PPPs) is an innovative option used for delivering a public service. It is basically a contractual agreement between a public entity and a private entity, whereby the private entity performs part of a government organization's service delivery functions, and assumes the associated risks for a specified period of time. In return, the private entity receives a benefit/financial remuneration according to predefined performance criteria. The government enters into PPPs to attract private capital investment; to increase efficiency and use available resources more effectively; and to reform sectors through reallocation of roles, incentives, and accountability.The Government of Nepal has recognized PPPs as an important approach for development but country has not been able to implement PPP infrastructure project in a substantial way. Lack of clear-cut vision, political transitions, unstable government and social transformations have been the current and future constraints for the PPP approaches to be executed.

## Cooperative sector in development

\begin{questions}

\question What is the role of cooperative sector in economic development of Nepal ?

\begin{solution}

Cooperatives were initially established for raising income generating activities of group of peoples of common interest. Individuals organize into a cooperative voluntarily, cooperate for common good, and are righful to the benefits that arise.

\end{solution}

\end{questions}

## Commonly used terminologies in gender and social development

(This section may be outdated. Excepts draw from Page 9, Overview of gender equality and social inclusion in Nepal, ADB)

**Social exclusion**: Describes the experience of groups that are systematically and historically disadvantaged because of discrimination based on gender, caste, ethnicity, or religion. Exclusion occurs in public (formal) institutions such as legal or education system, as well as social (informal) institutions such as communities and households.

**Social inclusion**: The removal of institutional barriers and the enhancement of incentives to increase access by diverse individuals and groups to development opportunities. This requires changes in policies, rules, and social practices and shifts in people's perspectives and behavior toward excluded groups.

**Gender**: Refers to the socially constructed roles and identities of men and women as well as the relationships between them. These roles change over time and vary by culture. In Nepal, women face unequal power relations and gender-based barriers due to a patriarchal society.

**Caste**: Refers to the Hindu hierarchial system, which originated by categorizing people into caste groups according to the division of labor, roles, and functions. In Nepal, the "upper" castes refer to the Brahmans and Chhetris and the "lower" castes refer to the Dalits who suffer from caste- and untouchability-based practice and religious, social, economic, political, and cultural discrimination. The Dalits comprise 13% of Nepal's population and can be classified into 6 subcaste groups from the hills (Hill Dalits) and 10 subcaste groups from the Terai (Madhesi Dalits).

**Adivasi Janajatis**: People or communities having their own mother tongue and traditional customs, distinct cultural identity, social structure, and written or oral history. Interchangeably referred to as "Janajatis", "ethnic groups" and "indigenous nationalities". The government identified 59 groups as indigenous nationalities and these are categorized into 5 groups based on their economic and sociocultural status. These include "endangered", "highly marginalized", "marginalized", "disadvantaged" and "advanced" groups. Newars are Thakalis are the only two groups classified as "advanced" groups.

**Madhesis**: The definition of "Madhesi" is politically contested, but in broad terms it refers to the people who have languages such as Maithili, Bhojpuri, Awadhi, Urdu, and Hindi as their mother tongue and are considered of Madhesi origin. THey include Madhesi Brahman-Chettri (2% of population), Madheshi other caste groups (14% of the population), and Madhesi Dalits. Their exclusion is based primarily on regional identity and language.

**Muslims**: A religious group who comprises 4.3% of Nepal's population.

## Gender and social exclusion in Nepal and its development outcomes

(This section may be outdated. Contains excepts from Page 15, Overview of gender equality and social inclusion in Nepal, ADB)

Improvements in social and economic conditions in recent years include greater access to roads, irrigation, safe drinking water, schooling and health care. The government has also made notable efforts with regard to gender equality and women's empowerment. However, discriminatory institutions and structures, ideology, and social norms continue to limit women's progress. The UNDP Gender Empowerment Measure, which considers whether women are active in public and economic life, indicates that women's participation and representation remain lower than that of men in political, economic, and professional domains. Although there has been an increase in the proportion of economically active women, their earned income is about one-third that of men and women continue to have low access to property ownership, financial credit, and political power. Caste, ethnicity, and regional identity and geographical location have been strong determinants of poverty and unequal development outcomes.

Various sectoral issues have been identified in gender and social exclusion dimension. The issues or more broadly, in some cases, sectors are:

- Citizenship
- Property rights
- Family law
- The police
- Employment and labor migration
- Trafficking
- Conflict, reconciliation and peace
- Gender based violence
- Social security and protection
- Participation in governance
- Health
- Education
- Agriculture and natural resource management
- Water supply and sanitation
- Rural transport infrastructure
- Energy

### Agriculture and natural resource management

Despite the importance of agriculture and forestry to the livelihoods of poor, these are the neglected sectors for investement by the government and donors. Agriculture contributes the largest share (32\%) of gross domestic product and it is the main source of employment for 78% of the poor. Yet, the contribution of agricultural development of official development assistance (foreign aid) is only 4%, and the sector receives only 6% of pulic spending.

The ownership of land has a strong influence on food security and well-being and is a major factor determining the economic and social position and political power of most of the population. Conversely, economic status and social identity (gender, caste, ethnicity, etc.) also have a large impact on who gets access to-and control of-land. The present land tenure practices are based on the customary forms of land tenure. These are not based on the principle of equity, so huge inequalities exist in the distribution of land, 98 and a disproportionately large number of Dalits, Adivasi Janajatis, and women belong to the landless and near-landless groups of society. Of Dalits living in the Tarai, 95% are landless, and 49% of Dalits in the hills own less than 0.25 hectares.

Past experiences with land reform policies demonstrate that their implementation has not provided access of land for the landless, poor farmers, and smallholders to achieve economic growth and poverty reduction.The fourth amendment to the Land Act 1964 (1997) abolished dual owner-ship of land, but failed to acquire excess lands and redistribute them to the poor and landless due to its phased implementation of the land ceiling in districts. The struggle for tenancy rights supported by civil organizations started in 1995 and has made some progress in addressing the issues of land rights for poverty reduction. However, many tenants and poor people have yet to receive their land rights; therefore the continuation of the land rights movement and effective land reform actions by the government are necessary.

The armed conflict and large-scale out- migration of men from rural areas increased the role of women in agriculture. However, women are still not recognized as independent and autonomous farmers by the social system and legal procedures. Though women have physical access to land as users, they do not have decision-making power regarding use of the land for agriculture and for other means of production.

As land is the most important source of col-lateral, access to formal credit for the rural poor is very limited. About 71.6% of smallholders are dependent on informal sources of credit, such as private money lenders and relatives, for loans. In contrast, about two-thirds of households with large landholdings often borrow money through formal credit services such as the Agricultural Development Bank and cooperatives. Landless persons and smallholders are denied access to basic government and extension services. The extension agents are also more likely to contact men than women to provide them information and skills on technologies since women are not recognized as autonomous farmers due to their lack of legal ownership of land. As a result, agricultural extension and information on new technologies are almost exclusively directed to men, even though women are traditionally responsible for farming.

The national policies for agriculture (2004), irrigation (2003), and forestry (2000) and the Three-Year Interim Plan are the main policy documents that guide the government's strategy for agricultural development and natural resource management. The agriculture policy aims to ben-efit the poor, women, and disadvantaged groups by promoting programs for cooperative-based production, rural agriculture employment, and agricultural credit at concessional interest rates. The policy also promotes proportional representa-tion in farmers' consultative committees and equal numbers of women and men in mixed groups, and establishes gender focal points in govern-ment bodies. The irrigation policy mandates 33% participation of women and disadvantaged social groups in water users associations, and ensures financial concession and technical sup-port to them for irrigation facilities. However, the policy lacks explicit institutional mechanisms for ensuring inclusion from program development to evaluation. Irrigation policy and programming have typically ignored gender, class, and caste-differentiated needs and priorities. It has tended to emphasize the construction and maintenance of systems, efficient distribution of water, and increased agricultural output rather than issues such as the impact of irrigation on labor markets and the coexistence of productive and consumptive water uses for women, the ultra poor, and socially excluded groups. In comparison with agriculture and irrigation, forestry has a stronger approach to inclusion: it has mandated that 35% of the income of community forests be allocated to uplifting the poor. It also promotes forestry-related microenterprises, membership of a male and a female member of each household in forest-related groups, proportional representation in executive committees, and capacity enhancement and positive discrimination for women and other marginalized groups.

All ministries and departments have appointed gender focal points to oversee main-streaming of gender into sectoral program design and strategies. This is a substantial effort. However, the gender focal persons are not sufficiently senior in the bureaucratic hierarchy to have much influence, and gender focal points alone are inadequate to advocate for effective gender main-streaming. The agriculture ministry established a separate gender division led by a committed woman, which significantly enhanced awareness and capacity of the staff to address women's problems in agriculture. In irrigation, major bottlenecks include the lack of appropriate institutional structures and mechanisms, and limited understanding and capacity for mainstreaming gender and social inclusion. The forestry sector has been comparatively successful in changing the attitudes of staff and in building their capacity to make effective institutional arrangements for increasing access by excluded communities to forest resources and development opportunities.The Ministry of Agriculture and Cooperatives started integrating women into its training pro-grams early on and has established institutional structures to support gender mainstreaming in its departments, divisions, policies, and programs. It has better women's representation among staff (6%) than the Ministry of Local Development or the Ministry of Women's Affairs, yet its Gender Equity and Environment Division still faces challenges in implementing its responsibilities due to a lack of gender sensitivity, small budgets, and the lack of a gender monitoring mechanism.103The Ministry plans to set up farmers' consultative committees and village agriculture committees to ensure farmers' participation in agriculture-related activities and decision-making processes. Proportionate representation of women, Dalits, Madhesis, and Adivasi Janajatis will be ensured in these committees.

The Federation of Community Forest Users is an example of a federation that has effectively influenced policy and development processes. It has established rules to include women in the decision-making arena and it supports local groups to include women and disadvantaged groups. By law, one-third of the executive- committee members of community forest user groups must be women, but there are no stipulations for Dalits and Janajatis. Despite its success in holding the government accountable to its citizens, community forestry is not without its challenges. Elite domination of executive commit-tees marginalizes the poor, Dalits, and Janajatis. The National Federation of Irrigation Water Users Association Nepal is quite similar to the Federation of Community Forest Users in its purpose, but it has not yet been as successful in representing the voices of their women and poor members in the policy and development arenas. There is a great potential for developing organizational coalitions and networking activities in the agriculture sec-tor for advocating the rights of women and small farmers and influencing policy.The policy reform process needs to strengthen government capacity and introduce concrete implementation and accountability mechanisms to reinforce the inclusive policy statements. Though the forestry and agriculture sectors have made efforts to mainstream gender, effective institutional frameworks for gender and social inclusion are of utmost importance. The establishment of gender divisions and gender focal points could contribute to positive outcomes if they have adequate institutional authority and budgets. Improved accountability to gender and inclusion mainstreaming from the various department and division heads is also required. Institutional capacity needs to be strengthened in the irrigation sector, in particular, for inclusive policy design and service delivery.Extension systems need to promote strategies, services, and technologies that address the needs of women, the poor, and the socially excluded. Greater efforts are needed to improve poor people's access to microfinance services and to ensure that socially excluded groups have access to project services and are represented on user and decision-making bodies. For this, promotion of linkages between the finance sector, rural development planning, and other relevant agencies for planning and implementation of specific targeted programs from the national to the local levels will be crucial.
