# Geography, lifestyle, society and environment

## Geography

### Geographical division

Nepal's geography makes the country's climate particularly complex. Because of the extreme variations in elevation within short distances, Nepal's climate varies significantly across the country, ranging from alpine and arctic in the north to tropical in the south. The country experiences tropical, meso-thermal, micro-thermal, taiga and tundra types of climate (MoFSC, 2014). As illustrated in Table \ref{tab:climate-nepal}, the temperature and precipitation vary strongly with altitude. 

```{r climate-nepal}
tribble(~"region", ~"elevation", ~"climatic_zone", ~"average_annual_precipitation", ~"average_annual_temperature", 
        "High himal", "Above 5000 m", "Tundra and arctic climate", "150-200 mm", "Less than \\SIrange{3}{10}{\\celsius}", 
        "High mountains", "\\SIrange{3000}{5000}{\\metre}", "Alpine and subalpine", "\\SIrange{150}{200}{\\milli\\metre}", "Less than \\SIrange{3}{10}{\\celsius}", 
        "Middle mountains", "1000-3000 m", "Cool to warm temperate", "275-2300 mm", "\\SIrange{10}{20}{\\celsius}", 
        "Siwalik", "\\SIrange{500}{1000}{\\metre}", "Sub-tropical", "\\SIrange{1100}{3000}{\\milli\\metre}", "\\SIrange{20}{25}{\\celsius}", 
        "Terai (low-laying plains)", "Below 500 m", "Tropical", "\\SIrange{1100}{3000}{\\milli\\metre}", "\\SIrange{20}{25}{\\celsius}") %>% 
  rename_all(function(x)str_replace_all(x, "_", " ") %>% str_to_sentence()) %>% 
  knitr::kable(booktabs = TRUE, escape = FALSE, caption = "Nepal\'s climatic zones (Adapted from MoE, 2010 and MoSTE, 2014)") %>% 
  kableExtra::kable_styling(latex_options = "striped") %>% 
  kableExtra::column_spec(column = 1:5, width = c("7em", "7em", "8em", "10em", "8em"))
```

### Climate and factors affecting climate

The average condition of atmosphere, which constantly keeps changing, in connection to particular part of land over a short period of time is called weather. However, climate signifies the average atmospheric phenomena over a course of some years thereby providing information on patterns like seasons, atmospheric pressure, wind movement, rainfall etc.

Climate is not as prone to changes as weather. For a given part of earth, the climate across multiple years is somewhat uniform. For a climate record, a long duration average condition of weather is taken into account. While informing on climate, certain features of weather such as rainfall and temperature are considered. Generally the mean values of weather parameters are stated together with the time duration over which those were recorded.

Climatology ?

Not every part of the world has same climate. study of climate is based on the components that define it -- solar radiation, atmospheric pressure, wind velocity, wind direction, humidity and rainfall. It is subject to shifts with changing latitudes as imparted by the changing condtion of the components of climate. As climate derives from weather parameters, it is liable to change with geographic features of land as well.

#### Factors affecting climate

1. Latitude

It has an important role to play in condition of atmosphere at any place. Basically, as we move more northward or southward from the equator (the imaginary line segment dividing the globe into northern and southern hemisphere), the incident solar radition has lesser intensity and therefore the temperature drops significantly towards the poles. The equator passess through the 0 degree latitude. The solar radition incident at this location is almost perpendicular to the surface and has more energy per surface area than when incident upon higher latitudes, wherein insolation is much scattered.

2. Altitude

Earth's surface is not uniform and has various reliefs. With different elevations of surface the atmospheric states such air pressure and temperature of the location concomitant are different. In lower elevations, atmospheric pressure as well as temperature tends is higher while climbing to hills, we find lower atmospheric pressure and milder temperatures. If a region lies in great height, it is very likely that temperatures therein in cold. It is generally accepted that with increase in every 160 m in elevation, temperature drops by 1 degree C.

3. Distance from sea
4. Presence of hills and mountains
5. Nature of wind
6. Slope of land

Regions oriented towards the sea/ocean are generally humid while the slopes facing larger continent tends to be more dry and arid as well. Likewise the slopes orienting east or westward are warmer than those facing north or southward due to incidence of incoming solar radiation.

7. Ocean current
8. Vegetation

7. Ocean current

\begin{questions}

\question What are the geographical features of Nepal ? Mention in brief.

\question What are the different types of climates occuring in Nepal based on the geographical features ?

\end{questions}

### Tourism

\begin{questions}

\question Describe tourism and its prospects in context of Nepal.

\begin{solution}
Nepal with rich ancient cultures set against the most dramatic scenery in the world is a land of discovery and unique experience. For broad minded individuals who value an experience that is authentic and mesmerizing, Nepal is the ideal destination. Come and revel in the untouched and the undiscovered and uncover yourself.

It is unsurpassed that the sheer diversity Nepal boasts, from steamy jungle and Terai to the icy peaks of the world’s highest mountains means that the range of activities on offer. Trekking, mountaineering, rafting in spectacular scenery are just three things Nepal is famous for. Activities as diverse as Elephant Polo and a micro-light flight through the Himalayas show that in Nepal, the only boundary is your imagination. With 15 National and Wildlife Parks (two are UNESCO Heritage sites) Nepal is one of the last places on earth you can spot the Asiatic rhinoceros and the Royal Bengal Tiger.

For many, Nepal’s greatest attraction is its people. The traditions and famous hospitality of its many different groups are indeed a major part of what makes Nepal so special. From remote mountain villages to medieval hill-towns and the ancient cities of the Kathmandu Valley, the people of Nepal are always welcoming. Come and experience the strong and unique flavors of Nepalese cuisine, prepared with love and a depth of flavor or join in and celebrate at one of the many festivals year round. In fact, with more festivals than days of the year, there is nowhere else in the world that can offer as many festivities as Nepal.

Tourism is one of the mainstay of Nepalese economy. It is also a major source of foreign exchange and revenue. Possessing 8 of the 10 highest mountains in the world, Nepal is a hotspot destination for mountaineers, rock climbers and people seeking adventures. The Hindu, Buddhist and other cultural heritage sites of Nepal, and around the year fair weather are also strong attractions.

Nepal is the country of the Mount Everest, the highest mountain peak in the world, and the Birthplace of Gautama Buddha- Lumbini. Mountaineering and other types of adventure tourism and ecotourism are important attractions for visitors. There are other important religious pilgrimage sites throughout the country for the followers of various sects and religions.

According to statistics from Nepal Tourism Board (NTB), a total of 598,204 foreign tourists entered the country via aerial route in 2012. The government of Nepal declared 2011 to be Nepal Tourism Year, and hoped to attract one million foreign tourists to the country during that year. The tourist industry is seen as a way to alleviate poverty and achieve greater social equity in the country.

Wilderness tourism

Nepal’s major tourist activities include wilderness and adventure activities such as mountain biking, bungee jumping, rock climbing and mountain climbing, trekking, hiking, bird watching, mountain flights, ultralight aircraft flights, paragliding and hot air ballooning over the mountains of the Himalaya, hiking and mountain biking, exploring the waterways by raft, kayak or canoe and jungle safaris especially in the Terai region.

Religious sites

Nepal is a multi-religious society. The major religion in Nepal is Hinduism, and the Pashupatinath Temple, which is the world’s one of the main Hindu religious sites is located in Kathmandu, attracts many pilgrims and tourists. Other Hindu pilgrimage sites include the temple complex in Swargadwari located in the Pyuthan district, Lake Gosainkunda near Dhunche, the temples at Devghat, Manakamana temple in the Gorkha District, and Pathibhara near Phungling, Mahamrityunjaya Shivasan Nepal in Palpa District where biggest metallic idol of Lord Shiva is located.

Buddhism is another main religion. The World Heritage site Lumbini, which is the birthplace of Gautama Buddha, is an important pilgrimage site. Another prominent Buddhist site is Swayambhunath, the Monkey Temple, in Kathmandu. Dang valley is also a sacred place for Hindus as well as other religions. Kalika and Malika Devi in Chhillikot hill, Ambekeshawori temple, Krishna temple, Dharapani temple etc. are sacred place in Dang district. Chillikot hill is also a good place for sightseeing and also an ancient palace of a king. Muktinath is a sacred place for Hindus as well as Buddhists. The site is located in Muktinath Valley, Mustang district.

Culture and Heritage Sites

Kathmandu the capital city of Nepal is the city of temple and very rich in cultural heritage. Within 7 km radius there are 7 world heritage sites (Pashupatinath Temple, Baudhanath Stupa, Swayambhunath Stupa, Changunarayan Temple, Kathmandu Durbar Square, Patan Durbar Square and Bhaktapur Durbar Square) which cannot be found anywhere. Museums in Kathmandu have rich collections of archaeological, historical and artistic importance and galleries display art work of the past and present. Full of art, architecture and culture, the Kathmandu Valley is the prime destination for the tourists. As Nepal is a land of festivities and celebrations, visitors can experience how a culturally diverse and rich society of Nepal grooms in harmony.

Major Tourism Activities in Nepal

Mountain Climbing

The 800 km stretch of the Nepal Himalayan is the greatest in the world with eight peaks that rise above 8,000m including the highest in the world, Mt. Everest. Ever since the country opened its peaks to climbers in 1994, the Nepal Himalayan has become a great theatre of mountaineering activity and the drama of success and failure have provided impetus to thousands of men and women to meet the ultimate challenge. The Nepal Himalayan has been an attraction to many people, be they saints, philosophers, researchers or adventures.

Trekking

The best way to experience Nepal’s unbeatable combination of natural beauty and culture riches is to walk through them. One can walk along the beaten trails or virgin tracks. Either way you are in for an experience for a lifetime. Along with forests of rhododendron, isolated hamlets, and small mountain villages, birds, animals, temple, monasteries and breathtaking landscapes, you will also encounter friendly people of different cultures offering a fascinating glimpse of traditional rural life.

Bird Watching

Nepal is a paradise for bird lovers with over 646 species (almost 8% of the world total) of birds, and among them almost 500 hundred species are found in Kathmandu Valley alone. The most popular bird watching spots in Kathmandu are Phulchoki, Godavari, Nagarjun, Bagmatiriver, Taudaha and so on. Get your binoculars and look forward to a rewarding experience.

Rafting/Kayaking/Canyoning

Rafting is one of the best ways to explore the typical cross section of natural as well as ethno-cultural heritage of the country. There are numerous rivers in Nepal which offer excellent rafting or canoeing experience. You can glide on calm jade waters with munificent scenery all about or rush through roaring white rapids, in the care of expert river-men employed by government authorized agencies. One can opt for day of river running or more. So far, the government has opened sections of 10 rivers for commercial rafting. The Trisuli river is one of the most popular of Nepal’s raftable rivers. The Kali Gandaki winds through remote canyons and deep gorges for five days of intense rapids. The BhoteKoshi is 26km of continuous white water and the raging Marshyanghi is four days of uninterrupted white water. The Karnaliriver provides some of the most challenging rapids in the world. The Sun Koshi , 27km, requiring 8-10 days to complete, is a big and challenging river. Adventurers are provided with world-class services by rafting agents. Agencies here provide life jackets, camping and the standard rafting paraphernalia needed by world-class rafting. An extremely popular sport in Europe, cannoning is now available in Nepal. Cannoning gives you the freedom to explore some of the most ruggedly beautiful, yet forbidden places in the world.

Hot Air Ballooning

Hot air ballooning is very popular with tourists for it affords the most spectacular bird's-eye view of the Kathmandu valley and the Himalayan ranges towering in the background. On a clear day it's a superb way to view the Himalayan (from over 6000m up), and the view of the valley is equally breathtaking.

Bungee Jumping

The ultimate thrill of a bungee jump can now be experienced in Nepal at one of the best sites that this sport can boast of anywhere in the world. Nepal's first bungee jumping site is situated 160m. Over the BhoteKoshiriver, inviting you to experience the ultimate adrenaline rush in the surroundings of this amazing place. The jump, at 160m., is staffed and operated by some of the most experienced jumpmasters in the business.

Paragliding

Paragliding in Nepal can be a truly wonderful and fulfilling experience for the adventure seeking. A trip will take you over some of the best scenery on earth, as you share airspace with Himalayan griffins vultures, eagles, kites and float over villages, monasteries, temples, lakes and jungle, with a fantastic view of the majestic Himalayas.

Ultralight Aircraft

Ultralight aircraft take off from Pokhara and offer spectacular views of the lakes, mountains and villages. This is an ideal way to see life from a new perspective. The choice of Pokhara Valley for ultra-light aircraft is appropriate chiefly because of the proximity of the mountains, and the scenic lakes. For those who wished they could fly birds when growing up, this flight is a must. It might be lonely at the top, but this flight is a must. It might be lonely at the top, but the spectacular view from up high certainly makes it all worth it. Flights are from the Pokhara airport beginning September through June. The flights take place from sunrise to 11 a.m. and from 3 p.m. to sunset every day during these months.

Mountain Biking

The best way to explore the Kathmandu Valley is on a mountain bike. Nepal’s diverse terrain is a mountain biker’s dream adventure comes true. Mountain biking offers an environmentally sound way of exploring this magnificent country, its landscape and living heritage. There are plenty of dirty roads and trails in Nepal to meet every mountain biker’s wildest fantasy. Mountain biking is specially recommended if you wish to explore urban centers of Nepal such as Pokhara and Kathmandu as well as the countryside. Adventurous souls may plan extended trips to such exotic locals as Namche Bazaar, and western Nepal. You could even do the entire length of Nepal across the plains. Mountain bikes are available for rent by the day or longer in many of the bicycle rental outlets in Nepal and around the city.

Jungle Safari

National Parks located specially in the Terai region in Nepal attract visitors from all over the world. A visit to these parks involves game- stalking by a variety of means-foot, dugout canoe, jeep, and elephant back. One is bound to sight a one - horned rhino or two at every elephant safari. Besides the rhinos, wild boars, samburs, spotted deer, sloth bear, four-horned antelope are also usually seen. A Royal Bengal tiger may surprise you by his majestic appearance.

Mountain Flight

Only awe-stricken silence can come close to matching the experience of going on a mountain flight to encounter the tallest mountains on earth. Mountain flights offer the closest possible aerial views of Mt. Everest, Kanchenjunga and the Tibetan Plateau. Mountain flights appeal to all category of travelers and have become a popular tourist attraction of Nepal. For those who are restricted by time or other considerations from going for a trek, these flights offer a panoramic view of the Himalayan in just one hour.

Rock Climbing

For all those cliffhangers out there, Kathmandu offers a roster of stone walls that make for an experience of a lifetime. Now of late, Rock climbing has become a popular sport in Kathmandu, which offers some really terrific places for rock climbing. Nagarjun, Balaju, Shivapuri and Budhanilkantha are some of the places where you can try this sport.

source: \url{https://mofa.gov.np/about-nepal/tourism-in-nepal/}
\end{solution}

\question Explain the role of tourism sector in the economic development of Nepal.

\begin{solution}
Tourism is one of the highly potential sectors for economic development of Nepal as it expands the opportunities for employment, income generation through indirect involvement and direct earning of the foreign currency.

The home country to 8 of the world's top 10 highest peaks, birthplace of the Gautam Buddha and a center of faith for large swathe of hindu piligrims around the world, Nepal, also hosts numerous culturally rich societies as well as world heritage sites.

According to World Travel and Tourism Council (WTTC) annual report in 2018, travel and tourism is one of the world's booming industries, generating approximately 8.8 trillion USD annually. Over 600 million international tourists visit different parts of the world every year.

According to Lonley Planet, Kathmandu is the 5th top travel destination in the world for the year 2019. Recent years have seen positive signs of progressing tourism industry with the increase in inflow of foreign tourists after the devastating 2015 Earthquake. According to economic survey, 2018/19, the number of tourists arrivals in 2018 (not counting tourists who arrived by land) was 1173072, which is 25% more than 2017. The tourism industry brought in foreign currency equivalent to 76.09 billion NRS in the FY 2017/18.

In 2018, the number of registered travel agencies reached 3508 and trekking agencies 2649. Government has formulated policies and allocated a budget of Rs 2.68 billion for the FY 2019/20 to support tourism sector in developing infrastructure and encouragin environment-friendly tourism activities. Rs 15.85 billion has been allocated for aviation sector improvement in the same year. Unfortunately worldwide spreading of COVID-19 pandemic, which reinstated nationwide lockdowns and tightened travel restrictions, caused government to retract its plans for launching a Visit Nepal 2020 campaign.

\end{solution}

\question Discuss about the major impacts on people's lifestyle due to the geographic conditions of Nepal.

% \makeemptybox{1.5in} % use this to provide a box in question
\begin{solution}

Physical geography is the study of natural features and phenomena on the planet's surface and our interactions with them. These features include vegetation, climate, the local water cycle, and land formations. Geography doesn't just determine whether humans can live in a certain area or not, it also determines people's lifestyles, as they adapt to the available food and climate patterns. As humans have migrated across the planet, they have had to adapt to all the changing conditions they were exposed to. At first, particular cultures develop because of the physical landscape. Over time, those cultures exert their own influence on the landscape around them.

Life cannot be the same in arctic regions as in the tropics; nor upon deserts of drifting sand as upon the grassy steppes which afford the natural home for wandering shepherds and their herds; nor upon the seacoast with its fisheries and commerce as among the mountains with their forests and mines. But it is not alone the extreme and unusual manifestations of nature which affect the life of man. So relatively inconspicuous a fact as the presence of a creature adapted to become a beast of burden might enable one people to grow into a triumphant race, contributors to a dominant civilization, and the absence of such a creature might condemn another race to backwardness and final extinction.

Geography, in overall, affects socio-economic lifestyle of people in following ways:

\begin{enumerate}
\item Geographic conditions determine the size of populations.
\item The economic occupations of a people are determined by their geographic environment.
\item Stagnation or progression are conditioned largely by geographic surroundings.
\item Lawlessness is the natural consequence of geographic inaccessibility
\item The form of government is affected by geographic conditions
\item Tastes and social and domestic customs are influenced by geographic conditions: Football is out of place in the tropics, and ice-skating is impossible. Athletic sports are indigenous to cool climates, and are the objects of amazement to inhabitants of torrid regions. The long evenings of the northern winter call into being suitable pastimes.
\item Ethical differences are largely influenced by geographic environment
\item Mythologies and religions are influenced by geographic environment: What the nature-myths of a people shall be depends in part upon what aspects of nature in their neighborhood are most impressive, whether they live by the sea, upon the banks of a great river, among the mountains, in the depths of the forest, or on a plain where the overarching sky with sun and stars chiefly command the gaze. The existing form of earthly power and authority tends to shape man's notion of divine rule.
\item Geographic conditions affect the moods and psychic tendencies of a people: General vital processes, upon which the action of the brain and nervous system depends, affected by conditions of heat, light, and moisture, but the nerves themselves are directly stimulated or depressed. To this cause has been ascribed the fact that the cradles of civilization have been found in dry regions like the Egyptian oasis in the desert, and the plains of Iran and of Central America. Not only does climate affect the permanent tendencies of races, but passing changes of the seasons affect the moods of men. Alternations of the seasons give variety to life and stimulation to the imagination.
\item Routes followed by migration, war and commerce have been marked out by geographic highways, and these have been the great distributers of human populations, customs, and commodities.
\end{enumerate}

\textbf{Land Formation}
Land formation is the physical shape of an area and the several processes that help form that shape. One process that makes a big impact is plate tectonics: the movements of crustal plates on the Earth's surface. These plates are constantly sliding past and colliding into one another. Plate movements can affect the availability of water by disrupting rivers and they disturb land formations that humans have settled on, like an earthquake ravaging a major city. Animals hunted by humans for food can be displaced as well, forcing people to move to another area to survive. Thronging cities are found at points of geographical advantage.

\textbf{Soil}
Soil carries out several functions that profoundly impact human activity. Soil recycles nutrients, regulates water quality, sustains life, and provides structural support for buildings. Without healthy soil, a previously fertile area turns into a desert, making it difficult to sustain vegetation and prevent massive loss of life. Soil doesn't just provide for agriculture, it also helps modern life because it contains minerals. These minerals include ore, which contains metals used for electronics and peat used for heating. People may move temporarily to more fertile areas to provide for their families, especially if they live in poorer countries like Kenya.

\textbf{Water Access}
Water is purified by evaporation into the atmosphere, from where it falls back to land and the oceans through rainfall. All humans need water to survive, and depend on regular rainfall and other sources of clean water for drinking and agriculture. Water is found above, on, and under the ground. People tend to settle near bodies of water such as oceans, rivers, and lakes for easy access to large amounts of water. For example, nearly the entire population of Egypt is concentrated around the delta of the Nile River because the rest of the country is an arid desert.

\textbf{Climate}
Climate is the pattern of variation in temperature, humidity, and pressure over an area for long periods of time. There are several types of climates: tropical with high rainfall and temperatures over 18 degrees Celsius, dry, subtropical with mild winters, continental with cold winters, and polar. People have not only adjusted their clothing and housing based on temperature, but their bodies have also adapted. The Masai people have longer limbs that help them lose body heat in the warm climate of East Africa. Arctic-dwelling Inuit adapted by storing more body fat and increasing metabolic rates.
\end{solution}

\end{questions}

## Culture, language, religion and demographics

\begin{questions}

\question (Long answer type) "Foreign employment significantly contibutes to customs earning of Nepal". Briefly elaborate the statement.

\question What is the current status of languages used in Nepal according to Language Commission ?

\begin{solution}

Six new languages have been added to the list of 123 languages spoken in Nepal. These newly discovered one include:

Kanchanpur: Rana Tharu,
Manang: Nar Phu,
Gorkha: Chum (Syaar) and Nubri (Larke),
Dolpa: Poike, and
Mustang: Serake (Seke)

Current Chairman of the Language Commission Dr. Lava Dev Awasthi submitted the annual report to President in her Office at SheetalNiwas. Prior to it, the national census 2068 had enlisted 123 languages as the languages spoken in Nepal. The list then had grouped 68 languages of the Sino-Tibetian family, 48 languages of Indo-European family and one each of Dravidian family (Uraon-Kudukh) and Austroasiatic family (Santhali) and a language with anonymous identity (Kusunda) as in different language families.

There are 19 languages with more than 100,000 speakers. This consists of 95.91\% of the total population. Among other languages spoken by the rest of the population 24 languages like Dura, Kusunda, Tilunga have a small number of speakers which has ultimately led them on the verge of extinction.

Among others at stake are: Pali, Sankskrit and Bhot.

The report blames excessive craze for English, colonial mindset and the illusions generated by the global market substituting the local one for endangering glorious linguistic diversity and multicultural lifestyle of Nepal.

To facilitate its activities the commission has prepared the list of experts of 101 languages.

The Commission has suggested to form a High-Level Linguistic Policy Determination Committee and assign it the task of coordinating and facilitating various activities related to the constitutional and other legal provisions related to language.

\end{solution}

\question How are indigeneous and local ethnic groups prioritized in Nepal ? Mention what strategies are taken by government to that end.

\question Write about the "Chepang" ethnic group.

\begin{solution}

Chepangs are an indigenous Tibeto-Burman group of people from the south-central region of Nepal. Over the past two or three generations, the Chepang have begun to slowly shift from a semi-nomadic (slash-and-burn) lifestyle to a more settled way of life, relying increasingly upon the production of permanent fields of maize, millet and bananas. The severe topography, however, has made permanent farming difficult (and usually insufficient), and the forest has remained an important (although decreasingly so) source of food for the Chepang. Historically, the collection of wild yams and tubers, fish caught from nearby rivers, bats and wild birds, and periodically wild deer hunted from nearby forests, have supplemented their need for carbohydrates and protein. With increasing populations, lack of arable land and few irrigation options, malnutrition has been a historic problem for the Chepang despite forest supplements. 

The Chepang have often been characterized as the poorest of Nepal's poor.
According to the recent Nepal Living Standard Survey, almost 90 percent of Chepangs live below the poverty line, earning around 6,000 Nepali rupees per capita annually. Forced teenage pregnancies are common among this community members. Chepang men and women are basically egalitarian and no social ranking exists as it does in caste Nepalese society. Many Chepang cannot read and write due to a lack of education beyond elementary school, and this illiteracy stands in contrast to the great gains Nepal has been making in reducing illiteracy. According to the 2001 Nepal Census, there are 52,237 Chepang in the country, of which 67.63\% were Hindu, 23.38\% were Buddhists, 7.74\% were Christians, and 1.25\% others. They are mostly located in Dhading District, Chitwan District, Gorkha District, Makwanpur District, and Tanahu District.

The Chepangs themselves follow Animism, although they are strongly influenced by both Hinduism and Buddhism, which came from the Tamangs just north of them. They observe all the Hindu festivals of Dashain, Tihar and Sakrantis besides their own tribal festival Nwagi or Chhonam, which is performed on a Tuesday during third week of Bhadra (some day in August and September). Chhonam is the auspicious day for eating a new crop. Before the celebration of this festival, eating certain agricultural products is prohibited.

In the 5th National Gathering of Chepang, 2004, it was stated they practiced Prakriti (Nature), with ancestor worship as most important. They worship many deities including Bhumi, Aita Bare, Gaidu, Namrung etc. (earth deity) etc. They also observe other different festivals like, Maghe Sakranti, Saune Sakranti, Dashain, Tihar.

The language is also known as Chepang but is called Chyo-bang by the people themselves. These people are also called "Praja" meaning "political subjects". The people speak 3 different dialects of this Tibeto-Burman language that is closely related to Raute and Raji, two undocumented languages spoken in western Nepal.

Chepang language is one of the few languages which uses a duodecimal (base 12) counting system rather than the decimal (base 10). 

Over the last decade, there has been increasing awareness among Nepalis regarding the plight of the Chepang people. Simultaneously, there has also been an rise in the number of NGOs working to support and uplift the livelihoods of Chepang communities.

source: \url{https://kathmandupost.com/miscellaneous/2016/01/02/the-chepang-people-of-chitwan-and-their-conversion-to-christianity}; \url{https://en.wikipedia.org/wiki/Chepang_people}
\end{solution}

\question Write in brief about the Lhosar festival celebrated in Nepal.

\question Write in brief about culture and society of Nepal.

\begin{solution}

Culture and Society of Nepal

The culture of Nepal is rich and unique. The cultural heritage of Nepal has evolved over the centuries. This multi-dimensional heritage encompasses the diversities of Nepal’s ethnic, tribal, and social groups, and it manifests in music and dance; art and craft; folklore and folktales; languages and literature; philosophy and religion; festivals and celebration; foods and drinks.

Dance and music

Legends state that dances in the Indian subcontinent originated in the abode of Lord Shiva — the Himalayas and the Himalayan Kingdom of Nepal — where he performed the tandava dance. This indicates that dance traditions of Nepal are very ancient. With altitudes and ethnicity, the dances of Nepal slightly change in style as well as in the costumes. The Dishka, a dance performed at weddings, includes intricate footwork and arm movements. Accompanying music and musical instruments change in tune with the themes, which revolve around topics like harvesting of crops, marriage rites, war stories, a lonely girl’s yearning for her love, and several other themes and stories from everyday life in the villages.
Languages and literature

As per the 2011 census, 123 languages are spoken in Nepal. Nepal’s linguistic heritage has evolved from three major language groups: Indo-Aryan, Tibeto-Burman, and indigenous. The major languages of Nepal (percent spoken as mother tongue) are Nepali (44.6%), Maithili (11.7%), Bhojpuri (6%), Tharu (5.8%), Tamang (5.1%), Nepal Bhasa (3.2%), Magar (3%) and Bajjika (3%).

Nepali, written in Devanagari script, is the official national language and serves as lingua franca among Nepalese ethno-linguistic groups. Maithili language that was originated in Mithila region of Nepal is the de facto official language of Nepal and Madhesh as a whole. Maithili is spoken in Nepal as a second language. Extinct languages of Nepal include Kusunda, Madhesiya and Waling.

Religions and philosophy

The 2001 census identified 80.6% of the population being Hindu. Buddhism was practiced by about 11% of the population (although many people labelled Hindu or Buddhist often practice a syncretic blend of Hinduism, Buddhism, and/or animist traditions). About 3.2% practice Islam and 3.6% of the population follows the indigenous Kirant religion. Christianity is practiced officially by less than 0.5%.

Hindu and Buddhist traditions in Nepal go back more than two millennia. In Lumbini, Buddha was born, and Pashupatinath temple, Kathmandu, is an old and famous Shiva temple of Hindus. Nepal has several other temples and Buddhist monasteries, as well as places of worship of other religious groups. Traditionally, Nepalese philosophical thoughts are ingrained with the Hindu and Buddhist philosophical ethos and traditions, which include elements of Kashmir Shaivism, Nyingma school of Tibetan Buddhism, works of Karmacharyas of Bhaktapur, and tantric traditions. Tantric traditions are deep rooted in Nepal, including the practice of animal sacrifices. Five types of animals, always male, are considered acceptable for sacrifice: water buffalo, goats, sheep, chickens, and ducks. Cows are very sacred animals and are never considered acceptable for sacrifice.
Festivals and celebrations

Several of the festivals of Nepal last from one to several days. Dashain is the longest and the most important festival of Nepal. Generally Dashain falls in late September to mid-October, right after the end of the monsoon season. It is “a day of Victory over Demons”. The Newars celebrate the festival as Mohani. Tihar or Swanti and Chhath are another important festivals of Nepal. New Year’s Day of the lunar calendar Nepal Sambat occurs at this time.

Other important festivals include Buddha Jayanti (the celebration of the birth of Buddha)Maha Shivaratri (a festival of Lord Shiva) and during Maha Shivaratri festivities, some people consume excessive drinks and smoke charas.Sherpas, mostly located at higher altitudes and in the Mount Everest region, celebrate Mani Rimdu, for the good of the world.

Most festivals include dancing and music, and a variety of foods are consumed during festivals and on special occasions.

The Sagan ceremony is the ritualized presentation of five food items (boiled egg, smoked fish, meat, lentil cake and rice wine) to a person which is done to bring good fortune as per Tantric tradition.

Architecture and archeology

Nepal Sumpada Sangha (Nepal Heritage Society) has compiled an inventory of 1,262 significant architectural and archeological sites in Nepal outside Kathmandu Valley.

source: \url{https://mofa.gov.np/about-nepal/culture-society/}

\end{solution}

\question Write an essay that discusses how different cultures maintain their distinctive tradition in your community. In what ways does this cultural diversity have a positive impact on your community ?

\end{questions}

- Refer to wikipedia link \url{https://en.wikipedia.org/wiki/Demographics_of_Nepal}, for demographic statistics of Nepal. This includes
  - Population growth
  - Vital statistics: Live births per year, Deaths per year, Natural change per year, CBR, CDR, NC, TFR, IMR
  - Population structure: Based on age group
  - Ethnicity statisics
  - Languages
  - CIA factbook summary
  - Religion, etc.

## Social and environment problems

### Historical context of Dalits in Nepal

The State formalized the caste system throughout Nepal during the reign of King Surendra Bikram Shah when Jung Bahadur Rana, founder of the Rana rule, promulgated the Muluki Ain (Country Code) in 1854. This Code, the first proclamation of State authority on all matters concerning the social and religious rights of individuals, organized Nepalese caste and ethnic groups into four categories: i. Tagadhari (caste wearing the holy thread); ii. Matwali (non enslaveable alcohol-drinkers); iii. _Pani nachalne_- _chhoi chhitto halnu naparne_ (castes from whom water is not accepted, but whose touch does not require sprinkling of water for purification); and iv. _Pani nachalne_ - _chhoi chhitto halnu parne_ (from whom water is not accepted and whose touch requires purification by sprinkling water).

The Country Code thus reconstructed Nepalese social structure into a four-fold caste hierarchy and placed _Dalits_ – the groups belonging to the fourth category, at the bottom. Before the implementation of the law, the indigenous nationalities had an egalitarian social structure and were outside the four-fold Varna and Hindu caste system. As the Code was the first law applicable throughout the country, the practice of untouchability became universalized. The Code also divided Dalits themselves hierarchically. This compelled Dalits to practice untouchability and discriminate against those who ranked below them within the broad group of untouchables.

Although the country later witnessed significant political turmoil, including the overthrow of the Rana regime in 1950 and the establishment of politically egalitarian governance in 1958, the Country Code of 1854 remained in force with only moderate informal adjustments until 1963, when the _Naya Muluki Ain_ (New Country Code) was enforced under the Panchayat System. This New Code marks the beginning of a new era of the most radical changes in Nepal because it stated that legally all citizens are equal irrespective of caste, creed and sex. The _Muluki Ain_ of 1963 also abolished discrimination between castes in respect of capital punishment. However, it did not declare the practice of untouchability punishable.

The restoration of democracy in 1990 intensified the voices of subjugated groups. The new Constitution of 1990 reiterates the universality of human rights, equality among Nepalese citizens in respect of rights and responsibilities, and also declares discrimination on the basis of caste punishable. Despite the reform measures introduced during the last four decades, little has changed in Nepal’s social structures, norms and practices, including the attitudes and behaviours of nonDalits towards Dalits - or among Dalits themselves.

### Kamaiya (Bonded labor)

The Kamaiya, a complex farm wage labour system prevalent in eight Tarai districts, engulfed about 20,000 households, most of which were forced to pledge family labour in return for meagre amounts of food crops and, in addition, were bonded by loans they had incurred to ensure their survival. In response to mounting pressures from human rights and civil society organizations, the government ultimately recognized the problem and, in July 2000, abolished the system. 

Subsequently, the Prohibition of Bonded Labor Act, 2002 made the perpetuation of the system punishable. After the adoption of the Act, governmental efforts to assist the ex-Kamaiyas provided plots of up to 0.15 hectares, along with assistance in the construction of huts. Other agencies offered aid in skill development, education, health and other elements of empowerment. As the households are resource-poor, however, they need access to employment opportunities above all – to which they have received little response. More ex-Kamaiya children than ever before now work as domestics in urban areas, more ex-Kamaiya women perform unpaid household chores for local landlords, and many ex-Kamaiya men have reverted to the same labour relations from which they were presumably freed.

The key reasons for the ineffectiveness of the rehabilitation
of _Kamaiyas_ include lacking of integration into their own villages, along with the feeble legal and social safeguards appropriate to agricultural laborers.

Despite some monetary aid disbursed since July 2000 by the government, United Nations agencies, more than a dozen international NGOs and even the Asian Development Bank, ex-Kamiayas report few changes in their living conditions, apart from the dissolution of their bond.

But freedom without economic empowerment has done little indeed to mitigate their misery, the more so as many have had to bond themselves anew for survival. Field research indicates that the children and women probably suffer more now than they did prior to their liberation.

### Discrimination against People with Disabilities (PwDs)

Discrimination against PwDs is rampant in all communities in general and in rural/ remote communities in particular. Even their families tend to neglect their basic needs (enough food, clothing, care concerning personal hygiene and medical treatment equal to that of the non-disabled). PwDs often languish in a corner or an isolated room or outside homes altogether (where they can be housed separately), without proper care and participation in day-to-day household activities or in any other cultural and religious activities. Beliefs in disabilities as the result of sins committed in prior lives, illiteracy, poverty, humiliation, and lack of awareness and information have resulted in the relegation of these individuals to the lowest rung of each stratum of society. Women with disabilities face multiple disadvantages because of their sex coupled with their poverty.

The first government program to help disabled persons began in 1964 in the field of Special Education (Integrated Education) for the blind and visually impaired, followed by its 1967 enlargement to accommodate deaf children and its 1969 admission of physically disabled children. The Special Education Council was established in the Ministry of Education in 1973. During the International Year of Disabled Persons, 1981, special education was expanded in all the five development regions for all types of disabled persons. 

The advent of democracy in 1990 and the concomitant constitution guaranteed the rights, welfare and security of PwDs equal to other citizens without discrimination. The Tenth Plan addresses these issues, including the mainstreaming of PwDs in national development. Yet although the government promulgated the Disabled Protection and Welfare Act in 1982, practices remained unchanged even after Rules were adopted for the implementation of the Act in 1993.

Currently, Social Welfare Council supports income-generating program; and a number of NGOs provide soft loans. United Nations agencies, I/NGOs, Community Based Organizations (CBOs) and volunteer organizations also provide financial and technical support.

The Act Relating to Rights of Persons with Disabilities, 2074 (2017) enacted pursuant to Clause (1) of Article 296 of the constitution of Nepal, 2015 has included following features  in order to respect their civil, political, economic, social and cultural rights by doing away with discrimination against persons with disabilities and to ensure the environment that enables persons with disabilities to earn self-reliant and respectful living by empowering persons with disabilities and getting them to have participation in the process of policy making, and development. Following points highlight some of the features of the Act:

- Classification of disability
- Provisions relating to disability identity card
- Provision of maintaining of records by local level
- Rights of persons with disabilities
  - Rights granted under the prevailing law on an equal basis with others
  - Right against discrimination
  - Right to community life
  - Right to protection against any kind of inhuman or degrading treatment, physical or mental violence, gender-based violence, domestic violence, sexual harassment and exploitation by the family guardian or other person.
  - Right to political participation
  - Right to participation in policy making
  - Right to form unions
  - Right to participate in the cultural life
  - Right to access to services, facilities and justice
  - Right to social security
  - Right to information
  - Right to movement
- Additional rights of women and children with disabilities
- Provisions relating to education of persons with disabilities (Governmental operated education institutions to provide free higher education)
- Provisions relating to scholarship and financial assistance 
- Provisions relating to skill development and employment
- Provisions relating to health, rehabilitation, social security and recreation
- Facilities and concessions to persons with disabilities
- Recognition of a Steering Committee (Chaired by Minister, Ministry of Women, Children and Senior Citizens) for the functions including to co-ordinate, monitor, promote the activities related to the rights, facilities, services and protection of the persons with disabilities and to give direction in the activities related thereto.
- Responsibility of the Government of Nepal, Provincial government and Local level towards the persons with disabilities.
- Protection and enforcement of the rights of, and responsibility towards, the persons with disabilities.
- Recognition of offences and punishment to perpetrators of hatred, disregard or neglect towards the persons with disabilities.
- Miscellaneous provisions

### Gender based violence

### Poverty

\begin{questions}

\question (Long answer type) Briefly analyse the existing situation of poverty in Nepal. Also mention the measures to be taken for poverty reduction in future.

\begin{solution}

Poverty alleviation

The state of economic and social backwardness is called the poverty. A set of economic and humanitarian measures, strategies and activities intended to permanently lift people out of poverty is known as poverty alleviation/reduction. There are policy, legal and institutional efforts being made in Nepal to reduce poverty.

The consitution of advocates and the sustainable development goals have highlighted social security and justice for people of all gender, regions while lending special emphasis to economically backwarded group of people in the society. Several programmes launched in the past two decades attempted to address the issue of poverty reduction and since the 10th five year plan, the issue was tackled systematically. Povery was categorized in three dimensions -- income poverty, human poverty and social deprivation. Currently more than 50 programmes aimed at lifting poor of their status are launched. In order to ensure that such programmes recognize true poverty stricken households and provide require interventions, a task of poor household identification and issuance of identity card to those has been on-going. Consequently, Nepal has made a significant progress in addressing poverty and improving human development index (HDI). Still, currently 18.7% of the population lie below poverty line and 28.6% of population is poor according to multidimentional poverty index (2018/19). This means we are still far from being established as a affluent nation.

Sustainable development goals envisages, all multi-dimensional indicators of poverty addressed, which includes increament of per capita income and reduced economic inequality among classes of people of different geographical locations, gender and social sectors and reformed national efforts towards this end in future. Similary, efforts of public, private and community and NGO, INGO, including development stakeholders need to be concerted and streamlined with strong cooperation for poverty reduction.

The 15th plan foresees a reduced absolute poverty rate to 11% and multidimensional poverty indicator to 13% by the end of planning period. Likewise it approaches for significant improvement of economic inequality between different income group of people.

Apart from strategic and working course of action set forth by government for current planning period, a general framework of measures for poverty alleviation are given below:

\begin{itemize}
\item Income generation is the major safeguard against poverty, henceforth activities promoting employment and skill development should be promoted
\item The distribution of poor households -- location, size and status should be recorded and database updated regularly
\item Identity card should be distributed among the identified households in order to facilitate easy launching of programmes to the target group.
\item Policy amendments with allowance package for truly poor individuals should be made
\item Programmes and projects aimed at skill enrichment of different sectors of people should be launced based on priority
\item Settlement plans for refugees should ensure their upliftment
\item Street children, disabled and elder citizen should be granted special support
\item Equal opportunity for employment to all classes of citizens
\item Government should aim for improving livelihoods of the poor through their self-reliance
\item Promote activities that increase self-employment. For this, agriculture commercialization and diversification should be done at policy level and supply of fertilizer, improved seeds and chemicals should be assured.
\item Investment environment should be improved for increased investment in agriculture, manufacturing, trade, tourism, health and education.
\item Fostering of inter-agency cooperation between government organizations in the fight against poverty.
\end{itemize}

A state of poverty reflects weak privilage for a nation and its citizens. It also means that the economy is underdeveloped and unhealthy for modern infrastructure attainment. Thus a targeted approach, that identifies and arranges basic facilities for the poor so as to enable them uplift their livelihood through skill generation and income generation enterprise is the current necessity in nationwide fight against poverty.

\end{solution}

\question What is poverty ? What is the difference between absolute and relative poverty ?

\end{questions}

### Human Development Index

### Drug abuse

\begin{questions}

\question What is drug abuse ? What are the effects and consequences of drug abuse ?

\begin{solution}

The substance that affects our mind and organs and damages our body if used in uncontrolled amount is drug. The habit of taking drug regularly is drug abuse or drug addition. Drug abuse and addiction have negative consequences on individuals and society as well. In reality, drug addiction is a complex disease, and quitting it takes more than good intentions or a strong will. Drug abuse is a serious public health problem that affects almost every community and family in some way. Each year drug abuse causes millions of serious illnesses or injuries. Drug abuse also plays a role in many social problems, such as drugged driving, violence, stress, and child abuse. It can lead to homelessness, crime, loss of employment, failure in school, domestic violence, etc.

Generally, drugs are illegal. Some of the drugs used and supplied by the drug users and drug traffickers are herion, smack, cocaine, cannabis, etc. Selling of such substance is illegal subject to criminal offense. Although strict laws are in place for punishing those who are involved in drug trafficking business, several people are involved in it. Below are some of the reasons that make it very difficult to stop drug trafficking:

\begin{enumerate}
\item The traffickers run this business in an organized way.
\item The traffickers use their private means of transportation for supply.
\item They have good link in customs, airport, etc.
\item There is good deal of money in this business.
\item The traffickers have link and wide network with high ranking officials and politicians.
\end{enumerate}

\textbf{Causes of taking drug}

The use and trend of using drugs is increasing rapidly in the world. About 4\% of the world's population use drug of some form. Many adolescents, teenagers and youth easily fall to drug abuse than elders because they are easily motivated by traffickers. The causes of drug taking are:
\begin{enumerate}
\item Due to influence of bad company, they trust their peer groups and under peer pressure, youths start using drugs.
\item Drug traders abuse them for their criminal purpose.
\item Attraction to advertisement and promotional activities that youths are inclined to imitate.
\item Due to lack of peace in family environment.
\item Lack of love and care from family members or related peers (girl/boy friends)
\item Teenagers have high expectations and when they are not fulfilled they feel frustrated and take drugs as resort.
\end{enumerate}

\textbf{Effects of drugs to and individual}
\begin{enumerate}
\item Cannot continue education
\item Failure and setbacks in exams and cannot develop career
\item Loose jobs due to decreased attention to work
\item Possibility of contracting diseases like AIDS, Cancer, etc
\item Suffers from financial crisis
\item Increase in criminal attitude
\end{enumerate}

\textbf{Effects of drugs in a family and society}
\begin{enumerate}
\item Emotional stress in the family
\item Family loses peace and prestige
\item Financial crisis in the family
\item Kids are victimized
\item Squabble and conflict with neighbors
\item Accident, robbery, murder, kidnapping and criminal activities increase in the society
\item Society struggles with economic and infrastructure development
\item Society loses active and creative manpower
\end{enumerate}

\textbf{Solution to the problem of drug abuse}
\begin{enumerate}
\item Strict laws should be made and implemented against drug traffickers.
\item Mass awareness programmes should be conducted to aware general public about the consequences of drug abuse
\item Various social organizations should play an active role in raising awareness against the drug abuse
\item Children and youths should receive proper counselling
\item Children should be raised in a good environment with proper love and care from parents
\item Rehabilitation centres should be provisioned for those seeking institutional support
\item Family and society should develop positive attitude towards those individuals committed to refrain drug use.
\end{enumerate}
\end{solution}

\question Anger is a harmful negative emotion. It is injurious to both personal life and work life. Discuss how it leads to negative emotions and undesirable behaviours. How can it be managed and controlled?

\begin{solution}
Anger can be termed as a extreme behaviour, an intense emotional state involving a strong uncomfortable and hostile response to a perceived provocation, hurt or threat. This is considered a negative emotion because it has potential to hurt someone or cause any physical or mental damage to ourselves or others.

How anger leads to negative emotions and undesirable behaviours

By blocking our emotional intelligence

Anger has the power of blocking the right thinking process that usually allows us to make right judgement. This state will influence us to make certain decision that would not have taken place if we would have calmly handled the situation. This will result in actions that are both undesirable and unworthy.

Ex: Slapping a friend in public for a small action that was accidental or unintentional.
    Creating sense of disappointment

Negative emotions are developed in an individual if a sense of disappointment prevails due to anger. This disappointment will create a strong sense of negative emotions such as disgust and hate, which will force us to display undesirable behaviour.

Ex: when you find out that your colleague is indulging in unethical action, you sense a feeling of anger. This anger will make you develop negative emotions like hate and disgust towards the colleague without hearing the other side of the argument.

How to control and manage anger

Mind calming techniques

The best method to control anger is using techniques to introduce calmness in thinking process. This can be achieved by practicing yoga, meditation and other forms of natural healing. This will provide that required moment of calmness that prevents our anger to overshoot, which otherwise leads to negative emotions and unruly behaviour.

Physical activities

Physical activities such as exercise, jogging etc will help in reducing the frustration that builds up and is responsible for anger. By getting rid of underlying and hidden feeling, we can atleast prevent ourselves from overreacting to a situation through unruly behaviour.

Way forward

Anger in a certain amount is beneficial as it keeps the spirits of an individual high. But exceeding the limit will usually create chances of negative emotions.

Thus, anger management is an important component in the life of an individual. It not only keeps negative emotions from emerging, it also ensures that energy of an individual is used productively and not spent on emotional angry outbursts.

source: \url{https://www.upsciq.com/anger-harmful-negative-emotion-injurious-both-personal-life/}
\end{solution}

\end{questions}

### Social conflict

\begin{questions}

\question What is social conflict? Discuss about the causes and consequences of social conflict in Nepal.

\begin{solution}

A society composed of diverse of individuals and groups. Each individual or group within a society have their unique ethnicity, language, culture and religion and socio-economic background. Similarly, it is hard to find individuals with common pursuit of interests, hobbies, habits and perspective. Therefore, in a ways, diversity itself gives way to conflict. Individuals differing for various interpersonal attributes and socio-cultural background can have a sense of amusement, non-acceptance, dispute/debate and disagreement in simple to moderate manifestation. In extremes of those, feelings of envy and grudge as well as tendency to exploit physical means of harm arises. All these happenings are characteristic of social conflict.

Following factors give rise to social conflict in Nepal

\begin{enumerate}
\item An individual loses trut in other and fails to respect his rights and authorities
\item Unemployment
\item Increase in poverty
\item Economic inequality
\item Indifference to social customs and values
\item Drug abuse and intoxication
\item Lack of social justice
\item Lack of education and awareness
\end{enumerate}

Although there are some \underline{positive} consequences of social conflict, including progression of socio-economic transformation, increase in awareness, improvement of social justice system and occassional enrichment of solidarity, several \underline{negative} consequences of it exit. Some of which are:

\begin{enumerate}
\item Disruption of social peace and order
\item Increase in criminal activities of robbery, murder, kidnapping
\item Encroachment of personal rights and feedom of individuals
\item Social tradition will be replaced by wrong social customs and values
\item Socio-economic development and physical development will be stalled.
\end{enumerate}

Acknowledging that social conflict has a wide reach within multiple socio-economic, religious and political sphere of a community and a nation as a whole, the situation should be resolved creatively rather than forcibly. A peaceful debate and a harmonious mindset with the feeling of tolerance are the pre-requisite for social order setting.
\end{solution}

\end{questions}

### Prime Minister Employment Program

Social security programs are integral to realize the constitution’s goal of achieving inclusive economic development, equity and democracy-based socialism in Nepal. In Nepal, in recent past, new initiatives have been taken to ensure and include a larger population in social security. For instance, politically ambitious Prime Minister’s Employment Program can be viewed among one of them.

PM’s employment program is a new addition that seeks to create internal employment for unemployed workforce. This is a social protection initiation that seeks to explore the ways in which unemployment issues can be addressed locally. Apart from mandatory 100 day employment guarantee, this scheme is designed to impart training for skill development to unemployed youths. It is seen as one such initiative that will contribute to achieving the motto of "prosperous Nepal happy Nepali". The program is mainly focused on the fulfillment of government’s commitment to ensure constitutional rights to employment of the people in Nepal. Hence in its policy document it focuses on,

- Labour and employment policy, regulations, laws and measures
- Social security laws, rules, regulations and policy formations and taking measures
- Keep statistics of unemployed work force

Anybody between the age ranges from 18-59 years is eligible to find a job within PMES. Those who will receive training (upon submission of application) under employment support program will have to work. In addition, unemployment benefit will be provided to the unemployed under the section 6 (22) of the act of Employment Rights related, 2075.

The program is governed by the various legal documents approved by the Cabinet of Ministers including:

- Employment Rights related Act 2075 (amended and approved by the Council of Ministers on Magh, 25 2075 (February, 8 2019)
- Employment rights related regulations 2075
- Prime Minister Employment program regulation guidelines 2075

It is envisioned that at the local level basically at Gaunpalika level there will be a forum created called Employment Discussion Forum – that will initiate dialogue at the local level to create employment as well as to identify those who need support from PM employment program.

At present, PEP has introduced a program called – _Shram Ko Samman Rastra Ko Abhiyan_. Within this initiative a total of 12 projects are implemented. At this initial stage employment information center is working partially and it is evident that this office lack appropriate workforce and are facing other operational issues. Until 2019 a total of 67% of allocated budget has been spent on creating Employment Management system.

The PEP, and other social security programs alike, have seen gradual expansion over the years and have seen good share in total government expenditure, which obviously is not a wrong direction in effort to establishing a better protection scheme for larger segment of the population. However, inadequate human resources, planning and coordination have constrained its effectiveness. In addition, PME initiative has also been criticized as as a pocket fund for the political cadres already elected local representative locally. In long run, the sustainability of social security programs are tied, for example, the old age pensions, depends on the Social Security Fund’s ability to make productive investments and its ability to adjust to changing demographic parameters. The situation, thus, underlines a need for more active regulation and control of tipping points in implementation of PME. 

The PME program is certainly ambitious in its scope. Its stated objective to ensuring social protection for the most vulnerable people living in rural Nepal through providing employment opportunities; ensuring livelihood security for the poor through creation of durable assets is yet to be seen. Moreover, given the crisis ridden economic scenario of Nepal, the sustainability of such initiatives remains a matter of concern. 

### Social protection

Different social security allowances currently offered by the government of Nepal:

Elderly citizens
- Aged 70 and older (60 for Dalits and those from the Karnali region)
- 3,000

Single/Widow women
- This includes all the women who are single (unmarried or divorced) or widow and aged 60 or older
- 2,000

Fully Disabled
- Fully disabled persons who have obtained a red disability identity card from the government
- 3,000

Severely Disabled
- Severely disabled persons who have obtained a blue disability identity card from the government
- 1600

Endangered ethnicities
- Citizens of the following communities: Kusunda, Bankariya, Raute, Surel, Hayu, Raji, Kisan, Lepcha, Meche, Kusbadiya
- 3,000

Children
- At most two children per mother from the Dalit communities and from Karnali region the Province 2 as well as from districts Achham and Bajhang
- 400

## Environment management and natural resource protection

### Relationship between climate change and energy use

- Energy use has close ties with climate change. India and china are among the greatest emitters of greenhouse gases and consumers of fossil fuel, and it is predicted that their consumption of coal as major source of energy will continue to rise for at least a decade (IEA, 2019).
- Into 2016 and we still have 80% of our total energy requirement met from fossil fuels (mostly, oil, coal and natural gases). International energy agency's report says that 30% of all energy-related carbon dioxide emission is related to coal as fuel, making it the biggest single contributor (2019).
- An individual effort to parsimoniously treat energy resources available to us determines individual footprint. We could choose to reuse a battery/cell, with minor power drops, in alternative electronic items compatible with it or just treat at a refuse at our home. The latter activity with unforeseen consequences might lead to the battery being disposed improperly and polluting an ecosystem due the leakage of its electrolyte chemicals.
- While electricity is lighting up most houses, its generation has been a markedly different process worldwide. The process basically depends with the resource endowment of a nation in their approach to choosing ways to explore it. Coal, for example, is used largely in China and the US despite its much tauted big contribution in greenhouse emission.

### Impacts of climate change

What are the impacts of climate change ? Discuss on detail about the initiative taken by Nepal Government in tackling the impacts of climate change.

Climate change is now affecting every country in every continent. It is disrupting national economies and affecting lives, of individuals, communities and countries today and is likely to do so in the ensuing future. Weather pattern are changing, snowline are melting due to global warming and sea level are rising. 

**Negative impacts**

1. Numerous mountains are seeing accelerated the melting of snow due to global warming.
2. Changes in monsoon patterns, such as erratic rainfall with alternate drought periods are the serious impacts of climate change in Nepal which hampers the agricultural production. The changes in monsoon pattern in Nepal greatly exacerbate the situation of poverty and food insecurity in the country.
3. Flood, landslides, forest fires, snow melt are the disasters that occur as a result of climate change without any prewarning and causes heavy loss.
4. High hills and mountains are more vulnerable to climate change compared to terai, thus climate change make large scale economic and ecolgical disruption in upper latitudes.
5. Loss of plant and animal biodiversity.
6. Increase in number of insects, pest and diseases and sporadic outbreaks becoming much frequent.

The positive impact of global warming, a characteristic feature of climate change, is that the crops that could in the past be only growth in certain low altitudes, requiring prolonged exposure to heat can now be growth in higher regions such as Manang and Mustang districts of Nepal. The is evidently due to increase average temperature of the region, thus allowing the crop to perform well. However, as noted earlier, there are more prominent negative impacts than the benifits we can derive from the climate change.

Nepal became signatory of UN Framework Convention on Climate Change (UNFCC) in 1994. Ever since then the issue of climate change has been routinely incorporated into policy and strategic frameworks by Government of Nepal. Following policies and strategies are currently in place to help mitigate the impacts of climate change in Nepal:

1. Constitutional approach

Article 30(1) of the constitution of Nepal guarantees a "clean environment" as fundamental right and elaborates that "every citizen shall have the right to live in a clean and healthy environment." Article 30(2) of the constitution also encourages the state to formulate necessary legal framework to balance environment and development.

2. Approaches in periodic plans
3. Climate change policy, 2067 (2011)
4. National climate change policy, 2076 (2019)
6. National adaptation plan of action (NAPA, 2010)
7. Framework for local adaptation plan for action (LAPA, 2011)

(for detailed discussion of National Climate Change Policy, refer to the section on National Plans, Policies and Strategies.)

\begin{questions}

\question Although Nepal is an agricultural country, what are the reasons for decreasing productivity of arable land in recent years.

\begin{solution}

Some of the reasons for decreasing productivity of arable land in recent years in Nepal are:

\begin{itemize}
\item Recent years have seen depletion of soil fertility. Besides leach and runoff of major nutrients, intensification of mono-cropping, mainly that of cereals, has accelerated exhaustion of these essential supplies. Likewise, farmers have not been, since early farming days, supplementing the land with micronutrient fertilizers. It should be noted that micronutrient deficiencies can have serious limitting effects in yield.
\item Haphazard use of chemical fertilizers have resulted in acidity and salinity build-up in soil. The crops exhibit symptoms of toxicity when growth therein. Trace to almost null measures of soil amendment adds to this problematic scenario.
\item Excessive reliance on seasonal rain has turned to become counterproductive. Monsoon streams and water bodies have not been able to fend for agricultural water needs. In some instances they have even dried down in recent years, mainly due to changing seasonal patterns and climate extremes.
\item In recent years, size of land holding have decreased. This means that in average a farmer own less area of land than what he used to crop previously, currently 0.5 ha per household. This is in comparison to more advanced nations, less by ten to hundreds of order magnitude. This has a rippling effect. Today farmers are practicing farming only as a side gig as well as being less willing to invest in technology introduction. This translates into lesser input consumption and ultimately to lower yield. At the same time transition from traditional practices of diverse cropping to mono-cropping leads to a greater loss in diversity and deprivation from essential ecosystem services of natural environment. For example, natural enemies of insects are indiscriminately being eradicated while trying to turn the wheels against insect-pests. 
\item While most development plans give high priority to agriculture - which contributes 30 percent to GDP - government investment in the Ministry of Agricultural Development (MOAD) - has declined from 3.7 percent of all government spending 10 years ago to around 3.0 during recent years. Meanwhile, overall government spending has doubled since 2006.

\end{itemize}
\end{solution}

\question What is climate change ? What are the negative impacts or such impacts possible due climate change in Nepal ? Mention.

\begin{solution}

Climate is usually defined as the "average weather" in a place. It includes patterns of temperature, precipitation (rainfall or snow), humidity, wind and seasons. Climate patterns play fundamental role in shaping natural ecosystems, and the human economies and culture that depend on them.

The planet's climate has been constantly changing over geological time. The global temperature today is about 15 $^\circ C$, though geological evidence suggests it has been much higher and lower in the past. However, in light of the global temperature records, scientists today are concerned that the natural fluctuation, or variability, is being overtaken by a rapid human-induced warming that has serious implications for the stability of the planet's climate. For example, notable events including drought and heat waves in Russia in 2010, drought in China in 2012, and droughts in the US in 2011 and 2012, have all had a major impact on agricultural production in these areas.

Climate change is a change in the state of the climate that can be identified (e.g., by using statistical tests) by changes in the mean or the variability of climate properties and that persists for an extended period, typically decades or longer. Climate change may be due to natural internal processes or external forces or due to persistent anthropogenic changes in the composition of the atmosphere or in land use by factors such as biotic processes, variations in solar radiation received by Earth, plate tectonics, and volcanic eruptions. Certain human activities have been identified as primary causes of ongoing climate changes, often referred to as global warming.

Observations of temperature have shown that 10 of the warmest 11 years have occurred since 2001. Coupled with these changes is the decrease in the number of frost days by 10\% in the eastern half of the US and an increase in the length of the growing season by over 10 days.

Trends in precipitation are more difficult to assess; however, overall precipitation amounts and heavy precipitation events have increased in most regions of the world; while occurances of drought has been increasing, particularly since 1970 (IPCC, 2007). 

Recent analysis of trends from 1971 to 2014 by the Department of Hydrology and Meteorology (DHM) shows that the average annual maximum temperature has been increasing by \SI{0.056}{\degree\celsius} per year (DHM, 2017). Another study found that a small, but statistically significant, increase in the frequency of hot nights has been observed. In contrast, the annual frequency of "cold" days and nights has decreased significantly since 1960 (McSweeney, New, \& Lizcano, 2012). The mountain regions are warming more than the plains (ICIMOD, 2018). The mean annual temperature is expected to continue to increase in Nepal over the remainder of the century. Recent projections indicate that mean annual temperatures could increase \SIrange{1.3}{1.8}{\degree\celsius} by the 2050s, with the highest increases in the mountain regions. Along with this, increase in warm days and nights is predicted.

\textbf{Impacts of climate change for human society}

\begin{itemize}
\item Melting glaciers, early snowmelt, and severe droughts will cause dramatic water shortages and increase the risk of wildfires in the American West.
\item Rising seas levels will lead to coastal flooding on the Eastern Seaboard, especially in Florida, and in other areas such as the Gulf of Mexico. 
\item Forests, farms and cities will face troublesome new pests, heat waves, heavy downpours, and increased flooding. All those factors will damage or destroy ecosystems which human excessively rely on -- Agriculture and fisheries.
\item Disruption of habitats such as coral reefs and alpine meadows could drive many plant and animal species to extinction.
\item Allergies, asthma, and infectious disease outbreaks will become more common due to increased growth of pollen-producing ragweed, higher levels of air pollution, and the spread of conditions favorable to pathogens and mosquitoes.
\end{itemize}

Examples of observed climatic changes

\begin{itemize}
\item During the past 50 years there has been an increase in $CO_2$ concentration from 325 to 390 ppm with a projection of further increases to nearly 500 ppm by the middle of the twenty-first century (IPCC, 2007).
\item During the twentieth century, global average air temperatures increased by approximately \SI{0.74}{\celsius} (\SIrange{0.56}{0.92}{\celsius}) (IPCC, 2007a) with projections of further increases in surface air temperatures of between 1.1 and 2.9 $^\circ C$ by 2100 under emission scenarios, which have adopted aggressive methods to reduce $CO_2$ emissions, and by up to 2.0-5.4 $^\circ C$ under scenarios with higher emission rates. 
\item Winter temperatures have increased more rapidly than summer temperatures, and night time minimum temperatures have warmed more than daytime maximums. Across the US (and elsewhere), record high temperatures are three times higher than the number of record cold events.
\item Decrease in snow cover and sea ice extent and the retreat of mountain glaciers in the latter half of the 20th century.
\item Rise in global average sea level and the increase in ocean water temperatures. Between 1900 and 2016, the sea level rose by 16-21 cm (6.3-8.3 in). The accelerated decrease in coastal areas is attributed mostly to human induced global warming.
\item Likely increase in average precipitation over the middle and high latitues of the northern hemisphere, and over tropical land areas.
\item Increase in frequency and intensity of extreme precipitation events in some regions of the world.
\end{itemize}

Examples of observed physical and ecological changes

\begin{itemize}
\item Thawing permafrost
\item Lengthening of the growing season in middle and high latitudes
\item Pole-ward and upward shift of plant and animal ranges
\item Decline of some plant and animal species
\item Earlier flowering of trees
\item Earlier and frequent emergence of insects-pests
\item Disruption of seasonal pattern of migratory birds and egg laying animals.
\end{itemize}

Source: Encyclopedia of Agriculture and Food Systems

\end{solution}

\question What is green house effect ? Mention its implications of green house gases in global warming.

\begin{solution}

The earth's climate is warming as a consequence of the accumulation of greenhouse gases in the atmosphere. Warming of the atmosphere is actually happerning because the atmosphere is continuing to trap the heat that radiates from the earth and traps it between the earth and space.

The most important greenhouse gases contributing to this warming are carbon Water vapor, dioxide ($CO_2$), methane ($CH_4$), and nitrous oxide ($N2O$). Although these gases are present in the atmosphere naturally, human activity has been responsible for a rapid increase in their concentration over the past century. Greenhouse gases are released by a variety of processes, the most important of which is fossil fuel consumption, which currently adds more than 9 billion tons of $CO_2-C$ to the atmosphere each year.

Chlorofluorocarbons (CFCs), which are basically synthetic compounds that are created in the industrial setting, also play a part in green house conditioning. They are usually what plays a part in depletion of the ozone layer. The more the ozone layer is depleted, the hotter our earth will get.

Globally, IPCC (2007d) estimates that 69\% of the GHGs originate from energy consumption, whereas 14\% arise from food production and 17\% from deforestation. Meanwhile, energy use, food use, and land use change, and thus emissions generally expand with incomes and population. In fact, historical emission data show that global GHG emissions and concentrations have been increasing at an increasing rate.

Agriculture too is a major source of the greenhouse emissions. Practices such as deforestation, cattle feedlots, and fertilizer used currently account for approximately 25\% of greenhouse gas emissions. When broken down in total, this amounts to 14\% of carbon dioxide emissions, 48\% of methane, and 52\% of nitrous oxide emissions.

\end{solution}

\question What is water-use efficiency? Describe the role of micro-irrigation in increasing the water-use efficiency.

\begin{solution}

Water use efficiency is the ratio of water used for plant metabolism to the water lost by plant through transpiration. It can be understood as a measure to reduce water wastage from plants by providing only the necessary amount.

Role of micro-irrigation in increasing water-use efficiency

Reduces excess water accumulation
    
In conventional irrigation system water is used in bulk without proper understanding of the requirement of the crop. This will result in accumulation of water without proper utilisation leading to wastage. In micro-irrigation, the water needed for the plant to grow is given in right amount so as to reduce wastage.

Recycling of expelled water

In micro-irrigation system such as greenhouse farming, the plant canopy is covered in plastic to prevent transpiration water from escaping. The water is then diverting back to the plant. This will ensure that water wastage from plant will be lower in comparison to the input.

Reduces run-off

Water irrigation in conventional methods like canals and tube well will result in water runoff from the fields without getting utilised. This will contribute towards wastage especially in areas where there is shortage of water. In micro-irrigation techniques, water will be targeted at the root of the crops so that wastage is as low as possible.

Way forward
It is necessary to device methods to make water use efficiency high and address shortage of water across the globe.

Thus, micro-irrigation is a very important idea when it comes to sustainable use of water resources. The initial investment once recovered will make agriculture a profitable venture.

source: \url{https://www.upsciq.com/what-is-water-use-efficiency/}
\end{solution}

\question The global lockdown imposed due to COVID-19 pandemic has turned out to be beneficial for environment on short term. Validate.

\begin{solution}
The major countries of the world, including India have self imposed a lockdown to tackle spread of COVID-19 pandemic. This has impacted economy of the world in an adverse manner causing slowdown. But the silver lining in the situation is improvement in environmental conditions that we have observed.

Environmental benefits due to global lockdown

Reduction in air pollution levels

The major environmental concern in this century is climate change, that has been caused due to air pollution across major human settlements. Due to the lockdown the pollutant level in air such as CO2, NO3, SO4, ozone, PM 10, PM 2.5 have seen a drastic drop. This has made the air cleaner for breathing and reducing health concerns.

Reduction in water pollution levels

Water pollution in developing countries is mainly due to factories dumping their waste in water bodies. The lockdown has forced the factories to shutdown and cut production. This has reduced or completely cut off waste discharge from factories.

Reduction in solid municipal waste

With low outdoor activities and travel, the household waste produced in cities have seen reduction. The reduced level makes it easier to dispose off the waste more effectively. Dumping grounds have a chance to recover if this trend continues.

Increase in biodiversity

Withdrawal of humans from outdoors have opened the spaces for biodiversity to recover their lost territories. Sea mammals like dolphins have returned back to the shores due to lack of disruption from humans in their territories.

Reduction in sound and light pollution

Cities have turned silent due to stoppage of vehicular movement and industrial activities. This has made the environment suitable for calmness. Excessive usage of light has been reduced too due to the same reasons.

Way forward

This restriction has to be converted into a habit for people to follow in future so that environmental pollution is kept in check.

So, the global lockdown has helped the environment to recover upto certain extent. What needs to be seen is the impact that return of normality is expected to bring.

source: \url{https://www.upsciq.com/the-global-lockdown-imposed/}
\end{solution}

\end{questions}

### Deforestation and natural calamities

\begin{questions}

\question How can we control the deforestation that might be caused by socio-economic factors ? Explain

\begin{solution}

Deforestation is the clearence of forest or woodland for extracting natural forest product such as timber, firewood, medicinal herbs, or any other form of human or human induced activities that result in loss of forest species. Such activities may include encroaching forest space and overgrazing, etc.

Most of the population of Nepal dwell in rural areas with minimum access to urban infrastructure -- easy transportation, well developed alternative sources of fuel, means of communication and specialized occupation. This means people are excessively reliant on natural unprocessed products derived mainly from forest, for making their living. The 2011 AD forest survey indicated that Nepal has more than 40% of its land area covered with forest, thus highlighting significant interaction of forest ecosystem with people, communities, biodiversity and economy. The relationship is more profound when the context is rural, which most of the Nepal is composed (82.93% according to 2068 BS census).

Still today, people use firewood as major source of fuel for cooking food to handling chores. In a lack of permanent residence building, several families still make thatched homes out of forest timber and tree cuttings. The latter is also fed to cattle as an important part of roughage diet since villages do not have reach to concentrate feed for the animals. Depleting an important reservior of human livelihood maker and animal provider in rural topography of Nepal will only make residents of these areas more vulnerable to economic shocks. When a household is engaged in forest timber accrual and supply as a source of earning, this dependence will lead to economic setbacks and overall lower quality of life during periods of lean supply from forest. Interestingly, the relationship applies conversely also, because regions like inner terai districts of Nepal, with inherently rich forest resources, are found to be progressing very quickly.

An accelerating rate of forest clearence can be controlled by one or more of the following measures:

1. Protection, utilization and benefit sharing scheme should be developed for community managed forest. Community participation in planning and execution of such schemes will make them have the feeling of ownership.
2. Alternative sources of energy should be promoted for fuel.
3. Marginal lands and shrublands should be disallowed for intensive agriculture and livestock grazing.
4. Acknowledging that every 1 hectare of arable land should be accompanied by 3 hectares of forestland, programmes for forest reclaimation and plantation should be intensified.

\end{solution}

\question What are the major reasons for deforestation in Nepal ? What are the consequences of it ?

\begin{solution}

Deforestation is occuring in Nepal due to human and natural causes. Forest encroachment, illegal forest clearance, clearance due to waterway entry (river passage), land slide, forest fires, uncontrolled grazing, unchecked extraction of forest floor resources such as stones, pebbles, sand and minerals, lack of public awareness, etc are the major reasons for deforestation in Nepal. Several factors contributing to deforestation can be summarized as below:
\begin{itemize}
\item Excessive utilization of forest resources in physical infrastructure development.
\item Forest protection, conservation and promotion activities are not having impact.
\item Afforestation programmes and forest conservation endevours are not well organized and effective.
\item Very feeble participation of stakeholders in overall development of forest sector.
\end{itemize}

Deforestation in Nepal has wide consequences, some of them are:

\begin{itemize}
\item Most important factor causing large-scale floods is deforestation in Tarai and Siwalik regions. Large-scale deforestation of northern Tarai and Chure range has aggravated flood problems in Tarai. Forest and vegetation obstruct the flow of water and reduces flow speed. Water is absorbed underground, resulting in less runoff and fewer floods. Also, forestland upstream provides a natural buffer for Tarai thus providing more response time. Deforestation has thus left the Tarai people with less reaction time, frequent and intense flooding, filling of agricultural lands with sand, diminishing ground water and high concentration of soluble minerals such as arsenic in tube well water.
\end{itemize}

\end{solution}

\begin{questions}

\question Explain about soil erosion, status and its consequences for Nepal. 

\begin{solution}
According to a United Nations-backed study, a third of the planet's land is severely degraded and fertile soil is being lost at the rate of 24 billion tonnes a year. In Nepal, the situation is even worse because two-thirds of the country's total area is geologically fragile where soil erosion is exceedingly high. Topsoil loss has been reported as high as 87 tonnes per hectare per year on sloping terraces. When the top soil is lost, the land is degraded.

Poor land management in Nepal has caused soil erosion each year with impacts not just on food production but also on biodiversity loss, carbon loss and disaster resilience. Forecasts on land in South Asia indicate that countries like Nepal will have to face the greatest challenges if better land regulation and improved farming technologies are not put in place.

When farmland is ploughed and tilled, the exposed topsoil is often blown away by wind or washed away by rain. Erosion due to faulty practices in crop production, for example, has resulted in the loss of millions of tonnes of topsoil every year. This leads to reduced soil fertility and degraded land.

Unscientific farming in the hills (steep slope) is one of the causes of soil erosion in Nepal. Shifting cultivation and unnecessary tillage practices also lead to land degradation and damage the ground vegetation and natural ecosystems. Cultivation on the steep slope without taking improved farming practices such as terracing, selection of appropriate crops and use of organic manures into consideration have contributed to increased soil erosion. Furthermore, agricultural intensification produces certain by-products and side effects that are unfriendly to the environment. Ways must, therefore, be found to minimise the effects of these by-products and side effects on the quality of soil.

Maintenance and enhancement of soil fertility are vital for food security and environmental sustainability. Ecologically sound agroforestry systems such as inter-cropping and growing tree crops in the sloppy lands can be helpful for the sustainability of farming. Many farming practices have been developed to improve efficiency in the use of resources and strengthen research on sustainable agriculture in developed countries and have made us hopeful about scientific and technological innovation in the management of soil.

The practice of tilling sloped land along lines of consistent elevation in order to conserve rainwater and to reduce soil losses from surface erosion is called contour farming. It acts as reservoirs to catch and retain rainwater, thus permitting increased infiltration and more uniform distribution of water. The contour farming is a traditional practice in the hilly areas of Nepal.

Another good practice to control soil erosion is the creation of windbreakers by planting evergreen trees around farmland in windy areas like Mustang. It helps prevent the wind blowing away the soil from the farmland. Windbreakers also help in protecting crops from damage caused by strong and severe wind and improve plant health, quality and yield. Crops protected from wind are able to retain significantly more moisture. Matting is the process of covering the soil with biodegradable materials that include mulch, straw, coconut fibre and wood chips. These are held together with biodegradable netting made from coco coir.

Crop rotation with non-hosts of the pathogens that require control is considered one of the most important cultural factors for reducing overall disease problems of crops as well as minimising soil erosion. Beneficial organisms can be added directly, or the soil environment can be made more favourable for them through use of compost and other organic amendments. Soil pH, calcium level, nitrogen form and the availability of nutrients can all play major roles in soil disease management. Adequate crop nutrition makes crops more tolerant of or resistant to disease.

Trees are often considered to be the universal answer to control soil erosion. Tree roots help prevent landslides on steep slopes and streambank erosion. Horticultural crops, particularly fruit trees, have positive implications for the future development of mountain agriculture in terms of minimising soil erosion, harnessing mountain niches and comparative advantages.

Agro-forestry is a sustainable land use system and practice in which woody perennials (trees, shrubs) are grown with herbaceous annuals (crops, pasture grass). It supports the livelihood of billions of people worldwide and provides a wide range of products such as food, fuel, fibre, fodder and forage for livestock. Even the landless farmers sustain their livelihood with this system.

According to a case study of agro-forestry from the mid-hills of Nepal, it is possible to earn Rs 45,490 per hectare from carbon sequestration per household if a payment scheme is introduced. It prevents the further degradation of the undulated fragile land of hilly areas.

Soils and agro-ecosystems are essential for sustainable production, hence farmers, social workers, politicians and agriculturists should come together to develop soil management strategies for sustainable production. Farmers should try to keep their farmland productive for generations to come.
\end{solution}

\question What do you mean by environment management ? Describe the interrelationship between environment management and sustainable development.

\begin{solution}

Environment management is concerned with the description and monitoring of environmental changes, with predicting future changes and with attempts to maximise human benefit and to minimise environmental degradation due to human activities. Environmental managers are a diverse group of people including academics, policy-makers, non-governmental organisation (NGO) workers, company employees, civil servants and a wide range of individuals or groups who make decisions about the use of natural resources (such as fishers, farmers and pastoralists). Yet, characteristically, environmental management is about decision-making -- and it is especially concerned with the process of decision-making in relation to the use of natural resources, the pollution of habitats and the modification of ecosystems. Fundamentally, then, environmental management is a political activity because those decisions - about resources, pollution and ecosystems - are never neutral or objective.

Rural parts of Nepal (home to 81.75\% population) are traumatized by the poor geographical terrain wherein majority of household are reliant on forest (constitute 44.74\% of total area), biodiversity and natural watershed resources -- to the extent that these resources are already seeing a peril. The environment here is subject to the stresses and strains of deforestation, lossof top soil, misuse of pesticides or insecticides, soil contamination, a decrease in productivity, watershed disruption, a shortage of resources, landslides, flooding and indoor pollution. The general environmental problems in urban cities and municipalities are air and water pollution, unmanaged solid waste, the lack of land-use planning, inefficient urban infrastructure, a conglomeration of manufacturing establishments, resource shortages, over-crowding and loss of vegetation.

Currently there are 5,646 industries in operation in Nepal (Registered at DoI 2013/14), composed of agriculture and forestry, energy, manufacturing, service, construction, mining and tourism sectors. Capital wise, there are 686 large, 1330 medium and 3630 small industries.

Thus, in this context with need of rapid economic development through extensive resource mobilization, amidst the pushbacks from changing global climate, environment management and its conceptual ties with sustainability at the core, holds much greater importance. The human and infrastructure losses due to the earthquake of April 25, 2015 have become a great threat and challenge for environmental management in the present scenario of our country. Some interventions are already in place. Those constitute:

\begin{itemize}
\item Constitution of Nepal, 2015; Article 30: Right to Clean Environment
\item SDG Goal, 2030
\item Environment Protection Act, 1997: The main thrusts of the Act and the Regulation are pollution control and environment assessment (EA). Regarding environmental pollution prevention and control, a pollution control permit system is conceived in the regulation. Detailed procedural approaches including environmental standards are identified by MOEP and executed through concerned line agencies. EA, the other environmental tool, is categorized into two parts: initial environmental examination (IEE) and environmental impact assessment (EIA). Development projects under the scope of IEE will be cleared by the concerned line agency, whereas MOEP will concentrate on the EIA category projects. Here again, monitoring of the EA-granted projects by MOEP has to be carried out by the concerned line agencies. Similarly, a provision of a revolving fund for pollution control, environment and heritage conservation, awareness creation, research and award business exists in the regulation. In addition to these, a compensation claim of damage due to environmental pollution caused by any sources could create controversies because of its vagueness and complaint handling procedures.
\item Nepal has adopted the notion of green development to minimise stress on environment and to mitigate the impacts on climate change. National policy has stressed environment and climate change. It has mainly focussed on strengthening and updating environmental policy, existing laws, rules and mechanisms. It also focuses on enhancing institutional capacities.
\item ISO 9001 Quality Management System: more than 600 companies registered
\item ISO 14001 Environmental Management System: more than 30 companies registered
\item ISO 14006
\item Status and Assessment of EMS Implemented Industries of Kathmandu Valley, MoI, 2009 
\item Environment Sector Programme Support (ESPS) 2000
\end{itemize}

\end{solution}

\question What is the role of public, private and community institutions in environment management ?

\begin{solution}
The act of describing, monitoring, predicting changes and maximizing human benefits from natural resources by maintaining a balance in their use and conservation without negatively affecting their quality and availability for future generations is called environment management. The role of public, private and community institutions in environment mangement is highlighted below:

\textbf{Public sector}

\begin{enumerate}
\item Forest, watershed, ponds and water reservoir conservation
\item Reducing negative impacts of climate change and introduction of green development concept
\item Mandatory provisioning of environmental impact assessment in development and construction projects
\item Air pollution, water pollution, sound pollution, soil pollution, food pollution and industrial pollution control and setting threshold in place for keeping them on check
\end{enumerate}

\textbf{Private sector}

\begin{enumerate}
\item Respecting and implementing plans, policies and laws-bylaws set forth by government
\item Proper management of industrial and manufacturing wastes
\item Public construction projects should be environment friendly
\item Bearing of social responsibility
\end{enumerate}

\textbf{Community sector}
\begin{enumerate}
\item Emphasis on organic farming and synthetic chemical-free fertilizer management in farming
\item Increase awareness on sanitization and proper waste disposal in society
\item Increase role in deforestation control
\item Lauch campaign on waste management and develop community level infrastructure such as public toilet and waste treatment unit for the activity
\end{enumerate}

\end{solution}

\end{questions}

\question Write short notes on:

\begin{enumerate}[label=(\roman*)]
\item Ethnic groups of Nepal
\item Biodiversity
\end{enumerate}

\question What are the measures that should be taken to conserve forest resources in Nepal ?

\question Write in brief about the importance of water resources of Nepal.

\question What are the major causes of deforestation in Nepal. Discuss.

\question What is the status of environmental pollution in Nepal ? Discuss about the efforts made by Government of Nepal in reducing effects of environmental pollution and preparing for climate change ?

\question What is meant by standard time ? Mention how is standard time of Nepal determined ?

\question Justify: Unplanned urbanization negatively impacts development of nation.

\end{questions}
