# Civil service and public service delivery

## Civil service

The civil service is an institutional mechanism to support the government in executing its tasks and realising the goals of the nation state that have been defined under the Directive Principles and Policies of the State in the Constitution of Nepal, 2072. Creation of a public welfare state is the main political objective, and a public service is to be set up and operated for fulfilling this objective. It specifies that the state shall be oriented towards promoting public welfare by maintaining peace and order in society, making arrangements for the just distribution of economic resources available in the country, and running the development activities for overall socio-economic development in collaboration with the governmental, cooperative and private sectors. The government's major role is to deliver the services to the people according to their demands and needs in a speedy, efficient and effective manner. 

But despite many repeated efforts the civil service still has many weaknesses, including:
- The low level of motivation of civil servants;
- The administrative machinery becoming too much bloated due to the government assuming the whole range of functions affecting people's lives;
- Unnecessary expansion in the number of government agencies and its employees;
- Too many layers in the decision-making process;
- Weak mechanism to make individual officials responsible;
- Adopting new technology effectively remains a challenge;
- Lack of responsiveness towards citizens; and a lack of decentralization of necessary authority to the officials down to the field offices.

Significant structural, managerial and behavioural challenges remain to be addressed, but some positive lessons have already been learned, including:

- Decentralization brings governance closer to the people and helps service delivery and also empowers the people;
- Strengthening local governance has brought many positive changes;
- Local hiring helps to retain the personnel locally and improve a sense of ownership;
- Many local level agencies feel more empowered; and
- Limiting rights to transfer has helped to retain people at decentralised sites

Following features define a civil service:

1. Recruitment based on merit system
2. Legal basis of service offering
3. Permanency and continuity
4. Non-military
5. Careerism and development
6. Pre-defined benefits and facilities
7. Professionalism
8. Job protection and honor
9. Political neutrality and impartiality
10. Mission based
11. Based on hierarchy
12. Dedication to public service

Government's success and people's prosperity relies significantly on effectiveness, efficiency and accountability of the public service sector.

Following points constitute duties of public service sector:

1. Support people elected government
2. Implement programs and policies approved by government
3. Perform as a representative of government
4. Provide assurance of service on behalf of government: Service prioritization; categorization, distribution; Proper and judicious service distribution; Timely service; Monitoring and evaluation.

**Activities under civil services**

In order to establish of peace, harmony and the rule of law in the country, tax collection from the public is ages old tradition that has been as primary mandate of the public service. With progress of time, several other activities have been assigned status of public services. In recent years, with changes in attitude of government towards governance system, reforms have also propagated to public service sphere. Some of the activities currently performed by the service are:

1. Assist government in legislation of people oriented policies.
2. Establish peace and harmony in the country
3. Conduct developmental activities
4. Make use of and utilize properly resources and inputs available in limited amounts in the country.
5. Provide fundamental services necessary to the public in coherent way
6. Promote activities that improve national dignity at international level
7. Perform activities that ensure social justice and social security
8. Launch activities for upliftment of socially backwarded and marginalized groups
9. Collaborate and work jointly with private and non-government sector.

Principles of civil services

1. Principle of equality: Non discrimination, public welfare is all that matters.
2. Principle of neutrality: Politically neutral, only dedicated to clients' welfare.
3. Principle of legal recognition: Implemented as provisioned in law, provisions of punishment upon violation.
4. Principle of continuity: Acts as a form of permanent goverment.
5. Principle of accountability: Towards government, public, programme, goals, colleague.
6. Principle of transparency

Characteristics of Sound Civil Service

- Adjusted to the level of social and economic development in the country;
- Efficient and effective in the delivery of services;
- Highly professional and capable of offering the best technical advice to the democratically elected government;
- Operated according to merit-based principles, combined with culturally sensitive management practices;
- Loyal in the execution of the policies of the acting government, while operating in accordance with the Constitution and the laws;
- Strongly committed to the public interest;
- Disciplined and intolerant of unproductive or unethical behavior;
- Honest and devoted to serving the population in an unbiased and impartial manner;
- Broadly representative of society;
- Upholding fair administrative practices, transparent in its operations and accountable to the citizens and their representatives;
- Willing to hire the best people available at each level, based on a fair and transparent recruitment process and to maintain competitive pay practices that will foster a motivational climate for state employees;
- Strongly in support of proper training and development at all levels;
- Capable and willing to develop partnerships with various groups and organizations in civil society.

### Managing the Civil Service

Central Personnel Agency: The MoGA is the central civil service personnel management agency and is responsible for formulating, implementing and reviewing plans, policies and programs for recruitment, placement, promotion, disciplinary action and retirement of civil servants. It also functions as the Salary and Allowance Review Committee and the Scholarship Committee. It is the central keeper of civil service personnel records through its line department, Nijamati Kitabkhana (DCPR). All ministries, departments, commissions, and central level offices need MoGA approval before taking any action related to civil service management. The ministry is mandated to conduct management audits of government agencies to ensure compliance with the Civil Service Act 1992. The reports are submitted to the OPMCM, which can decide to implement the recommendations. However, in practice, there have been just a few audits, and the MoGA did not have a dedicated management audit section when this study was done in 2010. Further, there have been hardly any decisions on the reports that MoGA has submitted to OPMCM.

Job descriptions: The Civil Service Act 1992 mandates job descriptions stating the specific functions, duties, responsibilities, and authority of each civil service position. Newly appointed employees must receive job descriptions with criteria for performance evaluation along with the letter assigning them to their positions. However, this requirement is rarely observed. Job descriptions that do exist do not have specific and quantifiable performance criteria. These remain a low priority, because the civil service has not traditionally had a performance-based management culture.31Promotions: Civil servants are promoted on the basis of competency evaluations, internal competitive examinations, work performance and experience. Competency is measured through performance evaluations, seniority, educational attainment, service in different geographical regions and training. Separate promotion committees recommend advancement for professional and support level civil servants respectively. There is also a provision for promotion to professional class for employees who have held the same position for at least 15 years. However, despite clear and specific criteria, the promotion system has a number of shortcomings, and in practice, performance evaluations are primarily based on personal judgments rather than objective indicators. Code of conduct: There is a code of ethics that civil servants are required to uphold. The law contains procedures and sanctions to deal with cases of misconduct, including indiscipline and breach of instructions. It restricts employees from being involved in politics, criticizing the government and its policies, receiving gifts, presents, donations and loans, and agitating or participating in strikes. Further, all civil servants are required to accord decent treatment to service recipients and work in an impartial, fair and efficient manner.

Job security: The civil service law is very protective of the rights of government employees. No civil servant can be removed or dismissed from service without a reasonable opportunity for self-defense. No case may be filed without government approval against any civil servant for any act committed while discharging his or her official duty. Where there has been approval, the government defends that civil servant even after the termination of service. The conditions of service are also fully secured: the salary, pension and other benefits allocated to any civil servant at the time of appointment cannot be altered without his or her consent. Any order for departmental action requires prior consultation with the PSC, and there is an Administrative Court to hear appeals against departmental actions.Civil servants retire at 58 years of age, or after three years of service in the case of Chief Secretary and five years in the case of Secretary. Trade unions: Civil servants up to the class three professional level have trade union rights, and authorized unions have the right of collective bargaining. In principle, trade unions are expected to provide constructive suggestions and support the government in making the civil service more effective while safeguarding and promoting employees' rights and interests. The Civil Service Act envisions one authorized trade union. However, there are six different trade unions in the civil service, and only one of them is unaffiliated with any political party.32 All of these unions enjoy trade union rights. The government may consult the authorized trade unions and seek suggestions while preparing bills, rules and regulations. But since the trade unions are allied to political parties, they often focus on parochial interests rather than the interest of the civil service as a whole. Since 2006, employee unions have been accused of undue influences in promotions and transfers, among other things.Individual ministries are responsible for preparing and enforcing job descriptions and managing employees, including maintaining records of disciplinary action. They have the authority to transfer staff within the ministry. They also review organizational structures and positions, and are required to inform the PSC about vacant positions. All ministries must have their salary reports approved by the Nijamati Kitabkhana (DCPR). Likewise, all ministries are required to evaluate the performance of civil servants. While this is the case, human resource management decisions of the ministry are routinely contested by the unions

### Pros

1. Stong judicial basis, consitutional
2. Predefined areas of work
3. Meritocracy
4. Oversight (by Parliamentary committee, Auditor general, CIAA)
5. Permanency
6. Professionalism (groups and hierarchies)
7. Deciplined (code of conduct guidelines)
8. Trade union
9. Social honor
10. Careerism
11. Integrated civil service
12. Inclusive civil service

### Cons

1. Lacking modernizaiton and technology adoption
2. Lack of motivation and low morale
3. Non predictable career path
4. Poor information management system
5. Low confidence among personnels
6. Tendency to seek rights and refrain duties
7. Lack of redress facility
8. Boss oriented culture
9. Vision and norms have not been institutionalized and widely recognized
10. Corruption
11. Lacking human resource development
12. Excessive centralization
13. Impunity and lacking discipline
14. Resistant to change
15. Lack of a comprehensive system of work reporting
16. Work performance is not closely tied to reward and punishment
17. Innovation and inventiveness is not encouraged
18. Reward and punishment as expressed is narrowly associated with transfer and promotion.
19. Malpractices from trade union

### Future direction

1. Competitive civil service

- Privatization
- Service marketization
- Result oriented management
- Agency based and autonomous approach
- Collaboration

2. Enhancement of effectiveness of civil service

- Gender sensitive
- Responsive
- Efficient
- Accountable
- Transparent
- Participative and predictable
- Adequate facility
- Lean structure

3. Working strategy should integrate following

- Challenging
- Comparison with tax payers
- Consult with tax payers
- Competition with private sector
- Contracting out
- Collaboration with people

4. Reform culture

- Responsibility
- Direct accountability
- Continuous reform
- Work directory
- Tele working
- Use of ICT
- Unified civil service
- Out sourcing
- Virtual organization
- Ombudsman (An official appointed to recieve and investigate complaints made by individuals against abuses or capricious acts of public officials)
- Portfolio management
- Information system management

5. Transitional management

- Enforcement of Law and order
- Control of political interference
- Social legitimacy
- Documentation and implementation of inclusive policies and laws

### Integration of civil service in federal system of governance

1. Generate human resource policy.
2. Merit based federal service and inclusive provincial service.
3. Defining of standards for integration.
4. Protection of service rules and facility.
5. Retirement should be voluntary and not be imposed.
6. Promotion of employee while posting from federal employee to local or provincial tier.
7. Transfer or posting should be more on voluntary basis.
8. Increase age limit to provincial personals as opposed to central level personals.
9. Provisioning of voluntary retirement service (VRS) and CRS with appropriate facility
10. Encourage personnel to be motivated to work at provincial levels rather than at central level.
11. While appointing personnel for rural locations, they should be offered higher benefits
12. Proper integration of career builds while having personnel transfer between federal and provincial levels.
13. Gathering of wide national consensus.

### Fixing problems with civil services

1. Legal problems

- Unclear administrative policies
- Poor implementation of existing policies
- Upgradation and continuity of extant policies is poor
- Unstable government policies
- Policies for personal gains

2. Structural problems

- Large organizational structure
- Redundancy of work
- Cumbersome organizational make-up bearing permanent bodies for tenured jobs
- Structures generated without thorough analysis are defunct.
- Excessive centralization
- Lack of power delegation to implementation body
- Unclear directions and regulation mechanism.

3. Implementation problems

- Process orientation, and unclear ways to activities
- Redundancy in execution
- Poor record and book-keeping system
- Complaint management (grievance handling) system is lacking
- Opaque processes to execution
- Lack of proper communication

4. Behavioural problems

- Power orientation
- Rent seeking
- Buck passing (blame game)
- Lack of professionalism
- System does not always ensure right man in the right place
- Status quo
- Self-centric
- Nepotism, cronyism, sycophany
- Negligence and defence approach
- Non-competance and systematic drag down of competent individuals
- Ruler conscience
- Violation of norms and values
- Lack of team spirit and collaboration

```{r}
tribble(
  ~"Roles and functions", ~"Sector",
  "Macro economic Management", "Economic sector",
  "Education", "Social sector",
  "Energy (electricity, alternative energy and others) and drinking water", "Infrastructure sector",
  "Secretarial services to the Council of Ministers, supervision and coordination", "Governance sector",
  "Transportation (road, air, water and railways) construction and management ", "Infrastructure sector",
  "Civil administration selection management", "Governance sector",
  "Agriculture, food security and irrigation", "Economic sector",
  "land reform and management", "Economic sector",
  "Industry", "Economic sector",
  "Commerce and supply management", "Economic sector",
  "Tourism and culture", "Economic sector",
  "Forest and soil-conservation", "Economic sector",
  "Auditing", "Economic sector",
  "Health, nutrition and sanitation", "Social sector",
  "Social security and protection", "Social sector",
  "Inclusiveness (gender, ethnic, religious, regional)", "Social sector",
  "Mobilization of youth force, capacity development, labour and employment, sports", "Social sector",
  "Decentralisation, local self-rule and local development", "Social sector",
  "Information and communication", "Infrastructure sector",
  "Science and technology (Information technology)", "Infrastructure sector",
  "Environment and climate change", "Infrastructure sector",
  "Urban development and rural infrastructure", "Infrastructure sector",
  "Peace and security", "Governance sector",
  "Defence", "Governance sector",
  "Foreign affairs and economic diplomacy", "Governance sector",
  "Law, justice and parliamentary affairs", "Governance sector",
  "Peace, reconstruction and rehabilitation", "Governance sector",
  "Corruption control", "Governance sector",
  "Statistics and planning", "Governance sector") %>% 
  knitr::kable(booktabs = TRUE)
```

### Provision in place for regulation of civil service

1. Constitution of Nepal, 2072 (Through different constitutional organs and committees)
2. Civil service act, 2049 and regulations, 2050
  - Efficient, competent, service oriented and accountable civil service
  - Provisions regarding conduct, discipline and punishments
3. Prevention of corruption act, 2059
4. Good governance act, 2064 and regulations, 2065
  - Delineates the monitoring and evaluation guidelines for leadership of both political and administrative spheres.
5. Right to information act, 2064 and regulations, 3065
  - Transparency
6. Administrative court rules, 2051 [link](http://www.lawcommission.gov.np/en/wp-content/uploads/2018/09/administrative-court-rules-2051-1995.pdf)
7. Legislature parliament, _rajya byabasta tatha susasan samiti_ (State affairs and good governance), Public accounts committee (For a complete listing of various committes under legislative parliament refer to section on Governance)
8. CIAA, Office of auditor general, Public service commission
9. Ministry of federal affairs and general administration
10. Judicial units of various levels
11. Department of Revenue Investigation
12. Administrative court
13. Administrative Restructuring Commission (ARC) (formed 2008)
14. Speaker ( _prabakta_) of respective units
15. Orientation toward New Public Management (NPM) during policy implementation
16. Awareness has improved among service takers
17. Media and civil society have empowered
18. Concept of inclusive administration
19. Adherence to several international laws and policies
20. Employees are encouraged to be service motive while delivering their services

### Public service in asia

The Asian identity mirrors a rainbow civilisation, both with respect to its internal diversity and cultural particularity. It is, therefore, difficult to weave different sets of identifications of Asians into a common regional awareness and set policy coherence. The common pattern of similarity in Asia is its political culture. Despite the sign of various modes of governance - traditional, democratic, praetorian and authoritarian - cultural attitudes play a key role in shaping institutions and human conduct. Hindu, Buddhist, Confucian, Islamic and Christian civilisations shape this attitude and give primacy on group interests over ideas of individual rights.

Much of philanthropic giving finds roots in religious feeling of compassion. Pre-religious Vedic scriptures of South Asia elaborate four different types of human conduct: bad conduct hurts others; normal conduct is meant to regulate personal and family lives; virtuous conduct aims to help others, such as establishing resting places, inns, schools, hospitals, well, water spouts and uplifting the poor; and supreme conduct governs Yagna, protecting the earth, heavens and the cosmos for tranquility and peace.

It is binding for the adherents of Islam to give 2.5 per cent of their net yearly earning to religious and social institutions called Zakat (alms), which is distributed to the needy. Buddhism seeks to stop the root of violence within every individual so that better relations with family, neighbours, community and states can be built. Stable peace requires developing compassion and giving support to the needy thamtaan. In both Hindu-Buddhist traditions, property obliges the people to perform paropakar, charity work and social service. Confucian thought, like those of Hindus, confers respect to authority, morality, unity and a sense of duty to serve people within the familial, social and political institutions. The highest ethical standard of Confucian tenet is jen. It means affective concern for the well-being of humanity. Confucianism, like Buddhism, is pacifist and attaches value to the notion of datong, implying that the whole world is one big family, akin to the ancient Hindu wisdom—Basudaiba Kuttumbakam.

The current Chinese leadership feels that Confucianism can fill its spiritual void and compete against Western individualism and consumerism for the creation a harmonious society. The defence of Easternisation containing certain Asian values is a defensive response to a one-sided Westernisation. The base of state-society harmony is precisely the familial values of mutual help which has cut the autonomous organisation of civil society. In Eastern Asia officials monopolise the public realm allowing people liberty to chase self-interests in the private sphere. The Christian practice is better institutionalised in charity. Every devout Christian is obliged to give 10 per cent of his or her income to the Church which is spent on public welfare. The Confucian doctrine and the family-oriented Hindu-Buddhist values oblige people to help relatives in crisis times.

Asian businesspersons value the morals of these traditions and assume corporate social responsibility by establishing trusts, charity society and foundations to fund relief projects and social initiatives. These non-profit associations have contributed to the development of specific laws, regulations and several codes of conduct to govern their lives, fulfil diverse needs of citizens and strengthen civil society's engagement in social responsibilities. Despite the persistence of high religions embedded within the institutions often lending legitimacy to state authority and in the religious practices of everyday life of citizens, even in the modernising countries like Singapore, Thailand and Malaysia capitalism is pervading every sphere of life and rapidly individualising citizens eroding the muscle of society for public action.

All over Asia exchange ties determine power and authority. Even in modern states leaders arbitrate the use of rules so that interpersonal relations can run easily, unhindered by laws. This has limped the growth of strong institutions. Those who occupy the state authorities and served by them remain satisfied with weak institutions and fear the depersonalised laws, institutions and processes. And when leaders fail to perform duties citizens replace the leaders, not changing the rules of the game and institutions. It is the strength of personal and professional ties that enable the growth of social capital and moderation of conflict. The general Asian family values make the social change process elite-driven, trickle-down and incremental overlapping tradition and modernity.

On the one hand citizens are loyal to authority, order and hierarchy and on the other hand there is fast erosion of this culture thus marking a paradigm shift from ritualised, clan-based, rural and customary traditional society to detribalised, de-ruralised, class-based, urban and modern society required by rapidly changing economic fundamentals, rationality and political modernisation. This shift has been propelled by information, education and science, growth of modern industrial hubs and cities and globalisation. As a result, one can see a new public sphere in the making entrenched in the democratic processes. A basic tension exists between consensus and conflict in the operation of Asian politics. Educated citizens are mobile, skilled and cosmopolitan and exercise more choices in public life. The globalisation is exposing the Asian public not only into each other's culture but also to world cultures. Enlightened leaders have, therefore, a general willingness to accommodate sub-groups in a common bond of the state.

Many of the Asian leaders' style can be characterised by patrimonialism. Highly personalised leadership coexists with impersonal laws and political institutions bearing the legacy of the traditional polity in which government is personalised and public administration is the extension of the ruler's patronage. Powerful leader controls the political economy and the personal ties increasing people's personal fortune. It implies a lack of strong social discipline—where cultural norms allow the flouting of rules and laws and indulging in corruption--thus a culture of impunity indicating the problem in the institutionalisation of political parties.

The social and cultural context shapes the performance of political institutions. The competition over institutions among various groups is more about power sharing than reshaping lawful institutions. In the weak states of Asia a fatal gap exists in the political order. Decay of democratic institutions mirrors public apathy in politics ripping cross-cutting bonds of solidarity across political institutions with new forms of identity, ideological, ethnic, regional and communal conflicts and even eroding the civility of society. One area of progress is the filling of gender gap in public life. Here, the works of civil society have proved vital in the transformation of politics based on freedom, gender equality, identity and social justice and release modern politics from primitive clutches.

In Asia, the tradition of public service differs from one society to another depending on the level of modernization and reconciliation between traditional and modern ways to adopt the aspirations of diverse peoples. The Asian style democracy represents personality cult, communitarian culture, patronage and valorisation of the state. In the well-off states like Japan, South Korea, Malaysia and Singapore, a basic harmony exists between the capacity of civil society to create public interests and the ability of states to fulfill them. In poorer parts, political institutions are far behind in social, economic and technological change and political promises of leaders outstrip the state's capacity to deliver, inflicting an atrophy of polity.

In South Asia, argumentative culture upholds a pluralistic worldviews animating civic life despite gross inequality. As culture shapes political development, Asian leaders, confronted with the task of setting up modern states, respond to this by shaping patrimonial forms of power that please their deep mental longing for security, stability and status. This may seem authoritarian but it is a natural response to people's needs. It ensures community solidarity, group loyalties and public service. Asia's accelerating transformation may breed new version of civic culture to avoid class conflict, if not geopolitical.

The modernity's wave enabled the Asian leaders to set up the centrality of bureaucracy, dominant party system and traditional politics. Now, its erosion now gave the birth to coalition politics where diverse interests are represented in the polity offering the mobility of class, caste and gender. Old Asian texts treasure precious ideas for protecting civilized life, liberty and identity beyond social contract. They offer liberal thought on learning, leadership, virtue, just and unjust wars, civility, nobility and common good. In urban nodes the birth of civic coalitions seeks to prevent the fading egalitarian culture while their rural counterparts detest clintalistic nature of winner-takes all political economy.

The East Asian style of trust building is typified by informal, leader-centric and non-interfering in other's affairs. Religions also played a role in it. The Buddhist concept of Sangha and Hindu's Sat Sanga played their role in incubating social capital like the art of association defended by Tocqueville. Each civilisation has produced a distinctive pattern of ties between the state and society and tied people's compliance to order, authority and discipline. In some regions secular nationalism is still the dominant force at the elite level. In others, religious and ethno-nationalism as well as tribal instinct are challenging the state's writ.

The denial of democratic rights to sub-groups of society has forced them to resort to distributional, identity and rights-based struggle as a reaction to the imposition of Western model of state in multi-cultural societies. Persistence of weak mediating structures in society framed in the image of golden mean involving the satisfaction of basic needs, individual freedom in thought, speech and action, decentralised society, avoidance of a complete separation of the sacred and secular in ordinary life and articulation of sustainable progress explain this. This golden means is vital in every sphere of life to establish the condition of middle ground between liberalism and relativism, globalism and localism and cosmopolitan citizenship and nationalism. 

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/28797}

### Facilities and benefits of public service personnels

\begin{questions}

\question What are the current facilities and remunerations in place for public service personnels ?

\begin{solution}

The facilities and remunerations that public service employees receive are the benefits they are authorized to for dedicating their labor, skill and time in providing service on behalf of government. The reward-facilities may be monetary or non-monetary. The civil service act, 2049 and civil service regulations, 2050 provisions following reward and facilities to the employees:

Monetary reward-facilities

\begin{itemize}
\item Monthly salaray and allowance
\item Grade facilites (increment of salary) after serving for a year
\item Payed holiday service
\item Facility of retirement benefits upon phasing out of service
\item In event of heart, kidney and cancer diseases there is provision additional 5 lakhs support
\item Life insurance of upto 1 lakhs
\item Every year 1 month salary amount will be offered as festival benefit to working personnels
\item Retired personnels will receive a retirement benefit amount of 1 month in addition to regural amount every year as festival benefit
\item Saving of salary (10 percente) as provident fund and additional amount equal to the salaray fraction will be paid by government
\item Provision of payment for health treatment -- equalling 12 month salary for gazatted officer, 18 month and 21 months salary for non-gazatted personnels and personnels without level specification, respectively.
\item Two third of the increased salary will be available in retirement pension, in every raise in salary.
\item Family pension or retirement fund payment
\item Family will be granted Rs 150,000 in case the personnel dies while in service
\item For death of civic service personnel member in a family, child care allowance of 5000 for a child each (for 2 children) will be provided.
\item Monetary award in civil service day to awardees.
\item Allowance for uniform and dress
\item Educational fund, family fund and disabled personnel fund facilities
\end{itemize}

Non-monetary reward-facilities

\begin{itemize}
\item Relocation transfer every 2 years, alternating between rural and urban centres
\item If both husband and wife are employed on the same service they will be attempted for transfer to a common district
\item Non-gazatted personnels will most likely be transferred to nearest localities to their home.
\item Leaves of different kinds
\item For foreign residing ambassadors and personnels employed in consular offices, at most 5 years of unpaid leave will be provisioned
\item Employee service protection, service contract protection and employee protection related provisions
\item For advocating professional rights of personnels, freedom for alignment in trade union
\item For punishing a personnel on beaureucratic basis, provison of refarral to the public service commission.
\end{itemize}

\end{solution}

\question What are the recommendations for making public service more attractive in Nepal ?

\begin{solution}
\begin{itemize}
\item Update basic pay and salary features to reflect contemporary status
\item Develop "pay for performance" indicator and implement in all offices
\item Provision special facilities for personnels working in rural areas
\item Update allowance offerings on dressing and uniform
\item Construction of integrated residence facilities for personnels
\item Automate transfer and promotion system in order to make it more transparent and predictive
\item In order to provision personnels filing up vacant positions in public sector, employee recruitment system should be more responsive and expedient, possibly arraning for twice a year recruitment.
\item Improve workplace environment and render it free of unncessasry interferes.
\item Identification and punishment of wrongdoers amongs the recruited personnels in order to improve public image of the service.
\item Upgradation of public service act and regulations to reflect contemporary needs to make service modern and public friendly.
\end{itemize}

Finally, It should be acknowledged that public service personnels are the carriers of social change. Therefore the sector should be strengthened, efficient and progressive. For this to happen several fiancial, including monetory and non-monetory, amendments should be made. Recruitment process should be streamlined and moderninzed to allow easy entrance of competent individuals. It should be ensured that the personnels are efficiently mobilized. Only then, the public service sector can manifest its full potential. This develops both the service sector and its employees and improves the productivity of the service.

\end{solution}

\end{questions}

## Decentralization

\begin{questions}

\question What is devolution ?

\begin{solution}

Devolution is defined as the transfer of power from higher to lower units of any system. In its broad form devolution resembles decentralization, but is often regarded as being more complete and permanent than decentralization. Most frequently, devolution is used with reference to the transfer of responsibilities and authority from central to subnational (or regional to local) levels of government. The World Bank distinguishes between deconcentration, delegation, and devolution as three distinct modes of administrative decentralization of the redistribution of authority, responsibility, and financial resources for providing public services. The three types are differntiated according to the degree of transfer, with decentralization being the weakest form and delegation coming next. 

The need for decentralization is not just an option for countries as a way of good governance. It is increasingly being necessitated by circumstances, both national and international. National pressure for decentralization stems from the openness of the polity that is being increasingly adopted throughout the world. In Nepal, political openness was institutionalized in 1990 by restoring multiparty rule. Real democracy requires the people themselves to be involved in shaping their own lives. And decentralization is the only means of devolving authority from the center to the local units of governance.

Hence, devolution is regarded as the strongest mode of decentralization in the sense that powers are devolved to political entities with a separate corporate status, such as local or regional governments. That is why devolution is also referred to as political decentralization. 

Motivations for devolution in that sense include the perception that devolved governments are best placed to develop and implement policies that exploit endogenous local or regional capabilities and are, hence, an appropriate reaction to increased competition between regions in a globalized economy.

To qualify as a devolved system, the subnational levels of government should be legally established as institutions that exercise power within clearly recognizable geographical boundaries. Other criteria include democratic institutions such as popular elections and the existents of assemblies.

Another aspect of the national imperative to decentralize for countries like Nepal comes from a combination of the country's geography and the status of its economic development. Since communication between the center and local governments is not as smooth as it is with countries having adequate infrastructure, one needs a measure of local autonomy to run local affairs, if only to avoid delays in decision-making. Similarly, the diversities existing among the people and places are not conducive for central governments to provide directives for everything. Even simple government tasks like running high school graduation examinations will need to keep the local circumstances in mind. It is not always possible for the center to run local operations. Hence, decentralization becomes an imperative.

At a time when national economies are being pushed by global forces towards centralization of a global scale, there is a need for governments throughout the world to decentralize as much powers as they can so that each local unit can decide on how to protect its own resources from unfair exploitation by global developments and instead extract benefit from them. This means that even for the protection of national identity and national interests, central governments throughout the world will be forced to seek the help of local efforts. There is no alternative to decentralization, the only question is how to go about it.

Decentralization goals were set by the National Planning Commission (NPC) since the Third Five-Year Plan (1964-69) to create a financial basis for people's participation. The Seventh plan also laid stress on formulation, implementation, maintenance and mobilization of local resources and talents. The Panchayat system had granted the local bodies taxation rights under Panchayat Development and Land Tax. The basic structure of the political economy-- social mobilization through local units and Back to the Village National Campaign, land reforms, modernization of health, education, agricultural, industrial and service sectors, development of transport and communication and the spatial and sectoral differentiation of the planning tradition, management and coordination system -- created by the Panchayat system laid down the socioeconomic base for development in Nepal.

The Nepal's constitution of 1990 made powerful provisions for decentralization. First of all, it shifted the power from an all-powerful monarch to the citizens in favor of an open and democratic system of governance, multi-party polity, popular sovereignty, constitutional and human rights to the people and constitutional monarch. Two "nesting" rules of the Constitution governed the mandate of decentralization in Nepal. First, the Directive Principles and Policies of the State articulates that "conditions suitable to the enjoyment of the fruits of democracy through wider participation of the people in the governance of the country by way of decentralization, and to promote general welfare by making provisions for the protection and promotion of human rights, by maintaining tranquility and order in society" need to be maintained. Second, Article 46(C) stipulated that fifteen members, three from each of the Development Regions, will be elected to the Upper House of Parliament in accordance with law on the basis of the system of single transferable vote by an electoral college consisting of the Chief and Deputy Chief of the Village Development Committee (VDC) and municipality level local authorities and the chief, deputy chief and the members of the District Development Committee (DDC). These two provisions provided the constitutional legitimacy to local self-governance in Nepal.

Decentralization policies appear more pronounced in the Ninth Five-Year Plan (1997-2002). It aimed to strengthen the local units to take the responsibility of formulating and executing local development plans by themselves. This is supposed to be achieved by institutionalizing local government, increasing people's participation in the mobilization and distribution of local resources, social and economic development of geographically disadvantaged areas, improvement, expansion and development of suitable local technology, entitlement of women, indigenous and backward communities of rural areas, enhancing the participation of local people for sustainable development and establishing technological and human development infrastructure in rural areas.

Local self-governance in Nepal came at a time when the state was squeezing itself through an economic crisis and structural adjustment policies. A devolution of expanded responsibilities at such a time meant that the local units were left without the requisite authority and resources. Even then they were more concerned about autonomy than anything else. Local government federations, that represent the coalition of interests and are united for collective action, have argued for the application of "subsidiarity" in decision-making and favor an autonomous self-governance involving devolution. It seems to reflect that horizontal, locally-controlled organizations are instrumental in stocking interpersonal trust and social capital because of the proximity of people and their familiarity with each other and, consequently, better able to cooperate in development efforts.

To unify all these Acts and to prepare a comprehensive framework for local self-governance, Prime Minister Sher Bahadur Deuba appointed a High Level Decentralization Coordination Committee (HLDCC) under his Chairmanship in late 1995. It identified several weaknesses in past practices, such as undefined scope and jurisdiction of local self-governance, overlapping laws, deficiency in institutional culture, lack of political determination, resource scarcity, absence of a mechanism to enforce civic accountability among the elected bodies and government officials, problems in the sustainability of development projects, dearth of planned development processes, flawed elections and organizational technique, etc. Similar problems were identified in the realms of coordination, monitoring and evaluation of development activities. (HMGN, 1996:29-34). Accordingly, a Bill was prepared by HLDCC to be presented in the Parliament. It was replaced in 1997 by the coalition government of UML, RPP and NSP led by Lokendra Bahadur Chand. This coalition government brought an ordinance to amend some laws relating to local bodies and local elections and initiated changes in the power, composition, representation and organizational set up of the LGIs. All these are included in a separate Local Governance Bill passed by the parliament on September 18, 1998. The promulgation of the Local Self-Governance Act (LSGA, 1999 and Rules 1999) thus provides a detailed framework for decentralization and constitutes a basis of good governance at the grassroots level.

The first priority for the Nepalese government is to create a central level neutral institution of local federations and independent experts to build consensus on major development issues and to avoid policy weakness, policy instability and policy reversals. The second is establishment of effective institutions of political authority at the level of the state, polity and the government before social democratization, market reforms and power devolution can take place. The pulling of the collective strengths of the state, the market and civil society through an effective coordination mechanism is essential to make the power of the center effective and responsive. Constitutionalization of these forces including establishing a system of effective checks and balances and power separation is equally important to foster the democratic attributes of rule of law, transparency, accountability and equity. Only then can governance accomplish the needed virtuous circle (synergy) for development.

\end{solution}

\question Write short notes on:

\begin{enumerate}
\item Deconcentration
\item Delegation
\item Privatization
\item Denationalization
\item Deregulation
\end{enumerate}

\begin{solution}

\textbf{Deconcentration}

"merely involves the shifting of workload from central government ministry headquarters to staff located in offices outside of the national capital." (Rondinelli et al: 1989,76) Decentralization based on de-concentration does not allow the local units ample freedom to take initiatives and decisions without the consent of the central authority. But, it allows the delegation of certain financial and administrative decision-making powers to local authorities and people do not have to go to the capital city for every decision.

\textbf{Delegation}

"refers to a situation in which the central government transfers responsibility for decision-making and administration of public functions to local governments or semi-autonomous organizations that are not wholly controlled by the central government but are ultimately accountable to it" (Litvack, et al 1998: 4-6). Delegation of power thus implies granting of some authority and decision-making powers to local authorities. But central government retains the power to reverse the local decisions and can take these powers back. Local authorities are responsible to carry out only assigned functions. They do not have autonomous policy-making capacity. The delegation of power means the delegation of trust.

\textbf{Privatization}

Privatization "is the act of reducing the role of government, or increasing the role of the private sector, in an activity or in the ownership of assets." (Savas:1987, 89). It is widely contended that too much state intervention strangles the productive energies of the private sector. In many de-communized and authoritarian regimes, centralized planning contributed to a swelling bureaucracy and helped in sustaining the political status quo. Critics argue that privatization is intended to separate the economy from social control by granting industrialists and business classes autonomy from the state and society, has fostered different stages of development within the same state and has justified economic growth free from ethics and civic obligations. In nations like the United States, Canada, Brazil and Mexico and the newly industrialized countries of Asia, for example, privatization has produced a rapid decay of the public realm, an indiscriminate depredation of the public good and the maldistribution of market-driven benefits.

\textbf{De-nationalization}

Denationalization is a particular form of privatization that involves "selling to the private sector (or giving away to the public or the workers) government-owned enterprise or government-owned assets used in producing goods or services; by extension, this form of privatization also encompasses "demunicipalization', and other forms of "de-statification". (Savas, 1987: 89). The defenders of the free-market school of thought have a radical imagination. They imagine that self-help organizations, non-government organizations and private sectors will be able to initiate development only through the erosion of the re-distributive capacity of the welfare state. Besides this, they also favor the free play of market forces as a convenient strategy to empower individuals to build their own fate.

Critics argue that the mobility of capital, technology and information across borders has not only challenged the coherence of democratic governance but also pointed to the withering human values and the very social fabric of democratic accountability. The cost of the actual decline in real wages, job layoffs, the widening gulf between the rich and the poor and de-coupling the fate of the workers from corporate profits has been enormous. In other words, structural adjustment of only the poor people is taking place which, by implication, is causing a democratic deficit. The belief in the capability of market-based transactions to solve all problems, including social ones, has fostered the most narrowly profit-oriented definition of rationality.

\textbf{Deregulation}

"franchises eliminating other price control and entry barriers in order to permit the market to respond to peoples' needs"(Savas, 1989: 89). The reason for deregulation is that bureaucratic control over policy breeds bribery, corruption, commission and patronage and impedes economic growth. Deregulation of labor markets and a reform in the tax structure might induce external investments but these investments must be weighed against the unintended effects in social sector activities, especially the ecology, education, health and welfare. Creating a flexible environment in business and excessive extraction of natural resources for export in the process of becoming market-friendly make the majority of the poor even more deprived of a sustainable livelihood. 

Its critics, therefore, argue that without a proper coordination the people of developing countries suffer badly owing to their smaller competitive advantage. They thus remain vulnerable to external market fluctuations. Therefore, cutting of tariffs, privatization, opening the economy to foreign companies and total denationalization of development subvert the various policy-oriented issues including monetary and fiscal policies, expenditure and pricing. Some degree of central control is, therefore, essential to keep various societal elements in balance (such as defense, foreign policy, banking and the social sectors, etc.) and to prevent the possibility of anarchy.

\textbf{Debureaucratization}

The notion of 'downsizing the state,' to create private opportunity and personal responsibility in all the realms of human life provides the rationale for cutting down the size of the bureaucracy. De-bureaucratization also encompasses the reduction of the role of the central government in many areas of the national economy (Dahal, 1996). It should also oppose the power of large corporations, if they have a monopoly. Debureaucratization pushes for deregulating the economy in an effort to promote incentives, competition, efficiency, transparency and accountability. Essentially, a bureaucratic state is identified by its techniques of ruling, regulating and governing the polity, economy and society through the use of a bureaucracy. Since bureaucratic forms of administration have proved unsuccessful in large-scale organizations, owing to their hierarchy, chain of command, status-oriented role, over-regulation, and technocracy-based culture, it impedes the process of economic growth, innovation and development.

In order to push for a Weberian type of 'legal-rational' bureaucracy, efficient enough to innovate, adapt, and orient itself towards a goal, rational choice theories advocate 'de- bureaucratization' of the development and governance processes and rational control of the environment. In developing countries, in general, and Nepal, in particular, political democracy followed a series of economic reforms. The policy imperative of de-bureaucratization to give a sufficient degree of freedom to private entrepreneurs had thus already been realized before the multiparty polity was ushered in. Neoclassical economists view that bureaucracy has its own autonomous interests which may neither coincide with democracy nor development. Liberal and Marxist theorists reveal that bureaucracy represents the essence of a state, and the state, in turn "represents an aggregation of private interests in which public policy is but the outcome of a pluralistic class struggle among interest groups." (Gilpin: 1975,28)

Bureaucracy needs to be reinvented to make it efficient, people-centered and fair. The Weberian type of legal-rational bureaucracy worked well during the agricultural and industrial revolutions when people worked with hands, rather than brains. It provided job security, economic stability, infrastructure development and social justice. But, in the information society of today, competitive market pressures have put the hierarchy-laden bureaucracy under duress rendering it increasingly difficult to function. An information society requires flexible and adaptable institutions that can offer high quality goods and services to the people. "It demands institutions that are responsive to their customers, offering choices of non-standardized services; that lead by persuasion and being inventive rather than commands; that give their employees a sense of meaning and control, even ownership. It demands institutions that empower citizens rather than simply serving them." (Osborne and Gaebler: 1992,15)

\end{solution}

\question What is the relationship between decentralization and good governance ?

\begin{solution}

Good governance and decentralization are inextricably linked in today’s Nepalese context. Rational allocation of decision-making is central not only to the efficient operation of a democratic polity but also to prevent an overburden of the decision-making load on a particular level of governance to its breakpoint and disintegration. Management efficiency cannot be had without a substantial devolution of central power, responsibilities and resources to sub-national units of government. It also enlarges the area for decision-making freeing the grassroots from the straitjacket of central directives. With a major constraint to the realization of the common people's aspirations gone, a wider space for people's representation and participation from below becomes available. Any complex society requires a diverse, heterogeneous and multitudinous decision making structure to carry out its multiple tasks in a coherent, explicit and predictable manner.

Apart from the moral imperative to work for greater democracy, there is also a political directive to decentralize government. The ongoing process of globalization and the expanding participation of people have overwhelmed the power of the central government to decide and act swiftly and efficiently. New conditionalities of foreign aid focus on people's preference and priorities, ownership, equity and participation in policies, institutions and processes in policy making. In other words, the central government is under greater pressure today than in the past to shift some of its powers to local units of self-governance--a governance that can become a workshop for citizen participation, community building, leadership development, social mobilization, conflict resolution and economic, political and social development.

It will prove to be a difficult process given the centralization tendencies not only of national politics and policy but also of international pressures from global centers of finance and multilateral centers of development policy. Apart from that are regional obligations of the state that make the task of decentralization all the more difficult, but even more necessary.

\end{solution}

\end{questions}

## Public policy making

\begin{questions}

\question What are the problems in implementing public policy in Nepal ?

\end{questions}
