# Public administration and management

## Bureaucracy

German sociologist Max Weber, who used an "ideal type" approach to extrapolate from the real world the central core of features that would characterize the most fully developed bureaucratic form of organization. Weber's ideal type of bureaucracy possesses the following characteristics:

1. The bureaucrates must be free as individuals; they can only be bossed around with respect to the impersonal duties of their offices.
2. The bureaucrats are arranged in a clearly defined hierarchy of offices, the traditional scalar chain wherein every bureaucrat has an unambigious place -- and knows his or her place!
3. The functions of each office are clearly specified in writing.
4. The bureaucrats accept and maintain their appointments freely -- without duress. Slave bureaucrats, while once fashainable in the Ottoman empire and Imperial china, are an inherent contradiction except within military or prison organizations.
5. Appointments to office are made on the basis of technical qualifications, which ideally are substantiated by examinations administered by the appointing authority, a university, or both.
6. The bureaucratis receive money salaries and pensions rights, which reflect the varying levels of the hierarchy. While the bureaucrats are free to leave the organization, they can be removed from their offices only under previously stated, specific circumstances.
7. The office must be the bureaucrat's sole or at least major occupation.
8. A career system is essential; while promotion may be the result of either seniority or merit, it must be premised on the judgment of hierarchial superiors.
9. The bureaucrats do not have property rights to their office nor any personal claim to the resources that go with it.
10. The bureaucrat's conduct must be subject to systematic control and strict discipline.

## Management: introduction, concept, objective, scope and function

Management is both the art as well as science. Management as a science would indicate that in practice, managers use a specific body of information and facts to guide their behaviors, but that management as an art requires no specific body of knowledge, only skill.

Practicing managers who believe in management as a science are likely to believe that there are ideal managerial practices for certain situations. This manager is likely to follow general principles and theories and also by creating and testing hypotheses. The scientific management movement was the primary driver of this perspective. Scientific management, pioneered by Frederick W. Taylor, Frank and Lillian Gilbreth, and others, attempted to discover "the one best way" to perform jobs.

**Frederick W. Taylor's principles of scientific management**

:::: {.center data-latex=""}

::: {.minipage data-latex="{.5\linewidth}"}

1. Managers must study the way that workers perform their tasks and understand the job knowledge (formal and informal) that workers have, then find ways to improve how tasks are performed.
2. Managers must codify new methods of performing tasks into written work rules and standard operating procedures.
3. Managers should hire workers who have skills and abilities needed for the tasks to be completed, and should train them to perform the tasks according to the established procedures.
4. Managers must establish a level of performance for the task that is acceptable and fair and should link it to pay system that rewards workers who perform above the acceptable level.

:::

::::

Practicising managers who believe in management as an art are likely to rely on the social and political environment surrounding the managerial issue, using their own knowledge of a situation rather than generic rules to determine a course of action. Henry Mintzberg is probably the most well-known and prominent advocate of the school of thought that management is an art.

Another scholar that promoted the notion of management as an art was David E. Lilienthal, who in 1967 had his series of lectures titled Management: A Humanist Art published. In this set of published lectures, Lilienthal argues that management requires more than a mastery of techniques and skills; instead, it also requires that managers understand individuals and their motivations and help them achieve their goals. Lilienthal believed that combining management and leadership into practice not only by getting work done but by understanding the meaning behind the work, as effective managerial behavior. Thus, he promoted the idea of the manager as a motivator and facilitator of others. This manager as an artist was likely to respond differently to each employee and situation, rather than use a prescribed set of responses dictated by a set of known guidelines.

In a paper by Luther Gulick, he identified seven management functions using the acronym **POSDCORB**. It was first presented in 1935. Initially, POSDCORB was envisioned in an effort to develop public service professionals.

- Planning
- Organizing
- Staffing
- Directing
- Coordinating
- Reporting
- Budgeting

Gulick's "Notes on the Theory of Organization" further defines the patterns of POSDCORB. That document explains how portions of an executive's workload may be delegated, and that some of the elements can be organized as subdivisions of the executive depending on the size and complexity of the enterprise.

Under Organizing, Gulick emphasized the division and specialization of labor in a manner that would increase efficiency. Yet Gulick observed that there were limitations. Based on his practical experience, he carefully articulated the many factors.

Gulick described how the organization of workers could be done in four ways. According to him, these are related and may be multi-level. Specifically, they are:

- By the purpose the workers are serving, such as furnishing water, providing education, or controlling crime. Gulick lists these in his organizational tables as vertical organizations.
- By the process the workers are using, such as engineering, doctoring, lawyering, or statistics. Gulick lists these in his organizational tables as horizontal organizations.
- By the clientele or material: the persons or things being dealt with, such as immigrants, veterans, forests, mines, or parks in government; or such as a department store's furniture department, clothing department, hardware department, or shoe department in the private sector.
- By the place where the workers do their work.

Gulick stresses how these modes of organization often cross, forming interrelated structures. Organizations like schools may include workers and professionals not in the field of education such as nurses. How they are combined or carefully aggregated into a school - or a school system - is of concern. But the early work of Gulick was not limited to small organizations. He started off his professional career at New York City's Bureau of Municipal Research and advanced to President Franklin D. Roosevelt's Committee on Administrative Management.

Under Coordination, Gulick notes that two methods can be used to achieve coordination of divided labor. The first is by organization, or placing workers under managers who coordinate their efforts. The second is by dominance of an idea, where a clear idea of what needs to be done is developed in each worker, and each worker fits their work to the needs of the whole. Gulick notes that these two ideas are not mutually exclusive, and that most enterprises function best when both are utilized.

Gulick notes that any manager will have a finite amount of time and energy, and discusses span of control under coordination. Drawing from the work of Henri Fayol, Gulick notes that the number of subordinates that can be handled under any single manager will depend on factors such as organizational stability and the specialization of the subordinates. Gulick stops short of giving a definite number of subordinates that any one manager can control, but authors such as Sir Ian Hamilton and Lyndall Urwick have settled on numbers between three and six. Span of control was later expanded upon and defended in depth by Lyndall Urwick in his 1956 piece The Manager's Span of Control.

Under coordination, as well as organization, Gulick emphasizes the theory of unity of command: that each worker should only have one direct superior so as to avoid confusion and inefficiency.

Gulick discusses the concept of a holding company which may perform limited coordinating, planning, or budgeting functions. Subsidiary entities may carry out their work with autonomy, but as the holding company allows, based upon their authority and direction

## New Public Management (NPM)

This concept was put forward in 1990s and aims to overcome the drawbacks facing traditional system of administration. NPM is best understood as a conceptual framework that draws on private-sector notions of disaggregated operations with market-based controls to produce efficient and effective outcomes in the public sector. In the briefest of quips, proponents of NPM contend that government should be run like a business. All of this aims to transformation of public administration to public management, improvement in public services and administration, improvement of administrative capacity and competitiveness.

According to Christopher Pollitt (1993), "the new public management" has four main aspects:

1. A much bolder and larger-scale use of market-like mechanisms for those
parts of the public sector that could not be transferred directly into private
ownership (quasi-markets).

2. Intensified organizational and spatial decentralization of the management
and production of services. 

3. A constant rhetorical emphasis on the need to improve service "quality".

4. An equally relentless insistence that greater attention be given to the wishes of the individual service user/"consumer."

In the final quarter of the twentieth century NPM reforms swept across developed democracies in countries such as New Zealand, Australia, Great Britain and the US. The political prominance of these reforms, combined with resulting changes in management practice makes it tempting to view NPM as the way the work of state gets done today. In practice, public management remains highly varied and much of the old structures of centralizaiton and bureaucratic hierarchy remain firmly entrenched.

Two impetuses that gave rise to a new concept of public management are bureaucratic distrust and public choice theory. Shortcomings of the public management in early days were picked as being grown to unimaginable proportions, far from politically neutral, relied upon formal rules and internal hierarchy to function. An NPM framework moves away from large, discernable public agencies, preferring to engage a host of agencies - public and private - in the delivery of public goods and services. Further, an NPM framework divests itself of the democratically derived mandate for political neutrality by expressing democracy differently, either through the provision of service options (i.e., the people "vote" with their choice) or public participation (i.e., the people "vote" through participation). Finally, an NPM framework leaves behind formality and hierarchy to stress managerial dexterity and entrepreneurialism.

The public choice theory has a long history stretching back more than two centuries. In brief, public choice theory -- or more simply, public choice -- looks to apply economic concepts to political ideas. One of the more influential works on the subject was offered by James M Buchanan and Gordon Tullock in their 1962 The calculus of consent: Logical foundations of constitutional democracy. Two themes undergird the authors' work: methodological individualism and decentralized organizational arrangements. 

For the welfare of public, there should exist alternatives in public sector as well. Only then people can have their choice, much alike the idea private sector thrieves on.

Principal agent theory

It is also termed as principal agent problem. This occurs when one person or entity (the "agent"), is able to make decisions and/or take actions on behalf of, or that impact, another person or entity: the "principal". This dilemma exists in circumstances where agents are motivated to act in their own best interests, which are contrary to those of their principals, and is an example of moral hazard. The principal and agent theory emerged in the 1970s from the combined disciplines of economics and institutional theory.

When it comes to fighting corruption, the 'Principal-Agency Theory' is helpful in discerning the good or the bad, which assumes that corruption is an individual aberration where due to information asymmetry, inadequate monitoring and incentive and the punishment system, the principal cannot detect corruption by his/her agent(s).The solution here is to get rid of one or two rotten apples in order to save the whole lot. There is no problem with this theory as long as its assumptions are correct.

https://kathmandupost.com/opinion/2016/06/19/corruption-vs-anti-corruption

## Public administration in Nepal

Modern public administration has a relatively short history in Nepal. It began taking shape in the early 1950s and has continued to evolve alongside the political changes and upheavals that have marked the period between 1950 and 2010. Politics shape government structure and functions, and the state administration cannot remain insulated from changes in the political landscape. Nepal has had two administrative reform commissions, one in the 1950s and another in the early 1990s. There was no such commission after the political changes of 2006, but it is likely there will be a new one after the new constitution is prepared, because the prospective new federal system will require restructuring public administration.

Nepal has had an essentially parliamentary form of government since 1990, and state structures have been designed to match the needs of the polity. An analysis of government structures and functions suggests that they resemble those in countries with similar forms of government, but with idiosyncrasies and inefficiencies unique to Nepal. For instance, there are over 150 development boards and committees created for various purposes (for expediting projects, for example), and many of them are not even functional. While such boards and committees can often be effective, the fact that so many are inactive suggests that they are redundant, unnecessary, or have outlived their purpose.

The governance act (GGMOA) clearly lays down the standards for government business at all levels. These include taking into account the larger interests of the people and nation, equity and inclusion, rule of law, human rights, transparency, objectivity, accountability and integrity, financial discipline, fairness, efficiency, accessibility, decentralization and devolution, utilization of local resources and participation. These principles, however, are not always evident in practice, as is clear from the reports of different accountability agencies such as the CIAA, NVC, and parliamentary committees, as well as the mass media and other civil society groups. 

In principle, governments exist to serve the people. This ideal informs public policies like the provisions of the GGMOA just enumerated. But ideals expressed in broad terms like 'national interest' are more easily interpreted for political convenience than concrete benchmarks like the *Rashtriya Mool Niti* that existed before the 1990s. Clear and concrete language would better guide decision makers in interpreting the provisions of the GGMOA, and better serve the public interest.

Openness and transparency are vital for accountability, because only an informed public can demand and make use of effective public services. While both openness and transparency are acknowledged public policy objectives, the lack of adequate and timely information remains a major obstacle that continues to prevent people from accessing services effectively or holding public officials accountable for non-performance.

Further, while accountability is a stated government objective, the fact that Cabinet deliberations are still protected by law from public scrutiny or court review suggests that the desire to 'protect' government information is a strong one, and that thoroughgoing accountability will remain hard to achieve. The GNBTR and GNBAR are not public documents in Nepal, while similar laws are readily available on the websites of other parliamentary democracies such as India. While there may be good reasons for protecting the confidentiality of government deliberations until a decision has been reached (though this has not been the practice, particularly since 2006), keeping Cabinet deliberations secret forever represents a mismatch between the ideal of accountability and the actual practice of government in Nepal.

Nepal has constitutional checks and balances on the executive, with bodies that get their mandate from Interim Constitution. Again, in principle, these bodies are independent — for example, appointees cannot be members of political parties — but their independence is questionable, given that political parties nominate the candidates, often based on affiliation rather than competence, a particularly common practice since 2006. Since political parties are not transparent about their membership, and there is no way to check membership roles of parties that do not release them, there is no way to ascertain the party affiliation of appointees. The clause requiring non-partisan nominees is meaningless in the absence of a mechanism to check if nominees hold party membership or not.

## Group dynamics

A group can be defined as several individuals who come together to accomplish a particular task or goal. Group dynamics refers to the attitudinal and behavioral characteristics of a group. Group dynamics concerns how groups form, their structure and process, and how they function.

Group dynamics are relevant in both formal and informal groups of all types. In an organizational setting, groups are a very common organizational entity.

### Group formation and development

There are several theories as to why groups develop. A classic theory, developed by George Homans, suggests that groups develop based on activities, interactions, and sentiments. Basically, the theory means that when individuals share common activities, they will have more interaction and will develop attitudes (positive or negative) toward each other. The major element in this theory is the interaction of the individuals involved.

Some of the other theories explaining why group formation occurs are:

- Social exchange theory (individuals form relationships based on the implicit expectation of mutually beneficial exchanges based on trust and felt obligation)
- Social identity theory (individual get a sense of identity and self-esteem based on their membership in salient groups)

The most com mon framework for examining the "how" of group formation was developed by Bruce Tuckman in the 1960s. In essence, the steps of group formation imply that groups do not usually perform at maximum effectiveness when they are first established. They encounter several stages of development as they strive to become productive and effective. According to Tuckman's theory, there are 5 stages of group development:

1. Forming
2. Storming
3. Norming
4. Performing
5. Adjourning

### Group types

Groups may be classifed based on whether they are formal or informal in nature. Formal work groups are established by an organization to achieve organizational goals. Formal groups may take the form of command groups, task groups, and functional groups.

In contrast to formal groups, informal groups are formed naturally and in response to the common interests and shared values of individuals. They are created for purposes other than the accomplishment of organizational goals and do not have a specified time frame. Informal groups can take the form of interest groups, friendship groups, or reference groups.

### Group structure

It refers to a pattern of relationships among members that hold the group together and help it achieve assigned goals. Structure can be described in a variety of ways. Among the more common considerations are group size, group roles, group norms, and group cohesiveness.

## Leadership, decision making, encouragement and motivation

### Motivation

An organization is an entity of human and non-human resources joined together to achieve a predetermined objective or objectives. 

In reality individual and organizational objectives are often at odds. Man, the psychologists say, is a wanting animal. AH Maslow has defined a hierarchy of needs to be:

1. Physiological needs -- hunger, thirst, etc.
2. Security, shelter, warmth
3. To belong
5. Self-expression
6. Self-fulfilment

Once the major needs of security and hunger, etc. have been satisfied, it is likely that organizations which follow purely mechanical systems, ignoring personal objectives, will find receding morale in employees. Thus scientific management relies primarily on the instrumental rewards strategy to motivate employees. Pay bonuses are distributed to workers who meet or exceed performance standards. Taylor believed pay is important to workers because it is instrumental in helping them achieve their personal goals, goals that lie primarily outside of the workplace.

Frederick Herzberg has devised "motivational" and "hygiene" factors. The former type include:

1. Achievement
2. Recognition
3. Advancement
4. Work self
5. Possibility of growth
6. Responsibility

This short synopsis of behavioral theory indicates only that there is a growing body of opinion which suggest that all the old ideas about motivation, based on financial incentives, need to be critically examined.

## Organizational behavior

### Theory X and Theory Y

Psychologists have long been noted for their studies of human and animal motivation. The operative discipline in organizational motivation is philosophy. The sincerity and rigor of the motivation of employees toward their duties is a direct reflection of management's philosophy toward them. That an operative philosophy is neither written down nor formally stated is irrelevant to its existence. Many organizations have commendable formal managerial philosophies. Ream upon ream of paper have been dedicated to espousing an official view of what an idyllic place the jurisdiction is in which to work. The only problem with these fine-sounding philosophies is that they are seldom operational, tending to exist only on paper. 

All managerial philosophies are premised on a set of assumptions about human behavior. Douglas McGregor, through his 1960 book The Human Side of Enterprise, popularized the contending concepts of managerial philosophy with his now famous Theory X and Theory Y sets of assumptions. McGregor hypothesized that a manager's assumptions about human behavior predetermined his administrative style. Because of the dominance of traditional theory in managerial thought, many managers had long accepted and acted on a set of assumptions that are at best true of only a minority of the population. McGregor labeled as Theory X the following assumptions:

1. The average human being has an inherent dislike of work.
2. Most people must be coerced or threatened with punishment to get them to put forth adequate effort.
3. People prefer to be directed and wish to avoid responsibility.

While McGregor's portrait of the modern industrial citizen can be criticized for implying greater pessimism concerning human nature on the part of managers than is perhaps warranted, Theory X is all the more valuable as a memorable theoretical construct because it serves as such a polar opposite of Theory Y, which assumes the following:

The expenditure of physical and mental effort in work is as natural as play or rest.
2. A person will exercise self-direction and self-control in the service of objectives to which he or she is committed.
3. Avoidance of responsibility, lack of ambition, and emphasis on security are generally consequences of experience, not inherent human characteristics.
4. The capacity to exercise a relatively high degree of imagination, ingenuity, and creativity in the solution of organizational problems is widely, not narrowly, distributed in the population. 

Of course, these differing philosophic orientations are extremes for purposes of example. Most work situations would require a mix rather than a simplistic acceptance of either construct. Nevertheless, assumptions shape destiny; they tend to create self-fulfilling prophecies.

## Organizational norms and moral systems

Norms are acceptable standards of behavior within a group that are shared by the members of the organization. Norms define the boundaries of acceptable and unacceptable behavior. They are typically created in order to facilitate group survival, make behavior more predictable, avoid embarrassing situations, and express the values of the group. 

Each organization will establish its own set of norms that might determine anything from the appropriate dress to how many comments to make in a meeting. Organizations may exert pressure on members to force them to conform to the group's standards. The norms often reflect the level of commitment, motivation, and performance of the organization.

Performance norms determine how quickly members should work and how much they should accomplish. They are created in an effort to determine levels of individual effort. They can be very frustrating to managers because they are not always in line with the organization's goals. Members of a group may have the skill and ability to perform at higher levels but they don’t because of the organization's performance norms. For example, workers may stop working a production machine at twenty minutes before quitting time to wash up, even though they produced fewer items that day than management intended.

Reward-allocation norms determine how rewards are bestowed upon organization's members. For example, the norm of equality dictates equal treatment of all members. Every member shares equally so rewards are distributed equally to everyone. Equity norms suggest that rewards are distributed according to the member's contribution. Members may contribute through effort, skill, or ability.

Social responsibility norms reward on the basis of need. Members who have special needs therefore receive the largest share of the reward.

## Record management

Records are the information created, received and maintained as evidence and as an asset by an organization or person, in pursuit of legal obligations or in the transaction of business ( -- definition of ISO 30300 standard). Records refer to archival information and data in all forms created or received by public institutions in relation to the affairs thereof such as:

- Document, books, ledgers, cards, drawings, 
- Audiovisual material and
- Electronic documents

and, 

- Documentary art records.

Records may be available in different formats;

1. Eye readable: Paper, microfilm
2. Machine readable: Electronic records, email, digital image, audio visual
3. Other: Physical objects (artifacts)

Public records management allows to realize transparent and responsbile administration of public institutions as well as safely keep and efficiently utilize public records and, by ensuring public rights to claim of information, henceforth foster effective participation of citizens in governance. Likewise, recent e-government initatives produces many e-document and records. All of these information should be archived and preserved for the reason of legal, historical and cultural evidence. But the latter also requires different technologies, methods and practices.

Effective record management is an essential precondition for:

1. Good governance
2. The rule of law
3. Administrative transparency
4. The preservation of mankind's collective memory, and
5. Ensuring the citizen's right to information

Characteristics of authoritative records (as mentioned in ISO 30300) are:

1. Authenticity: An authentic record is one that can be proven to be what it purports to be.
2. Reliability: A reliable record is one whose contents can be trusted as a full and accurate representation of the transactions, activities or facts to which they attest, and
3. Integrity: A record that has integrity is one that is complete and unaltered
4. Usability: An useable record is one that can be located, retrieved, presented and interpreted whithin a time period deemed reasonable by stakeholders.

Some of the features of a record that make it distinct from non-record are:

- Was it created in the course of business ? Correspondence, studies
- Was it received for action ? Controlled correspondence, departmental information request
- Does it document activities and actions ? Calendars, meeting minutes, trip reports
- Does it support financial obligations or legal claims ? Funded award files (contracts or grant files)
- Does it communicate requirements ? Policies or procedures
- Are you or your unit responsible for keeping it ?
- Does it provide information regarding the historical development of government programs or people ?
- Is it required by an approved records disposition schedule ?
- Is it generated and used in agency business, but is owned by the agency ?
- Is it a reference material; reports written by other agencies, journals and newsletters ?
- Is it a convenience copy ? Duplicate copies of correspondence, policies, reports
- Is it a stock copy of a publication ?
- Is it a draft or a working paper ?

Records have lifecycle. From birth to death but, different from humans, or to permanent life. Its stages can be summarized into following major heads:

1. Creation
- Generation
- Receipt
- Capture
- Register

2. Use
- Distribution
- Use
- Access

3. Retention
- Classification
- Indexing
- Storage

4. Disposition
- Evaluation at the end of retention period
- Transfer
- Destroy
- Legal hold

5. Long term preservation
- Arrangement
- Description
- Preservation
- Migration

6. Destruction (alternative to long term preservation)
- Complete destruction
- Shred
- Degaussing

## Communication

It can be said with truth that nothing can be done without communication: orders, instructions, information, requests all have to be commu-nicated in order that action may be taken on them. Communication is a vital service that the office provides to the organisation. The efficiency with which this function is carried out has a very great bearing on the efficiency of the organisation as a whole and on its continued success.

It is necessary, therefore, to examine the factors that create an effective communication system in an organization. The communication requirements of a large provincial government authority differ radically from those of a small local level public office. Nevertheless, there is a great deal of common ground and we can therefore examine the general factors necessary for effective communication to exist whatever the circumstances. They may be defined as follows:

1. Language: The recipient of a communication must be able to understand the words used, especially if technical jargon is employed. It must also be recognised that different levels in the organisation may use different language and even think differently. An appropriate example is the use of accountancy terminology by top management to explain to workers on the shop floor why their pay cannot be increased.

2. Timing: A badly timed communication will receive less than the full attention it deserves; this includes both time by the clock and time by opportunity. A telephone call will not normally be welcome at 4 o'clock in the morning: neither will a communication be fully considered if the other party is just off to catch a flight for which he or she is already late.

3. The medium: This must be appropriate to the purpose and the circumstances. For instance, it would not be appropriate to discuss procedures of good procurement which require paperwork and pro-forma submissions over the telephone.

4. Attitude: There must be trust and mutual respect between the parties to a communication for it to achieve full and unbiased understanding. Mistrust, acrimony or prejudice between them can result in unintentional or deliberate misunderstanding.

5. Willingness to participate: Both parties must be willing to communicate or effective understanding will not flow. Often unwillingness comes about because of unfortunate attitudes that have become established in the mind of one party or the other because of past experience or because of the influence of prejudiced colleagues.

Over the past two or three decades there has been a change in workers' attitudes to their employers. In present management/worker relations there has been a move away from the old notion that management could dictate to staff and workers and expect unquestioning obedience to the idea that the cooperation of the workforce must be sought by persuasion.

Managers, including the office administrator, have an important duty to communicate clearly with their subordinates in such a manner that these workers can understand the facts being conveyed and be able to interpret them within the context of their normal working environment. There is also a duty on managers to instruct their subordinates both to carry out their everyday duties and to instruct them in new skills. How the latter is done is of extreme importance as future work efficiency will depend upon the excellence of the communication between the parties.

Vertical communication

This is the line of communication down and up the organization structure. In the past vertical communication was almost wholly downward. The top level administrative authority made the decisions and these were passed down through the various levels of management and supervision to whatever level had to implement them. This was the traditional authoritarian approach to communication within an organization.

However, modern governance system embracing standards of good governance and efficient public administration demand more than a mere giving and blind acceptance of instructions and orders. Employees at all levels are now aware of the effects that management decisions may have. The modern concept of two-way vertical communication has, therefore, developed. Not only must an organisation now provide a channel for the downward flow of communication, it must also make formal provision for a flow upwards from the shop floor to the higher levels of management.

Nevertheless, it remains true that the main vertical flow is downwards because this is the way that instructions and directives have to be given. However, suggestions, comments and objectives are now part of the accepted upwards flow.

Vertical communication can be susceptible to failure and it is important that there is an adequate system for conveying instructions, directives, information, suggestions and grievances between management at all levels and the workforce, ensuring that communications reach those they are intended to reach.

Horizontal communication

In order that the day-to-day business of an organisation may proceed smoothly there must be effective and unimpeded communication across departments between persons at about the same level of authority. Thus, the a finance officer may have to communicate with the administrative officer or with departmental technical officer. This form of communication is termed 'horizontal communication' and is a very important part of an organisation's communication system. Without it the day-to-day business of the concern could not carry on and if it is inefficient the running of the organisation is impaired.

A great of success in horizontal communication depends upon the attitudes prevailing between departments/section and particularly between departmental heads. There must be an atmosphere of complete cooperation throughout the organisation. If even only one department is uncooperative it can have a very real influence on the effectiveness of horizontal communication and on the functional procedures which depend on efficient communication.

## Correspondence (Notetaking, proposal, memoranda and report writing)

### Memoranda

Memoranda are written communications intended for internal use only. The first question to ask about a memorandum ('memo' is the popular name) is: 'Is it really necessary to write one at all?' In very many cases the answer will be 'No' because the matter could very well be dealt with over the internal telephone. All too often the memo is looked upon as a defensive device to be used in the future to avoid blame - and an expensive defence it is to the organisation. A memorandum should be used only where the absolute accuracy of the written word is essential. 

A memorandum should be brief and to the point. Brevity, however, does not mean discourtesy and the same care in quality and politeness should be taken as when a letter is composed. The matter to be dealt with should be presented in a direct fashion. Ambiguity should be avoided and the same precision in the use of words is required as in the more formal letter. A memorandum should also deal with only one subject.

In general memoranda are typed, but they need not be. In fact, it can be said to be quicker and less costly if they are handwritten by the originator. This removes the need to call and dictate to a typist who has then to transcribe and type the memorandum, which then has to be returned for signature. If the originator is provided with a pad and carbon paper it is quick and easy for the message to be written by ballpoint pen and certainly less costly than having it typed. 


### Report

According to the dictionary a report is 'an account or opinion formally expressed, after investigation or consideration'. It will be seen from this definition that a report is considered to be formal and is required to give an account of the matter covered or to state an opinion on it.

There are two main kinds of report, though not every report will fall neatly into one or other of these categories. The first is the individual report. This is usually expressed in the first person and is the kind used for internal routine reports and short reports on day-to-day matters. Examples of these are accident reports, organisation and method reports, sales reports and so on. In some cases, particularly where a great deal of statistical and other figure information is included, a standard form is used so that variable data only has to be entered in the same way as in a standard form letter.

The second type of report is the general report. This is more formal than the individual report and is generally written in the third person, though this is not always the case. Such reports are frequently composed for external or public circulation and are often quite voluminous. Official reports of this nature sometimes run into two or more volumes bound in book form, with extensive indexes.

### Basic rules of report writing

There are basic rules that underly all forms of report writing, which do two things. First they ensure the logical construction of the report and second they assist the writer to present the report in an accepted format. These rules may be summarised as follows:

1. Should have a title
2. If addressed to a specif person or a specific body of people, should begin with salutation.
3. Any but a very brief informal report should begin with a statement ofvthe terms of reference.
4. An introduction to the body of the report is usual.
5. The body of the report should explain the nature of any investigations carried out, facts discovered and should put clearly and succintly the arguments and opinions, arising from the investigations.
6. Long reports should be broken down into sections with headings to guide reader.
7. The conclusions are normally required.
8. Report should be signed and dated.
9. Whenever the report is of a meeting, the names of those present should be given at the head.
10. Frequently parts of a report will be supported by graphs, tables of statistics and other similar data. It is usually recommended that such matter form an appendix or appendices.
11. A lengthy report should always to be accompanied by a table of contents.

## Office monitoring and evaluation

### Inspection

### Monitoring

## Management information system

\begin{questions}

\question How does the management information system help in decision making process ?

Management information system (MIS) is an information system used for decision-making, and for the coordination, control, analysis, and visualization of information in an organization.

In public governance, MIS are the tools to promote transparency, accountability and participation. More specifically, recent approaches to delivering bureaucratic services are expeceted to meet their goals of public orientation and result based performace evaluation aided through information system. Establishment of computerised Integrated Financial Management Information System (IFMIS) is being mulled over to implement single platform central accouting system as a part of a public finance management reform initiative by Government of Nepal with support of World Bank. For example, under this system information about expenditure made by the Department of Roads and the revenue collected by the Inland Revenue Department will be disseminated via the same platform. Also the concept of digital National Identity Card based is a part of broader vison of government, currently under delegation of the National ID Management Center (NIDMC) under aegis of Ministry of Home Affairs, to aggregate vital information database of the citizens.

In a corporate setting, the ultimate goal of the use of a management information system is to increase the value and profits of the business. This is done by providing managers with timely and appropriate information allowing them to make effective decisions within a shorter period of time.

While management information systems can be used by any and every level of management, the decision of which systems to implement generally falls upon the chief information officers (CIO) and chief technology officers (CTO). These officers are generally responsible for the overall technology strategy of an organization including evaluating how new technology can help their organization. Once decisions have been made, IT directors, including MIS directors, are in charge of the technical implementation of the system. Upon implementation, the assigned users will have the appropriate access to relevant information. It is important to note that not everyone inputting data into MIS need necessarily be management level.

The role of MIS in public and private governance is further invigorated by widespread networking facilities made possible through internet. There are also multiple cases of MIS platform sharing across multiple business centres to benefit from cross enterprise information exchange.

The MIS represents the electronic automation of several different kinds of counting, tallying, record-keeping, and accounting techniques of which the by far oldest, of course, was the ledger on which the business owner kept track of his or her business. Automation emerged in the 1880s in the form of tabulating cards which could be sorted and counted. These were the punch-cards still remembered by many: they captured elements of information keyed in on punch-card machines; the cards were then processed by other machines some of which could print out results of tallies. 

Waves of innovation spread the fundamental virtues of coherent information systems across all corporate functions and to all sizes of businesses in the 1970s, 80s, and 90s. Within companies major functional areas developed their own MIS capabilities; often these were not yet connected: engineering, manufacturing, and inventory systems developed side by side sometimes running on specialized hardware. Personal computers ("micros," PCs) appeared in the 70s and spread widely in the 80s. Some of these were used as free-standing "seeds" of MIS systems serving sales, marketing, and personnel systems, with summarized data from them transferred to the "mainframe." In the 1980s networked PCs appeared and developed into powerful systems in their own right in the 1990s in many companies displacing midsized and small computers. Equipped with powerful database engines, such networks were in turn organized for MIS purposes. Simultaneously, in the 90s, the World Wide Web came of age, morphed into the Internet with a visual interface, connecting all sorts of systems to one another.

Midway through the first decade of the 21st century the narrowly conceived idea of the MIS has become somewhat fuzzy. Management information systems, of course, are still doing their jobs, but their function is now one among many others that feed information to people in business to help them manage. Systems are available for computer assisted design and manufacturing (CAD-CAM); computers supervise industrial processes in power, chemicals, petrochemicals, pipelines, transport systems, etc. Systems manage and transfer money worldwide and communicate worldwide. Virtually all major administrative functions are supported by automated system. Many people now file their taxes over the Internet and have their refunds credited (or money owning deducted) from bank accounts automatically. MIS was thus the first major system of the Information Age. 

Advantages and disadvantages

The following are some of the benefits that can be attained using MIS:

\begin{itemize}
\item Improve an organization's operational efficiency, add value to existing products, engender innovation and new product development, and help managers make better decisions.
\item Companies are able to identify their strengths and weaknesses due to the presence of revenue reports, employee performance records etc. Identifying these aspects can help a company improve its business processes and operations.
\item Giving an overall picture of the company.
\item Acting as a communication and planning tool.
\item The availability of customer data and feedback can help the company to align its business processes according to the needs of its customers. The effective management of customer data can help the company to perform direct marketing and promotion activities.
\item MIS can help a company gain a competitive advantage.
\item MIS reports can help with decision-making as well as reduce downtime for actionable items.
\end{itemize}

Some of the disadvantages of MIS systems:
\begin{itemize}
\item Retrieval and dissemination are dependent on technology hardware and software.
\item Potential for inaccurate information.
\end{itemize}

source: \url{https://www.inc.com/encyclopedia/management-information-systems-mis.html}; \url{https://en.wikipedia.org/wiki/Management_information_system}

\end{questions}
