# Essays and opinion piece

## Governance

### Shift to Poly-centric governance

The concept of governance has emerged from the incubus of neo-institutionalism following non-performance of formal institutions, lean state defended by neo-liberalism and the surge of new public management. They all treat the lumbering state as a burden and democracy as a means of selecting leaders to govern. Governance is about the exercises of power by a network of actors for the proper disposition of public affairs and rational distribution of normative and material public goods which are institutionally embedded. Nepal's stable future rests on the concertation of the nation's diverse actors' sphere of competence for the creation of a good society. Balancing rival interests and setting the congruence of Nepali state and cross-national dealings of its societal actors underlie their efficiency.

Tension arises when one actor clocks the other's choice and denies the public access to policymaking flaking leaders' will to respond to problematic situation and sapping its vital authority to set Nepali aspiration of nation-building and stress of global geopolitics in a balance. Democratic rule can improve framework condition by equal treatment of people and by cutting trade-offs between economic growth and equity, popular aspiration and constitutionalism and political ideals and human condition.

For long, bad governance hanging around the state power in Nepal pushed the nation in the backwater and frozen the public hope of prosperity. Good governance assumed vital importance now for the nation's recovery from disorder, disruption and illiberal fiddling. A critical factor shaping the performance of Nepali governance rests on its ability to mend the society's web and steer public and private institutions for the promotion of public welfare. It presumes Nepali leaders to recapture their long-abandoned policy sovereignty and revive parliament's right and the state's authority to execute constitution, strengthen local structures and manage social change.

It is equally important to coordinate donors' multi-purpose and multi- directional governance projects for "policy coherence" and their harmony with national priorities. Both can capacitate local bodies with the ample supply of civil servants, money, technology, infrastructures and co-ordination works. But, as long as partisan distribution of constitutional and other public posts endures, stable balance in provision and production, exchange and distribution, supply and demand, import and export and business profit and human life remains an uphill task. Public interest orientation demands the embeddedness of governance in society while synergy of progress entails renewing civic virtues from the bottom-up.

 Paradigm shift: The associational revolution shifted the power and authority of mono-centric government to poly-centric governance. Three key poles of governance are the state, market and all intermediary institutions, networks and movements lumped as civil society governed by diffused interests. The success of their tasks rests on communication and coordination of diverse choices. A shared rule where each supports the other's competence averts anarchy. Nepali government as an executive wing of state deals national "politics" and represents its imperatives. The governance is de-territorialised reflecting diverse interests acting across multiple spheres of "policy" including parallel set of international regimes of which the nation is a member. Causes and effects of creed, greed and grievances of regional and global in scope, however, cannot be dealt by the Nepali actors only. Solution entails multi-actor collaboration in the life-world and shared benefits.

The duty-based organic civil society of Nepal, imbued with rich social capital, is desired to offset the utilitarian impulse of politicians and businessmen and fix all interests in the middle path through their optimization. The reawakening of public sphere can modify individual preference and set new checks on power above Nepali state's institutional complex- the axis of legislative, executive and judiciary authorities. But the self-ironies of right-based civil society and NGOs have reduced them in the margin of power lacking conduit to influence authorities and turning their misdeeds a high cost venture. Business sector of Nepal, however, possess high leverage as they finance politicians, influence policy, skew economic decision and gain illicit benefits using instrumental criteria of efficiency.

Goals and principles of governance: Governance is an array of goal-oriented policy processes, such as national security for the creation of a relatively safe environment, rule of law, voice of people and their access to justice, civic participation in social and economic life, delivery of public goods and conflict mitigation. Securing the dignity of Nepali people requires cohesive promotion of these goals. Governance can become effective if economic activities are organised around these goals, social, economic and political actors become conscious of their duties, acquire contextual learning and behavioural change. Nepal has accepted civil society, ancillary organs of political parties, local federations, etc. as legitimate actors to bring the voice of public in policy making.

Nepalis' power to self-organise and converse their interests rests on civic capacity of mediating bodies to supply soft power of ideas, lower the cost of cooperation and enable the leaders to grasp the state's potentials such as strategic geography, hydropower, youth population, tourism, cultural capital and heritage of tolerance to plan the nation's long-term future. An effective response to the demands of people and those of outside actors is crucial for the adaptation of all national actors-security, power nexus, regulatory, elite circulating, integrity maintainer, cultural industries and institution of production and circulation enabling them to get along to changing global political economy. Too much party-mindedness of top leaders has, however, battered the efficacy of public institutions in Nepal while impunity stained financial discipline, tax, tariffs and foreign aid aimed at filling saving, investment and foreign exchange gaps. 

Solution of Nepali people's many problems calls for collaborative efforts at multi-actor levels on the background of the post-conventional ethics of governance whose cardinal principles are: legitimacy, integrity, transparency, accountability, efficiency and equity. Each element presumes the other to complement, not compete and counter. Civil servants, planners and political leaders of Nepal are accountable for their policy choices and the course of actions because they are charged with the tasks of service delivery. People judge whether the power is rightly exercised and legitimate order is attained for the promotion of mutual gains. This can minimize free-riders, corrupts, criminals and conflict actors that flourish in predation, economic monopoly, capital flight, syndicate and patronage depriving the common Nepalis of a chance to rise socially and use their sovereignty. Means of governance are as vital as goals and values. Order can exist without justice but justice cannot be attained in a power vacuum and public order deficit.

Art of governance: The art of governance assumes: consensus-orientation of actors, information exchange among them, policy coordination, coherence of behaviour, feedback, steering national policies and collective action. As a nation caught in diverse hierarchy, Nepali authorities need multidisciplinary skills to cope with pressures and claims from "insider" groups such as bargaining union of civil servants, elected authorities, several inclusive commissions, national human rights commission and federations to various "outsider" groups such as business chambers, ethnic associations, class organisations, women's movement to human rights NGOs, which as right-based bodies, demand Nepal's consistency to universal standards. Beyond constitutional duty of collective identity of citizenship, they converse on global values flouting national roots of enlightenment. Self-organisation of these groups in Nepal has enlarged their capacity for collective action.

A correct disposition of power in Nepal requires coordination of all constitutional bodies, private sector and civil society, orient them to constitutional spirit and beef up national integrity system so that costs for deviants are high than compliance to rule. Since Nepal's discourse on politics, power and policy is gaining attention, learning about the tasks of federal, provincial and local bodies is crucial to ramp up the their capacity to deliver public goods to the people. Nepali think tanks should focus on policy networks instead of being fixed on the structure and powers of state agencies while leaders must pay attention to the demands of people, lobby for their interest, support governance goals, check the illicit behaviour of those in power and uphold due diligence on corporate power so that they don't corrupt lawyers, economists and journalists in defence of supply-side economy which sets the social equity subordinate to the control of powerful interest groups and coils the self-correcting device of democratic governance.

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/21234}

### Governance Transformation

Nepal is in the midst of a great transformational moment brought by an opportunity to compete, collaborate and connect with various scales of actors. Institutional restructuring of national and local bodies, mobility of vast number of labour force abroad, adaptation to modern technology, urbanisation, globalisation and climate change are drivers of transformation. The new narrative in Nepal is happy life, prosperity and stability. The self-rule of local governance structures in Nepal is the foundation to realise this vision. It is relatively autonomous with new types of civic, legislative, executive and judicial authority. The electoral politics of middle path is opened to reason and resolution of conflicts from the bottom up where women's leadership is predominant.

The Constitution of Nepal has authorised Gaunpalikas and municipalities to direct, control and conduct their own affairs and assume roles on education, health and sanitation, safe drinking water, communication, agriculture, irrigation, industry, animal husbandry, upliftment of woman and targeted groups, right to collect reasonable tax and engage in infrastructure development, planning, monitoring and evaluation, etc. Wards are the lowest units having a strong sense of caring community and shared identity that spawns democratic leadership, citizenship duties and governing. The new transformation in the structures, functions and roles of local bodies has, however, stifled the performance of elected local bodies owing to learning by doing approach. The ties between the federal, province and local levels are based on the principles of cooperation, coexistence and coordination. They are vital to settle the contending interests between the provinces and the local bodies, attain the transformation of the nation from poverty to welfare and prosperity and create civic culture worthy of Nepalis' civic heritage.

The hope of Nepalis from the local government is stifled by delays in many areas: adjustment of civil servants, required laws by federal and provincial governments, physical infrastructures, determination of local tax and skilled personnel for governance. The normal functions and service delivery in remote areas are stymied by the absence of civil servants, their low morale and increasing partisan prejudice. The Ministry for Federal Affairs and General Administration unveiled that local bodies need 37,000 civil servants which it is fulfilling through a fast track method of Public Service Commission exam. The State Affairs and Good Governance Committee of the parliament pointed out the inability of civil servants to adapt to political changes suggesting their transparent work evaluation and accountability to the tasks.

Absence of laws to regulate shared rights and jurisdiction of federal, provincial and local bodies punch their responsiveness. Restructuring of many Gaun Palikas and municipalities and merger of many local units expanded their sizes and devolved many district offices on functional areas without infrastructural preconditions and the scale of public economy. The District Coordination Committee faces difficulty in coordinating diverse local actors in matters of balanced development. Expansion of local infrastructures spurs economic growth, employment opportunity, cut poverty and widen the access of marginalised citizens in development outcome.

Economic modernisation and institutional set-up in the rural areas drive spatial diffusion of growth of small enterprises based on locational advantage and dispersed resource potentials- hydro, tourism, herbals, agriculture, animal husbandry, etc. To add stimulus to employment generation Prime Minister Employment Scheme offers a conditional grant of Rs. 10 million to local bodies and set the guidelines to the targeted youths in addition to other grants from National Fiscal Commission, Local and Federal Consolidated Funds defined as conditional, special, complementary and financial equalisation and provincial aid set to unleash rational progress.

The Nepali government has issued a directive to set up good governance committee at local level, aiming to represent functional interest groups of society in public deliberation on integrated development planning - setting priorities, public hearing, formulation of plans and programmes, budget allocation, operation and monitoring and evaluation of development in a transparent, judicious and accountable manner. A rational planning can ensure livelihood and uplift Nepalis' standards. Local elected bodies are largely inclusive in terms of representation of woman, Dalits or minority groups and hold transformatory potential in politics as it discards the caste, class and gender walls that subordinate one Nepali to the other. The representation of local functional interest groups such as chamber of commerce and industries, civil society, NGOs, trade unions, human rights bodies, Consumer Groups, journalists and voluntary associations can make them more deliberative in democracy, shape civic habits and build multi-scale interface transforming inherited rural society into self-chosen one.

They are critical mass of transformation and checks and balances of power. The locally elected chief coordinates the functions of Good Governance Committee. The authority and legitimacy of local government springs from elections. But there are non-government, semi-government, federations, cooperatives, civil society, business, voluntary and non-elected ones whose dominant culture is social inclusion, mutual aid and solidarity and whose decisions on functional areas affect the lives of Nepalis. Therefore, optimisation of interactions among them can improve the level of engagement and commitment in performance in the politics of common good and steer their tasks performances. In others, committee system has to be mobilized to build their capacity to effectively deliver.

The sovereignty of Nepal lies in its citizens, therefore, their participation in local decisions affecting them has become the fulcrum of democratic governance. The rationale of this good governance committee is to foster ethically designed governance, make service delivery people-friendly, organise inclusive deliberation of multi-stakeholders providing them ownership in the policy and share global knowledge, skills and technological innovation thus lowering the costs of transformation.

Since the habitat of politics is the state, Nepali political leaders need to take initiative to resolve the maladies of local bodies: tussles between chair and vice-chair persons, ineffectiveness of judicial committee on dispute settlement, corruption, abuse of public budget to buy luxury items, ineffectiveness of monitoring committee, etc. affecting the distribution of social security benefits and hampering development. These maladies ruin financial discipline and integrity and weaken the social contract. Election of contractors, middle men, owner of dozer, NGOs, businessmen, etc. cultivate predatory practices for collusion with technocrats to gobble up resources abusing the virtue of political power against the vices of structural injustice.

Legislators' interest in the executive domain of constituency building fund and lobby to increase the amount from Rs 40 million to 100 million for each legislator than legislation making has cut the development prerogative of local government, fostered patronage and made Nepali parliament weak to sustain power balance. The abuse of this money spoils the civic spirit. The increasing municipalisaion of Nepali society is shifting the migration pattern from rural areas to urban nodes and abroad. It is opening economic innovation, newer settlement, occupying newer lands and management for livelihood. This is transforming the scale of politics and the public spheres creating opportunity for social mobility and mixing clan-based community into syncretic one with better life with modern amenities.

This has produced a hybrid poly-culture but created difficulty in retaining youth force to rural households vital to lift transformed life. In the hills social cost of migration is huge. Only women, elderly people and children are left for subsistence farming. A strategy for alleviating misery through the modernisation of means of production through the use of macroeconomic tools of planning intervention is must to enable Nepali society to adapt to new age of acceleration. The egalitarian vision of Nepali Constitution incarnates social justice as a trait of transformation. It opposes cultic honouring of leadership with a heavy load of garlands in the public affronting the concept of popular sovereignty. The key challenge of Nepal's local bodies is effective governance especially in service delivery to improve the image of democracy and build trust among ordinary citizens, elected authorities and civil servants. This trust is central to improve the living standards of Nepal is affirming that democracy is better than any other type of polity.

Here provision, production and policy functions on exchange of public goods and distributive justice are vital to ignite social spirit of Nepalis as a basis of civil society and set the primacy of law over the privileges of elites flourishing in impunity. Without economic discipline it is difficult to bridge the gap between lofty ideals of local democracy and its outcome for the ordinary citizens. Democratisation of political, corporate and bureaucratic instinct of utility maximization and motivating them to respond to the aspirations of Nepalis can cut social vices, foster civic culture and liberate economic conclaves controlled by a few families against egalitarian spirit.

Sustainable progress demands common commitment of federal, provincial and local governments on basic public goods such as management of ecology, security, rule of law, health, education, food, clothing, voice and social opportunities to participate in public affairs, proper utilisation of dispersed natural resources and use of new technologies for inclusive transformation. Local production of essential needs through the modernisation of agriculture especially improving seeds, irrigation and investment in fertilizer factories, productive employment in diversified enterprises meeting the home market and import-substitution that can replace imported goods can enhance transformative prospects. Nepal's adaptation to climate change needs creating local institutions that monitors the undue abuse of nature, participation of local citizens and local management of natural resources linked to both livelihood and ecological resilience.

The laws endow responsibilities to local bodies in disaster preparedness, mitigation to resilient rebuilding. Local party leaders with their vital links with central and provincial politicians, civil servants and civil society can help build consensus on democratic progress, work for the outreach of programmes to targeted groups, build legal awareness of elected representatives, protect public property and fill the vacuum created by the dissolution of Local Peace Committees for durable peace. Representative political institutions and those functional interest groups constituted by citizens themselves must embody democratic accountability where no one blocks the collective action on public interest while facilitates the service delivery. Local democracy can take roots if coordination among the actors and institutions towards the goals of local governance musters the synergy of all actors of governance in the transformative prospect of better life.
 
Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/31321}

### The Essence of Freedom

The desire of human soul for aham asmi, liberty, freedom and emancipation, is an age-old and vitally attractive pursuit. It has embellished consciousness in both inner and outer spheres of life. Philosophical literatures describe the multi-dimensionality of human life and study of entire spectrum reveals how human freedom is constituted and vital for democracy, development and peace and why citizens need freedom to do what is morally just and right. Modern interpretation of life is self-defining, self-expressing and self-articulating, an end in itself, not in reference to only cognitive and affective bond with the nation, polity, parties or leadership. The history of citizens' struggle for freedom helped overcome their subordinated status. In this sense, freedom is intrinsically linked to equality. It is used to deconstruct and reconstruct human labor, society, political parties, polity and the state to set out for promised harbor of human dignity. Freedom is a condition whereby citizens uphold the power to think, speak and act as per the use of universal reason as a sovereign subject and change the society in a desirable course.

Rights-based political culture, however, only helps organised groups of society. Nepal's society, economy and polity are mainly informal and unorganised and, therefore, realisation of their constitutional rights is a necessity for freedom. This means informal society of Nepal must have equal access to the institutional resources of the state, private sector, civil society and international regime. Law based on public reason provides Nepali citizens to question the irrational aspects of human conduct and enable them to communicate problems in the public sphere and exercise legislative power via democratic will. The use of freedom in the life of Nepalis rests on their capacity of self-learning and reflection about the condition of life, organisation--building for solidarity and engagement in a shared public action not just in the spheres of production, consumption, exchange and distribution but also in the sphere of sustainability of nature and stable functions of life. The rational spirit of enlightenment alone is not enough if it does not harness long-term survival strategies, espouses a canon critical of the domination of life-world and awakens Nepali citizens to the integrity of its national culture. The ability of Nepali nation and citizens to compete in functional universality can enlarge the domain of freedom beyond constitutional state and animate the greater visibility of national life.

Full-scale operation of self-governance in Nepal can add to collective freedom while real separation of powers can give more autonomy to judiciary, media and civil society to protect freedom of citizens. Active citizenship based on a strong conscience helps them to become autonomous whereby intrinsic good sense disciplines blind passion of elites for the domination of non-elites through the instrumental use of reason. The concept of citizenship is based on holistic sense of membership of Nepali state and cannot be reduced to only a caste, class, gender, consumer, voter or labor dimensions that relativize the sovereignty inherent in them, compress the areas of national sentiment and limit their freedom. Active citizenship liberates them from feudalism, dynasticism, tutelage, negation and subordination and even ideological indoctrination which smacks of determinism and nauseating conformity, not the cultivation of freedom. It has splinted educated Nepalis in public debate suppressing the real birth of informed public opinion. The symbolic representation of adversarial politics in Nepal defined by a code of friend and foe where political power is utilized for more power in a vicious way has created a situation of perpetual anomie resulting from modernity's loss of social compassion. The inclusiveness of ideology alone can reduce the prospect for binary conflict and breathe the aspirations of Nepalis for freedom. Citizenship in Nepal presumes the extension of democracy in every sphere of life. Gautam Buddha and Immanuel Kant have rightly argued that human beings cannot be reduced to other human beings' means. Both define the concept of freedom in inner vigilance and middle path encapsulated in a moral balance between individual liberty and public duty. It is expected to revive the hope of moderates from anomaly.

In a pluralistic society like Nepal, freedom is naturally norm and law-bound, not anomic and lawless which leads to an anarchy of free wills of powerful interest groups and cuts the ability of citizens to achieve fulfilling life. For citizens of Nepal freedom is not only inherited from its history to assume present constitutional goals but also of the goal of the future society as well in response to the ever-changing social stratification and social division of labour brought by technology, self-transformation from pre-rational to rational being, Nepal's constitutional ideal of social democracy and humanitarian obligations. The source of freedom, however, rests on an awareness of constitutional and human rights and duties and lifts the burden of scarcity. This implies that acculturation in a culture of freedom seeks a harmony with the principles of democracy which provides adequate opportunity for participation, liberation of productive forces of Nepali society and self-management of economic enterprises. This can address the problem of swollen unemployment of Nepali youths who are driven to different destinations to meet their necessity.

Lawless freedom stokes the virtue of strong which corrodes legal and institutional constraints on their behaviour, weakens the ability of Nepalis to live together in peaceful existence and satisfy existential needs of all. This is why Nepali constitution is designed to control the tyranny of majority and confiscatory form of distributional struggle of minority through a system of property rights. The Constitution supposes freedom based on the foundation of citizenship equality and protective and promotive form of social justice and positive discriminations. Both the concepts are supposed to create an egalitarian society in the public sphere, a sphere where unreasonable use of power and wealth is criticised for reforms and the power of civil society, media and constitutional bodies are utilised for the rationalisation of Nepalis' life and public institutions. But to achieve this, the institutions of enlightenment must be public, broad-based and impartial which can be a passport for material prosperity. The immunity rights of Nepali citizens are couched in negative freedom which limits the authority of regime. A rough sense of equality rests on fulfilling existential needs of Nepali citizens and aspiration for freedom specific to democracy so that they are not dictated by what Karl Marx calls daily "necessity" for survival, "alienation" from their own products and "exploitation" by powerful elites using coercive means, policies and institutions. For Buddha and Marx, freedom requires the abolition of structural injustice and creation of an equal chance for all. Freedom erodes when leaders have conflicting ends.

Freedom espoused by Nepal's constitution is not libertarian in nature which seeks to weaken order-creating structures, nor classical socialistic one where the state controls individual freedom and commanding height of entire political economy but of social democratic in nature-where freedom is accompanied by accountability to social justice. It is here popular sovereignty and the state sovereignty finds a judicious harmony. It is possible only in a welfare state that socialist ideas can catch on, not in a rentier or extractive state, as it does not formulate policies as per constitutional spirit. But Nepalis must have the ability to exercise their inner conscience and outer form of constitutional rights without any dictation and manipulation from others. The history of Nepal symbolises eternal struggle of Nepalis for personal and national freedom of will and recognition. Nepali constitution does not intend to totalise and homogenise entire social and cultural diversity of the nation but recognises the unity in diversity, where each requires accepting the others and supporting them in the alleviation of their suffering. It enhances the domain of freedom for the oppressed. Poor Nepalis cannot exercise freedom if their condition of labour, life, education and institutions remains untransformed and identity is based on contradiction rather than common background condition of multiple identity groups to live with shared Nepali nationality and become aware of the social and spiritual links. Democracy cannot become functional if its intrinsic parts are weak and uncoordinated to act in the general will of Nepalis. The corporate structures of the state administration, business and civil society in Nepal need integration to the spirit of national public life. Liberation of Nepalis' potential is a key to their participation in national life and gain access to channels of appeal, attention and purposeful action which elevates upland of freedom.

Absence of preconditions for freedom creates a condition for the uncertainty of ordinary Nepali life. Modern mind is, therefore, engaged in the pursuit of vigilance, deliberation, participation and public action. The availability of positive freedom (good life) is highly correlated with sound human development index where Nepali leadership has to struggle hard to improve the better quality of life of citizens and higher level of freedom. Negative freedoms are related to non-intervention by the institutions of coercion. Nepalis can be better off if safety, wellbeing and choices are guaranteed. Socially satisfied citizens can enjoy good life-choices and generational mobility and reciprocity. Better existential condition can enhance the prospect of freedom and make life meaningful and exciting. Liberty and emancipation are not only matters of the left and the right politics in Nepal. Both should aim to address the hierarchy of human needs, rights and concerns and remove fatalism and reaction as per the constitutional spirit.

Democracy and modernity have unleashed many emancipatory ideals- rights, freedom, justice, solidarity, eco-balance and peace. They are changing the value complexes of Nepali society prompting citizens to demand an end to the utility of mindless violence in politics. This has many sided effects in Nepali society from family life, child rearing, education, health, care economy to the humanisation of multi-level governance. The constitution of Nepal aims to bridge the gap between the ideal of freedom and reality of scarcity of public goods. The political life in Nepal is, therefore, hovering around domination and contestation for the creation of a rational public order that includes the free and equal participation of Nepalis in the institutional life of the nation and experience a new lease of life.

### Development governance

The sole objective of Nepal's development strategy has been to set forth as to achieve prosperity, development and happiness of the people within a short span of time. The prime minister, ministers and political leaders are all harping on the theme of development, prosperity and happiness time and again. Prime Minister KP Sharma Oli has made a repeated plea to the investors to put in their resources in the development of the country. Whether in Davos or other forums the prime minister does not fail to articulate his vision of development and prosperity and argues that the country has all requisite infrastructures and guarantees for investors to put in their capital and technology.

However, the aspiration to achieve prosperity and development does indeed rest on the capacity to generate and mobilise resources and utilide them efficiently and effectively. A casual appraisal reveals that the country's capacity to implement development projects is very poor characterised by low utilisation and miscarriage of the resources. This is clearly mentioned in the report presented by the Public Expenditure Review Commission (PERC) the other day. This has resulted into shortfall in achieving the developing target. This has also engendered low and shrunken outcomes in building infrastructures and physical assets critically needed for the development and prosperity of the country.

Several projects which are glorified as the projects of national pride are allowed to languish in tatters. Whether it is airport, road, hydropower or irrigation constructions, no projects have been completed in time. They incur exorbitant and escalated cost overruns. In order that our development projects are completed in time and make planning process more viable and result oriented, it is essential that our capacity to utilise resources is bolstered and project development and implementation governance is fully set right. Needless to say, in the least developed countries like Nepal, economic planning is the tool for development. Economic planning has been used in Nepal for the last several decades.

The philosophy of the economic planning can be broadly categorised into two types -- indicative planning and imperative planning. The Indicative planning is mostly used in the countries where free market economy has been adopted. The indicative planning sets the targeted rate of growth for the economy as a whole for a specific period of time. In this type of planning role of private sector, civil society, cooperatives and other development partners is considered to be important where state plays the role of a facilitator and enabler. On the other hand, imperative planning is a fully state administered and guided kind of planning. This kind of planning functions within the hierarchical framework of state machinery. This was more popular in the socialist countries like the dissolved Soviet Union introduced by communist leader Joseph Stalin and continued till the fall of communism in the dissolved Soviet Union. But modern China has made innovative adaptation and used this method of planning very successfully. But now this type of planning has been more or less abandoned. Nepal follows the mixed type of planning process where the role of the public, private, cooperative and civil sectors has been recognised and valued for development. However, it is generally agreed that a development planning process should start with perspective plan. The perspective plan embodies an assessment of the country's long term development outlook and broader goals. Then the perspective plan is followed by the periodic plan. The annual plans and projects implement the targets of the periodic plan. The total activities of the government should elaborate and reflect in the planning document.

Nepal has already implemented more than a dozen periodic development plans and projects. The review conducted by the government has shown that the most of the plans could not achieve their targets. The reason why plans for development fail in Nepal is typically diagnosed by the Swedish economist Gunar Myrdal who had earned reputation worldwide for reason of his famous work called The Asian Drama. He mentioned that poor technology, underdeveloped institutions for enterprise and development, imperfections in the authority of the government, centralised governance system, corruption, low efficiency and poor standards of integrity in public administration have been the major impediments affecting the implementation of development projects in Nepal.

With a view to address some of the issues and challenges pointed out above, Nepal embarked upon the moves towards instituting decentralised development planning process so that the local development projects are executed efficiently. However, the decentralised planning process has been totally disrespected. The overlapping and duplication of the federal, provincial and local level projects as indicated in the PERC report speaks volume of the centralised mindset in the planning process. The big sorts in the decision making level and powerful politicians control and sideline the defined statutory planning process and plan their own pet projects to support their respective constituencies.

Prime Minister Oli and leaders like Prachanda are not an exception to it. As mentioned above, planning process has been rendered completely dysfunctional in Nepal. It is not only centralised but also personalised. The political leaders, bureaucrats and those who can dictate and manipulate the official channels can make the planning wheel move as a consequence of which projects are misallocated and resources are misused in larger proportion.

In theory, Nepal has adopted the bottom up planning process sanctioned and validated by the federal constitution. But the whole process has been turned into mockery allowing the crafty politicians and rapacious bureaucrats to meddle fully in the planning mechanism and system. Unless the whole planning system is revamped, reoriented and project governance system reformed in the true spirit of federalism, Nepal's development trajectory is not likely to take off and move upward.

### Note on constitutionalism

Constitutionalism refers to the rules of fair governance. As a vital element of democratic order, it lays the design of a polity central to power distribution, its ties with the state's institutions and citizens and code of conduct to coordinate a variety of goals in many realms. Aiming to place rule of law, it sets the normative standards of society to balance between freedom and authority, politics and law and rights and duties of citizens and the state. Constitutionalism averts the tyranny of majority by the wheels of public reason. It limits the rulers' authority by placing checks on power and creating autonomous legal safeguards to protect minority. It deters the confiscatory sort of distributive struggle of minority and social movements and forestalls both democratic decline and relapse into despotism. Democratic constitution aids the poor by social policies, taxing the wealthy and devolving resources so that they abide by the rules of game. Embodying political realism, constitutionalism sets a process of gaining, using and transferring power and subjecting vital matters to judicial review. Adjudication means nothing if court's verdicts are prejudiced screwed or non-carried out. It splits law from the integrity of ethical life.

Burden

The ritual of extra-constitutional path of regime change in Nepal has, however, imposed a huge burden on political stability and national affinity of citizens. It has muddled the constitutional which may be lucrative for a slew of legal elites who know how to exploit the flaws of human nature and devour the weak by due process of law. Awareness about injustice can easily recharge the battery of estranged groups to spiral their struggle against the natural selection of life to a higher plane of global consciousness and draw international jurisdiction to act. Nepal's constitutional practice has, however, saw the primacy of power equation over norms, values and cultural wisdom cutting the unity of political life with the state. Conformity with constitutionalism can make Nepal better governed. But it will not make Nepalis happier unless quality of life improves.

Trapped in web of power than the reason of constitutionalism, Nepali leaders failed to tend law-based conduct of citizens prompting the alienated to indulge in stir and ease the collapse of one Constitution after another. The Constitution of Nepal 2015 has experienced a thorny delivery though it added more rights to citizens and was endorsed by a vast number of legislators. It faced a strong resistance from Madhesi parties while India had tied itself with the UK and the EU to oppose it for not being amply "inclusive." It unveiled that Nepal's post-conflict order has substituted one type of conflict by the other finding the constitution no immune from geopolitical infection. The discrepancy in normal politics and huge promises in the constitution and incoherence of its various parts and unlawful behavior of elites have burdened it with infinite tasks beyond the capacity of the state to carry. As a result, political game is pivoted on who should control power, not settle peace, justice and progress. Evolved as a compromise text of fractious political parties-NC, Maoist-Center and CPN-UML- the constitution faces a clash between norms and facts. The spars of radical left, social movements, armed actors and right wing, blinded by their politics, can be harder to extirpate if leaders defer demands and amend the constitution without caring its effects. Without all actors ensuring a stake in the polity, the constitution will continue to face extra-constitutional challenges.

Nepali constitution embodies scores of democratic values for the creation of an egalitarian society. But it failed to pull away from the pack of multi-caste, ethnicity, gender, religion, class or territoriality to catch its own legacy of enlightenment. As a power map for shared rule, constitutionalism reflects the national goals and course. Discursive production of law is enduring. It allows the inclusion of interests and values of all sides. Nepal's constitutionalism is, however, facing a tension between those seeking to amend the Constitution and those finding no rationale for it, bargaining for interests and sharing values, and constitutional spirit of socialist-oriented economy and the reality of corporatism. A major shift has occurred in Nepal as law is finding resonance in popular sovereignty, albeit the tensions between economic dependence and independence, secularism and multi-religious society and equality of citizenship and reference to multiple castes and races. Democratisation process propelled by citizen equality is hamstrung by a politics of difference. So long as civic engagement revolves around personalised leadership, the separation between the public and the private sphere remains blurred and issues are settled less on the basis of constitutionality than the fallacy of legal logic. In such a context, constitution fails to become a safety valve and arbitrator of rival forces signifying a shared common good. Nepal's constitutional peril is that proportional representation will always create a patchy legislature given its plural electorate and executive will chronically suffer from a game of musical chair. Acculturation of leaders into its ideals can reshape democratic thinking and habits. The civic roots of its culture are conducive to constitutionalism as they prized justice at multi-sphere to maximise citizens' happiness.

The declaration of secular, federal democratic republic, social inclusion, proportional representation and gender justice helped Nepalis to redefine their social ties contesting what is undemocratic in its political culture. Democracy, as a bottom up process, presumes the self-liberation of citizens. Elected bodies are its laboratory. Engaged citizens see the prospect for: social representation, the the rise of network politics, contestation of the boundaries of majoritarian democracy, and the universalisation of human rights through the legitimacy of international obligations and constraints. Their constitutional awareness is vital to fortify engaging culture, make leadership accountable to social contract and nurture a culture of compromise between the politics of opposites and control wild appetite for arbitrary action, cronyism, impunity and corruption hostile to criminal justice system. If Nepal's macro institutions uphold national integrity and constitutionalise societal institutions they can defy entropy and make constitutionalism a self-binding ideal. But if the leaders and legal fraternity feed each other they can subvert its virtue. The challenge in Nepal is how to foster legal culture driven by public reason.

Constitutionalism entails reforming bleak economic basics and giving Nepalis a choice in the life's process, not only the unequal exchange of its labour for capital whose social costs stay howling. Given Nepali parties' manifold inclinations leadership consensus at the top remains fragile to address power dynamics and moral atrophy which bend the values of constitutionalism. Business penetration of politics and political penetration of bureaucracy mar its spirit to balance the interest of class and the mass in policy matters. Nepal is suitable for a culture of constitutionalism but undue passion of mini-identities requires optimisation. Its roots of civility provided Nepalis to stay together and build collective cultural memory conducive to a stable national identity. Cultural factors and social diversity are two key elements for democratic checks and national resilience. But Nepal needs to overcome two critical democratic deficits: substantive one in the grasp of all Constitutional rights and equalisation of welfare across diverse groups through evidence-based policy; and procedural one in terms of proportionality of social representation in power to erase the legitimacy and efficiency gaps. This can discourage politics of distributional coalitions seeking to negotiate the weak Nepali state for sectoral benefits and check the modernity's hedonistic treadmill infecting Nepali constitutionalism and leaving its citizens restless than before.

Two ironies pervade Nepal's constitution: promise of social welfare state and funding crunch to realise it leaving its politics aspirational and right to self-rule inherent in popular sovereignty which bars the impunity of interest groups but inability to govern local bodies as they face legal, administrative, infrastructure and resources bottlenecks. Partisan legal culture has become an enemy of reason where even a close circle of legal fraternity detests each other's views and defends its side despite its demerit. It has stymied Nepali state's ability to execute the constitution even with huge electoral legitimacy. Democracy within the state sets an open-access order for its citizens while beyond the state entails "institutional closure" and constitutional outreach to international regimes and laws. Lack of coherence between the state, economy and citizenship, beyond the state forces is flagging state-centric constitutionalism.

Tradition

Political stability in Nepal requires the lawful tradition of politics and attainment of autonomy, reliability and adaptability of public institutions in service delivery. Inequality of resource affects the quality of democracy and deprives one-third Nepalis at the bottom having no control over their destiny. They need resources, skills and opportunity. Democracy is the project of modernity. It abhors both pre-modern politics of tribalism and post-modern lack of affection to national affinity. As a compromise formula, it stresses on building the national identity of citizens. Nepal's constitutional history suggests that discontinuity of politics marked the failure of political classes to achieve their political tasks and create more winners of democratic game. A win-win outcome can create the stake of rural poor and minorities, women and Dalits and their ownership in its process and ignite a fresh faith in constitutional governance.

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/22877}

### Democratic citizenship

Democratic citizenship is a central issue of political theory and practice. Good training in citizenship rights and duties enables them to exercise valid judgment on public issues, assume social responsibilities and voluntarily participate in public affairs. Democratic citizenship is based on the values of enlightenment: reason, freedom, equality, solidarity and courage integrated to each other in a sparkling awareness about self and feeling right inside without being biased to others. It helps overcome customary and institutional fetters. Rousseau is right in putting feelings of the heart above the reasons of mind for a democratic political culture. It liberates citizens from the perils of determinism of fatalism, suffering, unfairness, domination and perpetual infantalisation of democracy, _sishu loktantra_. Nepali citizens, therefore, require full awareness of democratic politics, institutions and constitution to lead a life of choice, participation and dignity.

An irony pervades Nepal's political discourse. Nepalis face disharmonies between the compelling constitutional vision and sordid practice and their shared existence and lack of enough public goods for many those left behind. So long as the antinomy of freedom and injustice remains, it does not cultivate citizenship virtues or consistency of shared insights with the global community. Hans J. Morgenthau narrates three dimensions of human life--biological, rational and spiritual. Individuals move from one scale of desire, will and passion to the next based on the plane of their education and vigilance from childhood, adulthood and old age till death as a final point fossilises them.

Mere biological life espouses the survival of the fittest. The spring of self-justifying rational dimension is hotly contested now for its inability to solve all human problems. The higher scale one moves among the spiritual and moral dimensions, the greater the role of eternal wisdom and inclusiveness where what Astavakra calls "one sees others like oneself." The spirit of modern age of citizenship arises from the feeling of affection, attachment, mutual respect and support to each other for a satisfying role in the polity.

Education for democratic citizenship in Nepal is vital for the cultivation of democratic manner, integrity, attitude and habits. It brings democratic values to the life of each individual, family, school, political parties and public institutions and unshackles Nepalis from the aristocracy of organised power of leaders and their own audacity to frequently defy it in each election demanding reforms. A balance between will and wisdom is vital for the triumph of justice in the order of community, society, polity, the state and international relations. For this, Nepalis must acquire civic virtues and temperament beyond their social conditioning and allegiance to their families, castes, classes, peer groups, educational intuitions, professions and political parties to a duty to the Nepali state, goodwill to humanity and caring of other species upon whom they live on.

The role of Nepali media, Election Commission, civil society, educational institutions and political parties lies in training adults for democratic citizenship who do not escape the judgment of others in the life-enhancing activities and sustain thought-control or detached thinking from the web of life. The later trend does not make Nepalis future conscious and politicised which is a characteristic of democratic citizenship.

Nepal's classical treatises find relative importance of three virtues in human beings tamo, rajo and satto guna strutting three paths of life- bhakti (service or devolution) karma (action deciding the destiny) and gyan (enlightenment). It is absurd to think of good leaders without worthy citizens able to internalise these cognitive and affective virtues and expand the public sphere. Dialogical, reflective and contextual method of learning about the condition of life and discovering true knowledge and work for the resolution of problems in Nepal have positive effects than self-deceiving rote learning.

Ancient Nepal followed justice as a basis of rule. It transcends the disciplinary cage to include ecological, social, gender and intergenerational spheres. It also cites a cosmological understanding of self and others. The tradition of collective leadership in Nepali parties, however, often faces a cacophony, tension and cracks as fractious leaders innocent of culture have failed to appeal across fractional divides and govern the group affinity through collective competence. Unaware of their sovereignty, Nepalis also desire to get support from their leaders like children from their parents. It may look selfish to outsiders but it has deep roots in Asian culture which makes difficult for leaders to acquire public spirit that can transcend both individual and inner-circle of group interests and serve general public goods. A high sense of civic competence of Nepalis is, therefore, essential to build confidence in shaping the content, course and action of democratic citizenship.

Now the decay of ideologies has surged postmodern identity politics. But it has also opened pre-political tendencies and commercial interests to flourish. This socially constructed identity of late capitalism cuts the chance for democratic citizenship of equality. What would Nepal's future look like when language, culture and religion that fabricated its national identity are laid to rest, hotly contested or disfigured? Individual identity is defined by the self and also by others. The modern Nepali state gave them an identity of citizenship which is stable and universal. In Nepal, citizenship is required for voting, land and property purchase, job opportunity and entitlement to constitutional rights. It provides citizenship on the basis of ancestry, birth certificate, residence, marriage, etc. and intends to issue identity cards for every native by putting them into a digital system. It is important for them to pay tax, improve life condition, protect public property and extend loyalty and support when the state needs. The consolidation of democratic citizenship in Nepal is a vanguard against feudalism, tribalism and fundamentalism of all sorts as it fosters civic patriotism.

The ability of Nepali state to constitutionalise all actors of society is a must for sustainable democracy. Democracy cannot be equated with inter and intra-party politicking, divisive debate on national issues, polity, power and authority, squabbles of civil servants and unrestrictive, noisy politics for the change of regime every time or subversion of electoral mandate to fulfil personal ambition. They kill altruistic thirst and defy political stability and democratic culture based on self-determination of Nepalis. Civic virtue upholds public spiritedness, balance in giving and taking and civic engagement from public decency, respect to elders, cleaning of roads, planting trees, controlling domestic violence to defending national interests.

The identification of the character traits that constitute civic virtue has been a key concern of civic culture fit for Nepali democracy. Civility refers to cognition, attitude and behaviour Nepali leaders and citizens conform to Constitution, trust of authority and the sanity of the nation's tradition but also keen to execute international obligations. Spiritual faith does not make Nepalis feeble nor does secular anthropocentrism make them great by causing the leaders' personalised authority rot thus cultivating an institutional culture.

Civic disposition helps to guide on making good citizen. Its fundamental universal traits necessary for Nepal are: First, building civic confidence of Nepalis to be able to engage in civic life of multi-level governance as free and enduring genius. It enriches the robustness of democracy while lack of it creates public apathy, alienation or negation incubating parochial political culture. Second, civic disposition is the product of educational praxis where Nepalis understand their duties associated with self and the public institutions which enable them to live together under the same sovereignty linking knowledge to serve the life world.

Third, as a post-conflict state Nepalis must be educated to know non-violent ways of communication, decent ways to be open, tolerant and responsible in cooperative action to perfect a sense of humility. Civic disposition of democratic citizenship does not mean a culture of conformism and silence; they are social cancers but active engagement in the solution of society's problems. Fourth, traits of civic disposition in Nepal involve the virtues of active citizenship that combine the qualities of civic mindedness, commitment, responsibility, critical thinking, courage, patriotism, openness, compromising on reasonable issues, compassion to the weak, honest, respect for rule of law and deference for other's rights and dignity. Compliance to these attributes makes a general ferment of hope for democratic citizenship in Nepal which also makes a difference in the nation's life.

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/30537}

### Leadership Imperatives

Modern time is dotted by a moment of great transformation. Multiple crises in the world are threatening the rule-based order. Leaders, as societal catalysts, are struggling to cope with them through workable policies. The acceleration of scientific revolution-innovation, information, communication and technology is causing big disruption buffeting every aspect- nature, institutions, laws and rituals of normal life. In this wind of change only the transformational leaders, with creative imagination, understanding and experience about scientific progress, can cope with them by a specialised team of experts, reap from its benefits and free the vigorous productive forces alive in society. Their intellectual ability lies in crafting a shared vision to navigate the future, coordinate change and organise collective action.

Transformational leaders do not have the illusion of human nature. They differ from normal transactional politicians who, locked in the pyramid of status consciousness, seek only nauseating conformity and loyalty of followers through both rewards and punishments and resort to vote-buying and rent-seeking strategy as a survival imperative. In a nation like Nepal with diversity, leaders, with enlightenment beliefs and entrepreneurial zeal, can inspire citizens to constitutional goals, broaden their perspectives for national unity and animate their motivation, morale and performance.

Leadership training for greatness enables them to sail with the flow of change and prosper together with citizens, their culture and the state and become pro-active in untangling complicated problems. There are philosophers behind the success of great leaders. Sage Astavakra trained king Janak on atma gyan (inner vigilance) helping him to acquire divine quality of higher moral purpose and timeless worldly wisdom in rule. Inward training for the cultivation of good character is beneficial to self and others in need.

During Mahabharat times, Bidur invented many policy measures for the leaders to follow. Neglect of his advice triggered the War of Mahavarata. Plato envisaged the importance of a philosopher king for just governance and advised the ruler of Syracuse. His disciple Aristotle trained Alexander the Great. In India, Kautilya schooled Chandra Gupta who ruled the Indian empire while Niccolo Machiavelli tutored prince Medici of Italy. In China, Mencius was advisor of King Qi.

These leaders were men of vision, integrity and consequence. They did not divinise leaders' personality but humanised their behaviour towards citizens. The ideal traits of leadership rest more on connecting themselves with citizens in a common public purpose than dividing, dominating or controlling them like in feudal era. Now, the reinvention of ancient art and wisdom has become relevant in Nepal for the cultivation of leadership so that they focus on vision, connectivity and ability to collaborate with citizens in weal and woe.

In a new democracy like Nepal leaders' imperatives to rule increase in proportion to the position they occupy in the institutions aiming to fulfil citizens' expectations for the happiness of a rational life. Leadership virtues that keep the vitality of charisma are vital to connect citizens in a fractured world, solve their problems, enable to move beyond their personality and frame a positive shadow of the future. But the charisma is transient. It needs to be replaced soon by legal-rational authority legitimised by elections, process and performance.

This is why every country sets up think tanks to provide synthetic inputs to national leaders and build their capacity for awareness, adaptation and responsiveness to any change or challenge plaguing the nation. The decline of ideological leadership in Nepal marked the rise of professional, careerist politician of bureaucratic type which led a sharp break with the solidaristic politics and entered into networking driven by passion, instinct and self-promotion without any interest in remedying challenges of national unity, stability and peace. The conversion of Nepali leaders into a catch-all type with a strong bent on expediency, not consistency with their policies, posed a drag in improving the lot of citizens.

Nepali leaders have displayed enough courage to stir the emotion of citizens and offered them programmes for a better democratic world with freedom, justice and peace. Their leadership style and rhetoric inspired Nepalis of all walks of life to synchronise their political action for regime change. But they have shown poor quality in the governance as they reflect the partisan view of their political brand and feel no need to change the political culture they are socialised into performing. Leadership in Nepali language means netritwo, the upholders of right public policies.

Ironically, Nepali leaders have abdicated the policy making duty and applied borrowed policies from abroad without indigenising them to fit the peculiarities of national situation. Its outcome is polarised development. Their vigilance about the changing context, values, issues and institutions are critical indicators for their success in mobilising resources to satisfy Nepalis' expectations of democratic dividends. The sputtering success of Communist Party of Nepal in multi-level elections and promise of political stability, prosperity and happiness provided the nation a chance for a stable rule. But the political will for this is bitten by intra-party leadership feud and multi-hued social ferments straining the morale of public institutions to do something better.

The top leaders of opposition, Nepali Congress, alienated from each other and forlorn hope of citizens, have just completed their national awakening programmes seeking to consolidate the party by abolishing internal sabotage and leadership feud, holding timely elections of auxiliary bodies, linking with the grassroots and providing leadership opportunity for youth. The Madhesi parties, Rastriya Prajatantra Party and smaller left parties are engaged in fissiparous tendencies- unity-split-unity- while all left forces have a common strategy of unity-struggle-transformation through democratic centralism.

In Nepal, transformation has largely been delayed because of the split of critical masses, delay in translating the mandate, declining standards of education, economy, organisation and interdependence among social forces and overlap the old and new elements. The growth of enlightened leaders in the institutions of society is faster in networks and movements than the government and political parties to respond who end up performing by rote, not institutional memory.

The cascade of vices has shaken the poise of bulk of youth in politics. Some are fighting for inner party democracy, others are engaged in self-chosen civil society, federations, foundations and social movements to gain greater social legitimacy for self-governance and still others are forced to migrate abroad in search of job, brain drain or stay disaffected. The use of demographic dividends only to accumulate remittance and suppression of market competition by economic maladies have bred kleptocratic networks with impunity which cut the regulative power of the state to constitutionalise society and perform basic functions.

Democracy has opened the Nepali society to the new values and elevated citizens to a source of sovereignty where leaders can learn from their experience and become thoughtful, virtuous and reflective. Popular sovereignty helps leaders to break the usual way of seeing the world in a linear way advanced by social sciences but engage in it from all sides and know, like statesperson, the logic of transformation at all the spheres- family, community, society, political parties and state institutions. Nepal has seen a cycle of regime change without the chance to consolidate polity. The first reason is weak leadership with cultic personality. It only lulled their supporters into believing the utopia, even in a time of uncertainty and turning crisis of political order acute. Nepali leaders are less socialised in native knowledge, geography, history and culture and the zeitgeist vital for the transformation of feudal, patronage-based and clientalistic culture into civic one. This has led to the rise of strongman politics, father figure or leader-for-life, a sort of creeping authoritarianism.

The second reason is that political power is tottered by hereditary, family-friendly, patronage-based and coterie politics delinked from the reflection on history, public opinion and meritocratic virtues. As a result, the trust of citizens and party cadres on the leadership is shifting from one to another. The third reason is the operating style of Nepali parties in a personalised way without broad-based consultative practices with local party leaders, cadres and citizens. The fourth reason is politics is dominated by money where each values the other on the basis of monetary clout than the ideals of democratic life.

The capacity of Nepali leaders is beset by powerful interest groups screwing positive effects of public policies. Unlike in China where business and politics are separate spheres, Nepali leaders and businessmen are wearing both crowns strong enough to rip the social contract where citizens pay the taxes in return for security and redistribution of resources. This has inverted a balance of power between the state and the market. Transformation endures when the sanity of civic power guides the establishment and critical mass of change either acculturate citizens or assume leadership to set new state-society balance where out-dated structures, norms and practices are replaced by the new democratic rules and constraints, not stuffed by personal loyalists of leaders in all public institutions who skew the impersonal distribution of public goods.

In this context, Nepali leaders have to coordinate between the public servants and the public under a common authority, mediate between the top decision-making centre and the bottom of society for the articulation of citizens' needs and priorities based on a common conception of justice, mindfulness to ecological, social, gender and intergenerational concerns to help each citizen gain means of purpose in life, minimisation of their personal ambition for the promotion of public goods and break the passivity of citizens through civic education instilling in them problem-solving capacity to the challenges of democratisation and acquire collaborative learning to adapt to transformation underway. 

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/32625}


### Public Security and Democracy

The health of any society is linked to safe and sound environment. A key factor determining public security is the state of national security and global situation. Public security is a public good. No one can be barred from its benefits. It can flourish on the solidarity of the public with security agencies. Democracy as a rule rests on public trust, freedom of citizens from vital needs and their intrepid expression of opinion. Leadership gains legitimacy if it can fulfil them and realise citizens' right to secure life. Safe and secure citizens are those who do not feel threatened and whose life, liberty, property and pursuit of pleasure are fully secured. In Nepal absence of trust paralyses collective action and terribly affects the poor because they have less means to secure themselves. Growing mistrust lurches the power of civil society to regenerate impulse of civility. Democracy provides Nepali citizens a chance to test whether their sovereignty preserved in the Constitution of Nepal is real or rhetorical and their rights practical or legal only. They are the nerves of a decent life. In security deficits democracy turns flawed and sets off a state of nature and scarcity of public goods hitting the civility of society.

Fatal gaps
Nepalis suffer from two fatal gaps between the changing social order and weak governance to manage and aspiration-fed citizens and frailty of civic institutions to satisfy them. Rule of law can contribute to physical and psychological security in Nepal if its polity holds institutional muscle to provide social justice. Public security is linked to macro national security which is now beset by multi-level tensions lack of which stokes predatory forces to free ride. At micro level, it is linked to safe family and community milieu, secure roads, access to education and health, regulatory system to responsive politics. Anti-constitutional activities of various actors strain orderly rule in Nepal. The shortfall of public security fed by the infectious partisanisation of discipline creating agencies can only be remedied by their political neutrality and gaining the soul, the public support. As a result, a gap exists between the existing levels of public security in Nepal and what the regime ought to do urgently. Only a coherent plan can match the scale for securing citizens.

The causes of insecurity in Nepal are both intra-systemic and extra-systemic. Nepal's Home Ministry has identified 33 groups of various hues including armed outfits posing diverse scale of concerns. The scope of public security is scaling up in proportion to the increase of many sources of contagious risks. Its scarcity is evident from the fact that women, judges, journalists, officials, political leaders, business community and ordinary citizens demand for it. National security deficits have prompted VIPs to have more security staff these days than a decade ago and the private security agencies have thrived to protect the powerful, their wealth and enterprises surrounded by warning devices, guards and guns. Concentration of opportunity in sprawling towns have added newer risks-poverty, joblessness, crime, violence against women and girls, theft, drug abuse, growth of small arms, kidnapping, extortion, etc. They have disarmed Nepali democracy from its substance.

The organised crimes linked to grand corruption and pressure on coalition government to tolerate elite- run syndicate, monopoly, capital flight, tax-evasion etc provide the structural reasons for it. Crimes as proxy factors of violence are linked to macro milieu which can cause severe civic exhaustion - anomie, chaos and erosion of authority offering scope for looting of public wealth and flouting societal norms. Nepal's old disease is the treatment of effects, not the causes, which nastily bred the virus of insecurity. The growth of many channels of political socialisation in Nepal indicates enlarged communicative skill of citizens and use of technology. It provides a basis for the civil society to reflect on the condition of Nepalis, raise awareness, invent tools, manage technology-induced risks and spur safety measures for their lives and property. The government's dialogue team has initiated talks while Defense Ministry is holding informal consultation on how to improve national security through an updated security policy.

The sources of insecurity in Nepal stem from the erosion of the state's monopoly on power. It limped its ability to control threats, coercion, anti-social activities, gender violence and alleviate livelihood crisis. Identity politics has reduced the idea of a political community rooted on citizenship and dragged the capacity of polity to create secure environment. Information revolution has turned democracy along participatory line of the affected citizens generating tension with the representative democracy, its institutions and political culture. The surge of the tools of violence, such as armed groups, thieves, militant wings of parties, criminals and abuses of human rights with impunity continues unabated. In the absence of integrated law-enforcing system to enforce constitutional behaviour of all actors, it cannot build a trust across the nation's divides. In a country of minority, politics based on power equation alienates the Others. Public security has also suffered from porous border, limited resources of security agencies, sophisticated techniques used by criminals, poor information system and weak coordination between civil-security relations. In this sense, elites need to work on bonding forces of society and combat the violence targeting the public. Self-censorship of media, human rights bodies and security agencies induced either by profit incentive or partisan politics reduces them to a mere spectator and stoke a culture of pessimism and silence among the insecure section of Nepalis.

Public security is the duty of the state's public officials. But they fail to turn effective without upholding the integrity of office supported by watchful eyes of citizens. In Nepal, public institutions are weak and social and economic order is fractured by the erosion of hard institutions of the statemilitary, armed police force, police, intelligence and public administration responsible for a robust security. Psychological safety emerges from the soft power--vigilant public, media, civil society and attentive citizens. They supply early warning of social risks, spawn critical information and build opinion, preference and policy. It is vital to create business-friendly environment. Active citizens can act as a watchdog of political power and carry out their innovative pursuits. Their right to information makes democracy a responsive rule. Informed dialogue across the nation's diverse spectrum is absolutely essential to build trust, bridge the factors that split them and heal and reconcile this nation's sores.

The politics of moderation between capitalism and communism is the way to manage the appetite of both to consume each other or collusion for shared benefits and elevate the outlook of identity crazy groups into a larger national sphere. Building trust across the Nepali citizens can surpass the elites' penchant to parochialism, re-tribalisation of society and indulgence in post-modern tumult justifying vicious politics. The role of Nepali civil society remains supreme in circulating the civic education and inspiring their active engagement in national construction. It is a key pillar for lifting the design of public security of Nepal. The community police-citizen interface is a fine example.

Nepali media daily report the overall health of the state and society. If the level of insecurity grows, the indicator of early warning moves up. Disinformation generates distrust across the empirical divides hostile to security, stability and social peace. Public alertness about the changing national context is a heady way to reduce conflict-induced insecurity. Awareness about the civility among leaders and security agencies builds bedrock of trust and radiates to every corner of Nepali society. Transparency of business investment is essential for the democratization of information, capital and business houses and resolves the tri-lemma between media freedom and security of journalists, professionalism and social responsibility and access to information and credibility of news, views and information pertaining to public security.

Those engaged in security mainly police and public administration await three critical roles: monitor anti-social groups, drive actionable intelligence from the investigative media and attentive citizens and build strong ties with the community. A modicum of public security in Nepal demands a synergy of hard institutions of the state which carry the sanity of tradition and soft social capital of society which is helpful for the adaptation of the state to both popular aspiration and the shifting nature of global security architecture. National leadership has to adopt both preventive and remedial measures to allay insecurity and enforce a responsive rule. A peaceful environment requires building a nexus between security, democracy and progress and mitigation of general fear of citizens about the condition in which they live. The performance of security agencies rests on their autonomy, efficiency, impersonality and capacity to provide surveillance and act ably.

Civic surveillance

Spreading out of the circles of security from individual to institutional and larger macro level can pass public trust through the watchful eyes of Nepalis. Civic surveillance makes it preventive and cost-effective while pre-emptive and response-ready security deployment deters the evils' offensive. The promotion of integrity system of all actors through accountability measures set norms for the fulfilment of shared expectation and build integrated horizontal and vertical social capital. The creation of a strong national centre is vital to spur centripetal forces and secure heartland, strategic areas, buffers and frontiers. It provides them a chance to form networks in the community and cut security risks. Stronger ties act as a bridge across citizens and synchronise conduct. To meet its rising challenges, responsible civil society should be made effective to enforce citizens' solidarity with the state and their collective action. 

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/26534}

### Ethics of Political life

The ethics of political life refers to its qualities of being right, honest, non-corrupt, fair and good. It is entrenched in representative, legitimate, transparent and accountable governance which makes bribery a high-risk venture. This ethical life becomes weak if thieves of Nepali society and the state rob citizens of their equitable future. The media daily reveal that both are heavily infected with the toxic elements - corruption, crime, deceit, amorality and abuse of authority. The cardinal virtue of ethics is wisdom. Politics, however, universally unfolds a paradox: combative human nature collides with human rationality and a shared sense of civic responsibility. Political realists hold grim view of human nature. It creates a circle of affective bond around selfish genes. On the opposite side of life, idealists believe in social nature of human beings. The universal human reason feeds prudential rule and breathe the ardour of ultimate values.

Here ethical life seeks a balance between self-interest and care to others. Nepal's constitution has integrated rights, laws and morality. The invention of human rights aims at taming egoism and lift moral standard for the greater good of citizens. It is a path to cooperation for security, stability and peace among citizens and nation-states. Optimal freedom can shape decent behaviour for the formation of a culture to bind selfish individuals to a common vision. Personal ethics of Nepali leaders can snuff out the malaises of politics and crack the spell of hazy practice imperilling the governing rule.

Certain ideals set politics to ethical edge. First, ethical politics balances the conflicting desires of diverse Nepali citizens without excluding any one from the public good. Good life promised in the Constitution of Nepal cannot be divorced from their abject living condition. Second, ethical politics is not vacuous. It demands virtuous character of leadership capable of innovating good public policies, laws and actions and fulfilling promises, rights, needs and duties underlined in the Constitution. Third, ethical politics seeks the compatibility of means and ends of a welfare state. It treats Nepalis an end in themselves, not means to each other's benefit. It wires the sanctity of human life which market fans and seditious politicians often miss. Fourth, ethical politics views that liberty of pleasure rests on apt dispensation of political order assuring the integrity and dignity of Nepalis so that they are not vulnerable to violence, insecurity, poverty and scarcity caused by dysfunctional polity. The dignity of Nepalis can be ethically justified and morally defended. It pertains to the integrity of democratic polity. Fifth, ethical politics values human life above other values such as power, authority, legitimacy, position, wealth, etc. fitted to grasp the purpose of life.

Inculcation of ethics allows Nepalis to exercise conscious choice of good over the bad. Nepal has adopted education for all, labour rights, gender equality, abolition of social discrimination and protection of weak and environment. Education can make them better off if institutions and norms of the nation are utilized to erase the pains of everyday life and remove causes of misery. This means economic values must be compatible with educational policies and practices and development gaps do not skew the sharing of commonwealth by all citizens. The social psychology of citizens is that they compare themselves with others. This is why winner-takes-all society is prone to overload of public demands, instability and conflict. Nepal's constitution has, therefore, stressed on increased social spending, social security and social justice for the poor. Still, unfulfilled electoral promises and rights prick moral conscience of leaders.

Ethics embeds all Nepalis on public spirit to share a sense of civic pride by controlling the lever of power caught in a callous division of spoils of weak statecraft. Nepal's demand for justice in the global arena can be ethically justified if its internal order is grounded in the frame public decency. This entails the art of governance defined by its positive outcome to all citizens. But corruption dilutes this by an exit of those in authority from the accepted standard in pursuit of illicit profit. Nepal's recent history is beset with policy corruption, patronage, gifts, kickbacks and theft of international aid. This has swelled the costs of progress in Nepal. The thin line between accepted behavior and unauthorized personal windfall gain will continue if public policies do not have ownership and relevance.

Controlling the inner virus of Nepali polity is vital for pumping economic efficiency, political accountability and judicial fairness. Vices permeate into individual life when one prefers to live beyond one's means either through bribery or stealing of public funds. Nepal's institutional decay is attributed to the deviation of public officials and elected representatives from the fidelity of its goals and indulging in greed. If cultural industries are conscripted to heaping praise for self-indulging corrupts, they echo nothing but an atrophy of civic sense.

The delivery of public goods and services to citizens is the ethical duty of a government. In Nepal, its efficacy necessitates capacity building, result-orientation, public participation and the promotion of national integrity by a right checks and balance of the polity's institutional poise. This cuts the abuse of authority and leakages of national wealth. Predatory corruption whether minor, based on the survival need of low paid officials or huge ones involving higher authorities at policy level reminds what Prithvi N. Shah said, "bribe takers and givers are enemies of the nation." Such monetary accretion does not go to productive reinvestment, but to foreign banks or foreign investments, infinite consumption of luxury items and distortion of management practices.

In public sector contracting, the costs of corruption are reflected in the waste of scarce resources, misallocation and bad practices. The economic cost of corruption in Nepal have exhausted political muscle and bred many corrosive practices: procuring high cost goods, tax-evasion, bank defaulting, rent-seeking, selling of profit making state enterprises, decision in favour of fruitless project, rising cost of goods and gradual entrapment of the nation in the odious debt and misery of ordinary Nepalis. Where bureaucratic corruption is institutionalised, officials do not hold their jobs in high esteem. In case of low salary, promotion fails to motivate them. Rather, tendency appears in foreign travel and fake payment. In an oligarchic polity with a multiple source of syndicate, bribery flourishes in revenue branch, law enforcement office, public utility sector and within the same office by superiors where services are slow without bribe.

Nepalis are appalled by the nation ranking high in the firmament of global perception index tormenting ethical life and wrecking public works. When corruption turns out to be systematic, it is hard to check it without reforming the symbiosis of business, bureaucracy and politics, ending impunity for grand offenses against public and national interests and protecting the Nepalis from law breakers--predators, thieves and armed actors. Unless top Nepali leaders imbibe Seven Principles of Public Life invented by Lord Nolan, such as selflessness, integrity, objectivity, accountability, openness, honesty and leadership and institutional culture, the ethical political life cannot get robust footing. Public programmes afflicted with bribery require defiant action of CIAA, Auditor General, parliamentary committees and intelligence unit, not tearful confession of lack of laws.

Financial integrity cannot be beefed up without a political will of the government, access to information and a vibrant public sphere to escalate the cost of abusing ethical life. Anti-corruption watchdogs need to probe the fairness of the decisions and the duty of public officials. Ideally, the National Election Commission can deter corrupt and criminals' participation in the polity and make leaders accountable to the ethical life. Civil societies also have a vested interest in detecting the illicit tricks of public officials and mobilising citizens to cry for justice. They can become effective if judiciary serves as a guardian of the public interest and does not bow down to the executive in withdrawing cases of major offenses. Nepal's Constitution has included right to information which makes media's central role in enforcing the accountability of leaders to the public interest and monitoring their deviation from a wide range of policy issues including aid infusion to conditionalised policy and geopolitical plot.

Integrity of Nepal's political life requires integrated solution - citizens' abiding defence of public institutions, their mutual checks on power and effective civic bodies, such as media, civil society and anti-corruption watchdogs to align with them in fighting the amorality of life. Constitutionalisation of behaviour of all actors and democratisation of parties can reduce political vices arising out of the deinstitutionalisation of the polity and weakening of civic life. It is feasible to infuse ethics into politics and enforce a moral standard in Nepali society, economy and polity through education, socialisation and strong civic activism. Ethical base of Nepali polity demands the strengthening of criminal justice system. Execution of law through legislature, making binding decisions of public will and enthusing in politics social solidarity and compassion are vital steps so that ill-gotten private wealth does not disrupt moral feeling of noble hearts of family, community and educational institutions to foster the ethical standards of political life.

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/23635}

### Duties of Citizen and State

A good society cannot be created only by rights without any social duties and accountabilities. To Immanuel Kant, acting according to duty means to "obey the law" legislated by citizens or their deputies as rational beings. Government officials have well-defined duties to compulsorily perform, which creates credibility and trust in them. Citizens also have determinate duties expected to be fulfilled by means of their dharma of volunteerism, vigilant defence of public sphere and institutions that enable them to converse on critical issues and discover measure to solve them on the optimal interest of all sides.

In Nepal, civic duties embrace worldly legal, moral and practical obligations of citizens. The Constitution has entitled them with many welfare rights, which oblige the state to fulfil and engage in mutually helpful international cooperation and perform cosmopolitan duties. The modern rights have replaced Hindu-Buddhist concept of vigilant interiority, atma gyan, which is central to the character building of leaders and citizens. This concept provides them freedom to use public reason and right to rebel against unjust rule.

In democracy, duties correspond to rights where the state and citizens are bound by mutual obligations civilised by socialisation, communication and nationalisation. It transcends selfish human nature, which seeks to govern the weak by depriving their dignity, nationality and humanity. A balance between rights and duties can bring the Nepali society to the cardinal virtue of middle path and build social solidarity.

The Constitution of Nepal makes citizenship to Nepali citizens an indispensable right by virtue of their nationality. Nepali citizenship is acquired through: jus sanguine, descent, jus soli birth, domicile residence, marriage, diasporas and honorary grounds. The last three types have allowed non-territorial dimension of citizenship. There are non-territorial groups such as citizens of other countries yet tracing Nepali roots and upholding its identity and cultural affinity of oneness and wholeness while six million Nepali youths in the global labour markets exercising some form of post-national citizenship though they have limited labour rights, less dignity and fewer choices relative to those living within the nation. Guest workers are fulfilling national utility while refugee's status is governed by "gentlemen agreement" with external leviathan. Both are excluded from political participation. The tradition of citizenship in Nepal is tied to a practice of closure along national line and linked to nationality.

Nepali Constitution deems citizen and the state sovereign entities bound by reciprocal loyalties and duties. It spells out 31 rights from the right to life, liberty, education, health, property, social security and work to food sovereignty and four duties to Nepali citizen: safeguard the nationality, sovereignty and territorial integrity of the state, remain loyal to it, abide by the Constitution and law, render compulsory service needed by the state and protect and preserve public property. Good citizenship is constructed by the cultivation of civic virtues, art of association and distribution of power in decision making across the populace for local self-governance. In Nepal, the rights-based legal culture of citizenship has shifted from immutable stage to contractual ones at all levels from marriage, company, civil society, political parties, state to global governance.

Duties of Nepali citizens are less elaborative, for example, it does not refer to the duty to pay tax, caste vote during election, inform about the crime to law enforcement agency, maintain public decency, uphold the spirit of patriotism, engage in public action, maintain social harmony and peace, etc. This implies that caring public and national interests is the shared duty of Nepalis and their state. When the sovereign space of political community, the Nepali state, erodes through globalisation from above and proliferation of autonomous forces below it drains emotional bond and ignites the surge of tribalism with its scorn for the sanity of native wisdom of tolerance of diverse culture. The logic of globalisation operates under the law of economic efficiency, not democracy and, therefore, Nepal must devise an integrated political response to negotiate new challenges.

The state, based on a civic culture of citizenship, is best suited for stable democracy, no matter whether the rule is unitary or multi-level. What it needs is the government of law and free watchdogs, including judiciary able to control the abuse of institutions, laws, rights and duties and accelerate resolution and reconciliation. The legitimate monopoly on power of Nepali state is vital to enforce Constitution spawning a vault of hope for stability and progress. Citizens differ from clients and consumers. The former are tied by the impersonal bond of nationality and seek common good while the latter seek to satisfy private interests. The consolidation of Nepali state demands active and positive citizenship able to utilise democracy's ingenious energy and invent legitimate demands to polity.

The art of agile and active citizenship with an awareness of enlightenment, rules, rights and duties and the legitimate source of state power can exert pressure on the leadership to formulate good laws and public policies beneficial to common good. Their apathy, however, weakens the community, society, polity and the state in the same way as inactive cadres enfeeble political parties or civil society's vital energy.

A society with many rights and few duties like in Nepal creates condition of social disequilibrium affecting both social cohesion and system integration. It undercuts democracy's material force. Stable national identity in Nepal is important for the management of its diverse caste, ethnic, linguistic, religious and geographical dispositions so that they do not harbour centrifugal inclinations or nurse irredentism vitiating geopolitical pressure. Duties of citizen provide collective national sentiment for patriotism, a sort of bridging and bonding social capital and their equal stake in the state. The duties of Nepali leaders lies in rescuing politics from parochial fear of scarcity and exclusion and restless struggle for power in the face of powerlessness of citizens by mobilizing the forces of national unity.

Nepali state is fiscally and institutionally feeble to perform its entire duties without its capacity enhancement, integrity and an ability to pacify tools of violence. Unfulfilled rights erode the legitimacy of the government and polity, if not the state. Nepali state is also burdened with many international duties.

In this context, Nepali state has to formulate certain policies for the congruence of society, economy and polity and mediate between legal equality and condition of inequality of citizens. The abolition of a gap between constitutional ideal of an egalitarian society and empirical condition that defies it is vital to liberate Nepalis from their primordial identities and loyalties and construct national identity fused in popular sovereignty and state sovereignty.

Group enclosed rights foster subsidiary identity politics and cuts the concept of popular sovereignty embedded in individual and human rights what J. J. Rousseau calls "the will of all." In Nepal, citizens are socially constituted and continuously penetrated by partisan politics, Hindu-Buddhist and other religions, glitter of modernity and soft power of powerful countries. The choices made by them are, therefore, not free from their background conditions. Democratic culture diffuses duties to many institutions to whet public spiritedness for a common background condition for all. Nepali leadership needs to coordinate them under administration, institutions, rules, rights and duties inspiring citizens to work together on the basis of cultural and historical memories of national independence.

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/30112}

### Rule of Law or Rule of Justice ?

The question of what is just and unjust has plagued the minds of scholars and statesman since ancient time. It has been analysed in both universalistic and culturally relativist terms and on the basis of evolving values of progress, human rights and constitutional state. Legal construction of public order where institutions embody social justice enables citizens' support each other for collective gain. It cultivates civic virtues, attitudes and dispositions necessary to shape their habits to follow laws and judgment. Rights of citizens embedded in the constitution are connected to laws and duties aiming to improve the standards of living. The right-based culture, however, elevates coercive shadow of law over justice and morality and supports organized class of citizens while Nepal's politics, society and economy are predominantly unorganized and informal. They lack political agencies for collective action.

In this context, adoption of just polices and doing the right things are measured not simply by economic costs and benefits or utilitarian balance of pain and pleasure but by the intrinsic dignity of all Nepalis irrespective of their caste, class, gender, age, occupation or religious convictions and distinctions. Juergen Habermas argues that legal positivism is not apt for substantive democracy because it ignores social context and remains insensitive to the threat of vested interests which poses difficulty in turning political power responsive to citizens.

The popular sovereignty inscribed in the Constitution of Nepal enables them to leap into history and take charge of their own destiny through self-determination and local self-governance. Trust in the Constitution roots democratic ethos of judicial interpretation of its text with a broad understanding of its spirit without forgetting the condition of ordinary Nepalis and lending them empathy. Nepali courts can properly adjudicate the will of citizens as the bases of the law of the nation and government's legal-rational authority, if not dominated by wealthy classes. It encourages the marginalised, women, Dalits and the poor to strive for freedom and equality attuned to public international laws. The issues in Nepal are: how laws act on those poor who cannot afford to pay the fees of layers in the court in defence of their cases? How can the democratic idea of majority decision as final judge be consistent with republican tradition of popular sovereignty or "categorical imperative" of moral law articulated by Immanuel Kant?

Rule of law, an application of formalized norms and rules for all, under condition of poverty, hierarchy and patriarchy cannot satisfy Nepalis' all constitutional rights. In this context laws, as impersonal procedures and enforceable norms, hardly settle rival experiences, values, interests and choices of Nepalis divided by geography, income, social status, education and technology unless common goods are available to all. The deliberative mode of constitution making in Nepal through Constituent Assembly has been expected to reflect its plural traditions of enlightenment and synthesize all the viewpoints of society. Deliberative mode of legislation is the most rational. It helps citizens settle their legitimate public policy concerns in a golden mean. Nepalis' destiny can be realised by overcoming social evils - poverty, corruption and fatalism affirming equal opportunity and balancing majority rule by human rights of minority.

Nepal's every political party, civil society, economic and social organizations and the state promise justice to citizens. Do they have institutional and material means to fulfill it or muddle around the power equation and parliamentary coalition of majority ? The rule of justice demands the fulfillment of promises and capacitating Nepali state to meet entitlement costs. Otherwise, it stokes a crisis of trust and loss of faith of citizens. The convoluted laws, devoid of procedural rationality, opens loopholes and multiple interpretations by legal experts and incoherent verdicts beyond egalitarian spirit of class compromise. Regular inputs from deliberative public to the legislature and courts democratize laws affirming justice.

Rule of justice has broader scope than the rule of law. It means granting Nepali citizens what they deserve for the realization of their self-worth and underlies their freedom in the pursuit of their welfare gains. But it limits the freedom within certain boundaries to make it congruent with the general welfare of human beings. Rule of justice seeks to judge laws, society, politics and economy on their consistency with equity, fairness and dignity. Nepal's underused portfolios of natural, cultural and human resources are ample to enhance progress vital for material basis of justice. But it requires their optimal management, clever use of productivity boosting technology and performing public administration able to energise multitude of public, private, community, civil society, NGOs and voluntary service providers with a rainbow of choices to Nepalis. Fairness entails taxing the wealthy to aid the poor so that their solidarity can make a society of stakeholders cooperative.

The rule of justice is desirable state of affairs for enhancing many levels of social security and corrective and distributive justice to Nepalis so that social contracts at every level of society are glued by mutual obligations. But their lax enforcement is caused by fractious leaders, powerful interest groups, lobby, economic monopoly, predators and forces of globalisation. They skew the goal of Constitution to create an egalitarian society though increased social rights, coordination of public, private and cooperative economy for socialism and group equalisation through differentiated rights promise. These are vital steps to win votes and expand the welfare basis of government.

Citizens' opportunity for inclusion, proportional representation, job, education, health and care at various span of life adds new strategy to promote their good life so that they defend public order, social cohesion and peace. Nepal's welfare state seeks to balance welfare growth in respect to individual freedom and sovereign equality but too many rights without matching contribution and duties can impose overload on the state. It can breed dependency and feline disaffection among its citizens. The swollen political classes keep feeding themselves without performing good governance public interests, rebound sclerotic economy animating the spirit of justice and prevent the risks of turning of Nepalis into welfare clients.

So long as rule of law in Nepali is opened to politics and played without mutual accountability and respect among leaders, civic engagement in opinion formation, election and law making becomes tension-filled where the rich fear distributional struggle of the poor to satisfy material justice while the poor, with fire in the bellies, fear the coercive potential of law in a condition of structural injustice. This irony can cut the solidarity of national citizenship and unbound them from community obligation where they live. Law, unbound by canon of justice, is amoral. It fails to abolish the effects of privileges in judgment.

Faustian pact obliges the state to provide security and welfare to citizens in return for their loyalty. This is basis of unity of a pluralist society like Nepal. But the capacity of laws to integrate society and polity faces challenges from the atomizing tendency of market, competition among the poor for low wages and their inability to create agency for collective action. Nepal's transition from pre-national identity to citizenship added inclusion in the edifice of constitutionalism. Just institutions implicate justice which can provide a basis for just public order.

The constitutional separation of power is based on dark view of human nature which drives politics for self-interest and, therefore, checks are placed to avert the fear of tyranny, make leaders rule-bound and secure individual freedom. But the tradition of paternalism in Nepal has made power separation fluid, eroded the efficiency of public institutions to achieve their tasks and dispense justice consistent with the Constitution and SDGs. Public morality of Nepali leaders demands ethical awareness of their power and choice of good over evil. It is rooted in ethical life which tends to secure ordinary Nepalis from human and nature-induced vulnerability and set coherent objective for ecological, social, economic and political justice enabling the poor to satisfy their needs vital for social mobility.

But Nepali polity must balance social inclusion and meritocratic virtue. The link of laws to scientific evidence and reason is obvious but whether its execution and interpretation is driven by conscience or self-interest of interpreter has an effect on democracy. The use of scientific culture can dispel myth and fatalism but in no way they can fulfil Nepalis' desire for dignity. Nepali leaders, driven by secular traits, needs to embody moral checks and imbibe constitutional spirit on their power lusts.

The supremacy of law in Nepal is often challenged by justice demanding social forces, such as women, Dalits, workers, indigenous, ethnic groups and minorities and entrenched elites whose power impulse favour privileges, impunity and self-righteousness. The constitution cannot be used to justify violence. The crisis of stable political order in Nepal springs from lack of constitutional enlightenment, logical incoherence in the interpretation of laws, basing arguments not on public reason, spirit of constitutionality and universal public morality and structural impediment in recruiting judges.

If law is decided by merit of the case, judicial organ ensures its protection and executive aptly administers law and policies it can lay the groundwork for a liberal adjudication in Nepal. If judges are selected on the basis of partisan prejudice and they have to attend parliamentary probe and hearing the judicial autonomy, integrity, credibility and wisdom suffer. Justice, more than law, is vital to the growth of personality. The practice of constitutionalism is a remedy. It refuses to recognise the power of powerful over the general interest of Nepalis and marks an emancipatory break from popular legal maxim of Nepal "law for the poor, immunity for the rich" for a qualitative change in the nature of rule of law affirming justice.

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/31750}

### Citizen-centric Peace Building

The restless labour of Nepali citizens for positive peace has found its resonance in their peace building activities. But now this trajectory is encircled by unsettled problems. As a result, peace in the nation continues to compete with other endless claims, such as sharing power, capacity building of provinces and local bodies, flexible citizenship, proportional inclusive representation, controlling social vices, fulfilment of basic needs and satisfaction of identity- mania of scores of political and social actors. Negotiation and fixing of these competing claims into a legitimate public order is a precondition to fulfil an ardent desire of Nepali public for respect, esteem and peace.

The signing of Comprehensive Peace Agreement (CPA) indicates that Nepal is not remote from the centre of human civilisation. The battle of Nepali leaders and citizens now lies in realising a rational approach to education about it and adjusting their conduct to goal-directedness. The central responsibility of Nepali leadership lies in peace-oriented activities affirming rational human nature, entrenching liberal norms in a highly impulsive politics and balancing the need of Nepali state for national security and societal needs for freedom and self-governance. The reason of Nepali state presumes to protect leaders and groups from their own propensity to commit evil acts and the state of lawless freedom they want to exercise without the justification of good public reason.

Moral awareness
The moral awareness of the government about its own power orients it to practical measures for the creation of a liveable human condition fit for all Nepalis and enables adversaries to seek a common social, political, economic and cultural ground for conflict transformation. Nepali citizens' roles in multi-level elections have been well extolled but their roles in peace building have not been sufficiently discussed either in knowledge building or policy analysis. The slight interest is partly due to the confusion connected with their self-unimportance because of stress on great men politics, partly due to overblown polemics about pacifism and ritual invocation of perfect bliss articulated by spiritual organisations, partly due to their fragmentation into different camp of leaders, mass media, sub-national organisations, civil society and rights-based NGOs which hardly treasure social learning and partly due to more aspiration and less outcome that public discourses of enlightened citizens have generated to the Nepali policy makers overshadowing the role of citizens in building peace.

The notion of peace is bound up with a constitutional order based on mutually agreed principles for the behaviour of all actors in their dealing with each other. In this order, they can defend themselves and pursue their legitimate goals without having recourse to sadistic means of violence incompatible with the goal of peace. Stacking values in binary code such as democracy versus the state, human rights against security responsibilities, professionalism versus partisan alliance, tradition versus modernity, men versus women and one class, caste, ethnic group or race against the other have only unfolded blindness about overlapping interests and, therefore, could not resolve the multidimensional conflicts of Nepal. These antimonies have defied the hope of unified public action for peace. Any attempt to project conflict along this code implies that there are active interests to repress Nepali citizens' scream for the promotion of long-term peace. The conquest of certain inner and intra-party rows in Nepal is vital to evolve civic culture and resolve the condition of unstable power equation.

It is essential to alleviate the fear of government holding either simple majority or two-third majority support from abrupt collapse thus leaving the tasks of governance teeter. This tendency of politics has often opened space for each other to negotiate for absolute gain rather than mutual advantage and put the Constitution in a trap of lawless combat. Nepali citizens are, therefore, less satisfied with mere preaching of the politically correct words by their leaders as they see the surge of battles at all levels of governance leaving the agenda of peace, prosperity and happy life woefully tantalising. They want their leaders improve the moral quality of their life and constructively engage to foster peace norms with the right deed. It can stifle aggressive behaviour overtaking peace building task. Positive peace is the goal of Nepalis' life and, for this, they aim for ethical virtues that avoid political extremes, classical norms of hierarchy, patriarchy and status quo and reconcile free will for social change against the domination of deterministic politics.

Peace building as a practical area involves a set of goals, policies, strategies and programmes which aims to foil the eruption of armed conflict, evades structural and direct violence and seeks to set up a legitimate political frame for all the stakeholders to peacefully participate in ecological, social, economic and political life of the nation. It provides a keyhole for an analysis of the root causes of conflict in Nepal and an examination of the transformation of troublesome links between structural injustice and the cycles of violence and counter-violence setting a downward spiral of security, democratic and development processes. It is possible to establish stakeholders' solutions if each actor of Nepal comes out of its institutional, ideological and personality frames, understands each other's legitimate concern, begins to communicate public purpose, recovers the balance of state-society coherence and offers peace building a remedy for the security of all Nepalis. Rebuilding the state is a precondition to the success of any national initiative-security, order, service delivery, mutual dependence and acculturation to national life.

It has become an imperative for leaders and groups to moderate the lingering habit-driven thinking and keep grievances within the bounds of optimal order donned by Nepali Constitution. Legitimate order means the leadership has to forget about "imperial peace" to resolve internal conflict by inviting external powers and facilitating oneself to rise to power in Kathmandu with their support. The success of decolonisation moves has ended the utility of this approach. Only a few satellite states, under the penumbra of great powers' footsteps, follow this path. Similarly, they should also relinquish the idea of "muscular peace" that resolves conflict by rendering opposition forces to impotence. In a country of diversity like Nepal this sort of peace cannot last long as it fosters structural injustice, opens societal fissures for divide and rule politics and creates various kinds of opposition-both extra-constitutional and anti-systemic.

The "hegemonic peace" is power equation-based which too did not sustain constitutional stability and foster social, economic and political development in Nepal. In this model, powerful actors impose the rules of the game over the less powerful against their wish and stir up multiple resistances, peaceful protests and rebellion. Peace based on human nature stokes fear of domination and denial of basic needs. It is dubbed as negative peace.

A "democratic peace," based on human reasons and norms, transcends imperial, muscular and hegemonic styles, ensures the citizen's ownership and participation in peace dividends, upholds human rights and social justice and creates the circle of more winners by expanding constitutional and institutional bases of rights, power, resources and recognition. It is a negotiated one and, therefore, citizens, as stakeholders, pin resolute hope in its sustainability and demand transitional justice to conflict victims considering it important to bridge the dichotomy between CPA and its honest execution, help leaders stay truthful to their promises and enable them in general and conflict victims in particular to realise their inalienable rights, dignity and social harmony.

The level of overall progress in the state determines the efficacy of citizens and civil society to spur national aspiration of democratic peace. The public realm of intermediary associations where women, conflict victims, children, youths, Dalits, Aadibais, Janajatis, Madesi and all groups of citizens at the grassroots are engaged in restoring the broken relationship, building enterprises of production, distribution and exchange and rebuilding the general life of Nepali society. They uphold realism of precise conviction, rather than ideologically and emotionally conditioned stance, to weave the web of peace. It is a conviction which remains unwavering even during shifting balance of political power in Nepal. Ordinary Nepalis perceive the sterility of violence as a tool of politics.

Integrated strategy

A correct disposition of Nepali leaders' will can place constitutional checks on power, entice contesting groups to overcome adversarial situation and shape the perfection of shared future. Essentially, peace building by Nepali citizens is rooted in the sense of peace community formation: in the rationality of peace education, mediation of grievances, appreciation of the preservation of human rights, execution of transitional justice and promotion of human values, enterprises and reciprocity that avail basic needs for all and eliminate future sources of illegitimate conflict. An integrated strategy for conflict mitigation, post-conflict reconciliation, peace building and renewal of democratic spirit helps ensure predictable financing for early recovery activities. An economics of peace, undisturbed by any passion and instinct, in Nepal rests on collaborative efforts of entire drivers, actors and stakeholders and their general compassion for improving the human

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/26569}

### Democratic Dyanmism

Democratic consciousness has inspired the struggle of Nepalis of diverse stripes to turn their rights congruent to public goods. Civil society as their associations, federations, networks and movements aim to guard their interests from the capricious actions of the holders of power and wealth, and spur their creative engagement to make governance open and responsive to public interests. Civic action is the engines of political democratisation and social modernisation from below. It enables Nepalis to build their community vibrant and control the deviation of public policy from constitutional spirit.

By cultivating the general will and public action, duty-based Nepali civil society groups seek to keep democracy in fair balance. Their volunteerism has historically complemented the state functions while collaboration with citizens moderated the utilitarian prejudice of politics and the business. Stirred by the enlightenment values Nepali civil society have served the voice of weak and enriched the bridging social capital of Nepali communities. This turned civic sphere inclusive in discourse, engaging and dynamic so vital for democracy consolidation.

Socialisation of selfish nature of human beings towards civic ideals of tolerance of diversity, education, culture, communication, laws and institutions enables public action in many areas of public good. It can control extremism, dualism and contradictions that heaped various vices in Nepali society - poverty, inequality, discrimination, ecocide, social violence, corruption, impunity, refugees, etc. pounding the writ of democracy. Now Nepalis have developed a habit to compare and judge democratic life of the nation with its constitutional ideals and universal principles, not just relying on dead statistics, legal logic and causal determinants which misjudge the links of bodily needs with mind, spirit and soul. They seek to improve overall human condition reared by historical wisdom.

Robert D. Kaplan says, "Democracy loses meaning if both rulers and ruled cease to be a part of a community tied to a specific territory, the state." This means democracy project of rights-based civil society in Nepal needs to transform Nepalis of various identities into equal citizens able to exercise their 31 constitutional rights and four duties, and remain loyal to the institutions of state. Only their critical debate on democratic values and actors can renew the project of ecological resilience, human rights, democracy, social justice and peace. The interactive forums of Nepali civil society can offer the solution to these irrationalities and bring the society and the state back to the middle path. It enables the leadership to create a condition to secure security, basic needs, civic rights and pluralism. Citizenship is a condition to engage in public sphere and a shift from clan-based, group-enclosed and pre-rational insular community to group-opened, rational and citizenship-based society unbounded by geopolitical interest, partisan politics, interest group, business or cultic leaders caustic of social capital, civic sensibility and democracy which are essential for political stability in Nepal.

The Nepali leaders have yet to align politics, laws and public policies to a common civic spirit and constitutionalise all the actors such as the state, market, political parties, civil society and individuals to steer them to the direction of social development, social justice, environment and human rights. The regime is seeking donors and INGOs to collaborate with national NGOs, civil society, local bodies and communities and align their activities to national priorities. This can bridge the knowledge, skill and resource gaps in the spheres of women, children, livelihood, poverty alleviation, job creation and skill training. The Social Welfare and Development Act provides legal structure for local bodies to register, renew and monitor NGOs and civil society. They can cancel their registration of those indulged in social engineering and divisive politics and spending most of money in administrative cost, not target groups.

Those working at inter-village or municipality level have to do the same at province level. INGOs, the soft power of global regimes, cannot work directly with local NGOs and civil society without the official consent. Nepal offers civic space for civil society and NGOs, chamber, journalists and authorities to participate in Good Governance Committee at the local level. The demands of Nepalis for democratic dividends--social inclusion, rights realisation, skill, education, health, technology, information, market access and development imperative have amplified civic space where civil society can plug in to balance the mounting deficits.

The Nepali state's pluralist social and cultural universe historically tolerated the liberal values. It did not suppress the society's freedom to self-organise, articulate and effect public action. This has provided Nepalis associational life, a culture of autonomy, mutual trust and cooperation with the state on security, protection, wellbeing and freedom of citizens. The evolution of democratic impulses, social inclusion and right-based development broke the social closure for Dalits, women, poor and minority in public life though some political parties still harbor parochial politics of negation, identity craze, politics of difference and the realisation of group-differentiated rights which excludes the other beyond democratic citizenship of equality.

Great Poet Laxmi Prasad Devkota argues that the corruption of public culture followed the propensity of intellectuals and rulers to think for themselves first before the nation and people and minimal interest of well off in social investment. It hit the resilient rebuilding of this nation. One reason is that leaders as a role model under diverse regimes seemed concerned more about the self, family, business and partisan benefits than about public goods where party-affiliated civil society are subjected to grubby conformism while donor-driven to clientalism-both lacking interest in democratic emancipation of Nepalis. The other reason is the real lack of democratic accountability and the vital counterweight of fair media, autonomous civil society and judiciary to limit the bargaining power of interest groups, fulfill primal urge for basic needs and detribalise Nepalis. Democratisation is closely allied with distributive justice. Now, civil society need to build the skills of Nepalis to beat their weakness and enrich civic virtues to create a healthy community linked to one another as a member of common nationality and shared humanity.

Both the government and international community in Nepal find local bodies, community organisations, federations, cooperatives, NGOs and civil society valuable partners for their projects considering that they are less bureaucratic, more flexible, innovative, adaptable and issue-based. They are complementing the development and political functions of the state, providing the resilience to citizens to cope with their needs for justice, identity, reconciliation and reconstruction. It has liberalised the nature of traditional politics from status-bound to social contract, altered the functions of state and transformed Nepali society to post-conventional direction of inclusive, secular, federal, democratic republic. Still, what is taxing is how can they overcome their partisan character, develop autonomy, build coalitions across diverse Nepalis and enable collective action on matters of public good. Civil society groups in Nepal, as partners in democratic progress, are providing useful information to increase public understanding of governance goals, policies and strategies. Their alternative vision, methods and proposals provide useful information for planning, policy, budgeting, management, execution, evaluation and critical review of democratic progress. Their contribution is cherished by laws and plans. The Nepali Constitution has included lots of social rights for the expansion and deepening of democracy. But, its fulfillment needs multi-actor cooperation including those of civil society and business. This helps to control lawless dissent.

Nepali polity prizes the constructive roles of civil society in improving societal acceptability in policy making and outcome in the preparation of plan, Constitution, Post-Earthquake National Reconstruction Plan, peace accord etc. It can limit polarising effects and build coherence and sustainability in different actors' goals, means and strategies to progress. They have helped to create ownership and representation of diverse interests and moderate macro-development policies -- PRSP,SDGs and post-conflict and post-quake reconstruction through stakeholders' consultation (training, workshop, seminars and discussion) and obtaining necessary public feedbacks for the contextualisation of policy.

The mechanism of accountability is set through Public Account Committee, anti-corruption watchdog, Auditor-General, media, policy makers, donors and voters where civil society invoke right to information entailing the openness of democratic governance. Now local elected bodies engage the citizens' representatives from various walks of life in public hearing about plans, policies, priorities, budget allocation and even evaluation. Others busy in social struggles aim to foster equity in the development outcome (gender, caste, region, age, class, ethnicity etc), ecological preservation (sustainable development) at multi-level rule, delivery responsiveness, education about social charter, social audit, public hearing, formation of Citizens' Groups, partnership and consensus building and enabling polity to pilot through democratic ideals.

The task of civil society in rural areas is to scale the institutional incentives to peasants, workers, women Dalits and poor to adopt new skill, technology and entrepreneurship enabling them to adapt to new age of inclusive transformation. Many hands approach is useful to capture the hierarchy and complexity of Nepali society and internally democratise the public and private actors. Local ownership in democratic initiatives is vital to build indigenous capabilities. It provides basic condition for basic liberties and public services that cuts undue dependence on external agencies.

Local civil society groups are engaged in a variety of mediation and peacebuilding roles at multi-track and mobilising Mothers' Groups and now Dispute Settlement Committee seeking to resolve conflicts by ethics of human rights, justice and integrity of democratic life. A vibrant civil society can correct the power of the state, moderate the appetites of government for arbitrary use of power, resource and authority, democratise political parties and temper the ferocity of market forces in the general interest of public goods vital for democratic dynamism. 

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/29132}

### Politics of Social Movements

Social, economic and political institutions set the context, norms and incentives for individuals and group behaviour, and enable them to organise action. They also define rules of the game for inclusion and exclusion. The peaceful revolt of the excluded for social justice creates a ground for producing a new reality and marking a transition from personalised politics. For them, the enemy is the past and the solution lies in impersonal aspiration of a collective identity "social," a concept in which shared language is found for feeling, thinking and action. Democratic structures offer them a chance to negotiate unequal power relationship to improve their condition. The modern social movements arose as citizens found the structures of union, political parties and parliament too bureaucratic, rigid and hierarchic largely numb to their needs, rights and aspirations.

Shared goals

In Nepal, the scream of protests of a multitude of social forces - women, Dalits, Aadibasis, minorities, human rights groups, federations, etc. seek shared goals of entitlements, resource and recognition beyond the politics of left-right divide. The values of modernity and democratic awakening have offered an impetus for a choice of life and rational change of Nepali society, revealing the justification of justice over law. Nepal's Constitution has integrated participation, social inclusion and proportional representation as normative frame to widen the scope of citizenship. Their political mobilisation has animated rights beyond the bound of formal institutions. It has revitalised the public sphere of civil society and its capacity to activate participatory democracy. Citizens' struggles for change emerged outside the electoral politics, political leadership and rule.

The spring of Nepal's social movements against the unjust use of political power, blind faith and deprivation was stoked by critical masses of citizens. They were motivated by a sense of civic duty to improve the quality of life beyond rights-oriented action. The values of liberation, just rule, justice, peace and eco-balance were grounded in the nation's classical treatises as they justified public action against unjust order. Newer forces of world system have sponsored sectoral rights, infinite exploitation of nature and poor for short-term profit and misused the nation's empirical diversity, not harnessed its resilience. They have also incubated counter elites to instrumentalise Nepali state's cultural diversity for endless regime change for the false harmony of atomised life. This has flagged Nepali society's ability to converse beyond positivism, state's ability to deliver public security and goods and its elites' ability to conceptualise policy devoid of alien guide.

The previous vibrant social movements with salvation potential have now become projectised by aid regime rendering them unfree. Their inability to organise solidaristic action has incised both legitimacy and rationality. Transformational leadership, with resolute human spirit, can rescue them from attrition and rekindle seamless web of Nepali society. In Nepal, most of social struggles for change ended in a compromise without unbolting an open moment for native vision but setting a lot of normative values - popular sovereignty, social inclusion, principle of affected and grasp of their contractual rights. Their texture of life rests on unity of action and care for the posterity.

The information revolution is confronting Nepali elites' political culture. It has problematised national tradition, culture and the state. Globalisation of social movements has flattened the development, democracy and human rights context beyond the state's bound entailing rethinking on meaning, structure, agency and political power. Most of Nepal's youth migrate abroad for jobs and cope with the changing labour market condition and laws governing the nature of works. Labour as a spirit of life and politics as a means of collective action can aid each other. The ownership of sources of wealth is governed by political decisions. Creation of a just labour market within Nepal ensures its vaunted opulence while squeezing it compromises the nation's future. The breeding of multi-classes across both the capital and labour broadened bi-nary code of politics but did not change its transactional political culture. The new citizenship rights can legitimise new form of collective action to change this. Democratic ethos embodied in Nepal's social movements has captured the spirit of solidarity across multi-actor and multi-space and parallel socialisation, mobilisation, networking and leadership, asserting the decolonisation of common humanity driven by non-lineal social change.

Rejecting dependent development, Nepali citizens defend subidiarity through the pull of local and global solidarity to reform power for re-distributive justice, reduction of poverty and social inequality ending gender and other discriminations. They have politicised them and adopted universal values for the rationalisation of constitution, institutions and practices. But they need reflective knowledge to defy the commodification of social life by media, traditionalisation of work and reduce the risk of being abused against weak Nepali state. Equalisation of actual life condition despite unequal abilities entails the execution of social welfare state. A systemic link exists between the crisis faced by the Nepal's economy and citizens' rights for decent jobs, dignity, social protection, education and health. Realisation of their humanity to normative end-freedom is possible if their movements can build the capacity of state and find term to an emotional aspect of citizenship, responding to systemic risks.

Nepali citizens' ties with the vital life processes, politics, the state and world system are shifting. Politics expanded the scope of labour, work and public sphere and brought the policy issues to the front of governance. Nepali politics cannot address the problems of its multi-classes unless devoid of common interest orientation. Access of citizens in policy making can overcome their self-alienation and justify strategic action built on social contract, mutual adjustment and even subsidy, housing, health care and education for the weak in exchange for their loyalty to the state and their vote in elections. A shift from symbolic to real economy helps Nepalis to reclaim the state to control social vices through the virtue of its welfare benefits.

The steam of many social struggles of Nepal evaporated. Their leaders were ended in a self-parody, virtual oligarch, projectised and rendered partisan. Nepali state's retreat from the welfare invited the influence of trans-national forces aligned with local economic interests. But they failed to stand above partisan interest and address grassroots movement of people's representatives for greater influence of local struggles into institutional power for a people-oriented progress. Organic re-links of social struggles can synergise their will and responsibilise them. But they have to include three dimensions - a public, national and care economic ones and their steady politicization.

Politics is a decision making system. Access of Nepali citizens to this system is central to resolve existential problem. The centrality of co-determination of national politics, law and policy through social dialogues is the key to emancipate Nepalis from self-alienation, fear and dearth of basic needs. Social movement actors can advance welfare politics so that its welfare state finds symbiosis in social democracy. Nepal's social movements have fruitfully forged solidarity across the national borders and achieved reasonable progress in rights, legislation, cultural identify, politicisation of members but they also face social division, inertia, knowledge cringe and lack of inner democracy. Now struggle in Nepal is pivoted on how Nepalis can exercise their sovereignty and stabilise the state along federal-provincial-local axis to address class, caste, gender, ethnic and regional disparity.

Civic competence

Nepali leaders are daily encountering social struggles, some even fed by drivers of geopolitical conflicts. Their unity of action can re-energise the power of citizenship to shape fair society, emotional fulfilment and care economy. Nepalis' vision of change rests on their civic competence in bottom-up democracy, dignified life and organic solidarity with its supporters. Inter-connection with world system demonstrates that Nepali citizens' social struggles have to follow the mobility of capital, not just the state and reshape polity according to their priorities. Inter- and intra-movement unity can contribute to substantial reforms in the redistribution of resources, activate citizenship and engage in evoking their power to communicate those interests to public sphere for debate and collective action but they must abide by the functional requirements of Nepali state's stability.

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/22703}

### Leader Transformation

Every society is divided by a class of few leaders and great mass of supporters. As a universal phenomenon, leadership emerges from the social, economic and political conditions, electoral process and institutions of society such as family, tribe, community, political parties and the nation-state. Their ties to these units underlie the scale of vision and responsibility. Since their institutional boundaries are porous, leaders' action can be judged from their ability to fulfil people's needs, rights and concerns. Emerged from the chrysalis of new values of freedom, justice and dignity of people, the new political leadership of Nepal has achieved success in launching revolutions but appeared weak in governance.

Like medical doctors, they need to diagnose the changing condition, organise resources and offer policy prescriptions. Their quality rests on how well they manage legitimate demands of people, solve their problems and tread the nation along constitutional path. The antinomy between what Nepali leaders have promised to achieve "happy people, prosperous Nepal, good governance and political stability" under normative ethics and rival utilitarian paths they have chosen to attain these goals set them in litmus test.

Traits

One may frankly inform leadership virtues in terms of transactional and transformational fervour. The bond of transactional leaders to their followers is like business. It is based on exchange-vote buying and rent-seeking, not embedded in the social interest of the nation. Nepal's elections have shown the predominance of these Janus-faced demagogues. In a transitional politics like Nepal's where constitution, values, institutions and procedures of governance are not properly stabilised such a leadership, often plagued by their own uncertainties, cannot address the changing aspirations of Nepali citizens. They have allowed national institutions deteriorate rendering many of them partisan unable to perform optimally and neutrally. Institutional erosion has caused volatility of Nepali political system whose robustness is vital for the citizens to realise their rights, duties, choice and action and affirm the life of dignity. The goodness of Nepali leaders' virtues does not transpire when national education is reduced to "facts" devoid of values of public morality.

The relationship nourishing, not the task-oriented, nature of most of transactional Nepali leaders have turned the human rights struggle of people unfinished. Their views are insular, self-seeking and sub-culture oriented. Critical masses of civil society often question their authority and legitimacy and cast doubt on their sullen ability to match deeds and actions. Nepal's electoral trends show that electorates have always defeated the incumbent leaders indicating the need for changing policy contents, political leadership and party structures though they are resilient to bounce back in the centre of politics through networks, organisation control and geopolitical leverage. As a result, Nepali citizens judge their leaders in terms of output performance than only on the basis of glitzy promises. Nepal does not lack the root of wisdom. Leaders need to fortify stable links with the people to learn how to gain wisdom, freedom and dignity.

The transformational leadership is goal-oriented, rationalist in attitude, enlightened and adaptable to both liberal eloquence of the Age and changing aspiration of Nepali people catalysed by democratic revolution. They create a climate of opinion to justify their future roles rather than either discrediting history or harking back on its nostalgia. Their attachment with the people provides a hope even for the poor to engage in transformational project and improve life-choices. In Nepal, one can see transformation in the context, language of discourse, actors, issues and rules of the game but the creation of a just human community promised in the constitution remains alluring. Most of Nepali political leaders are boxed in their own partial frame unable to read other's motives and intentions and seem weak to inspire the opponents for collective action to help Nepalis relish democratic dividends. 

Nepali leaders can be placed in the scale of statesmanship, political leadership and bossism. The statesman is a visionary and thinks ahead of his time. He makes his constituency the entire Nepali state and learns from historical insights and scientific trends to reconcile his own ambition with national interests. Statesman's perspective is long-term perfection of generation and his action matches with the experience of people. He judges how best public and national interests can be served. One can cite the examples of Nepal's heroes and builders who defended national sovereignty bequeathing great deeds to posterity.

Political leaders' vision is rooted in periodic elections and an exigency to flex party's muscle. They are ahistorical, reactive and thrive on seductive ideological rhetoric and short-term planning. They work with consultants on deterministic theory of progress which is contrary to pluralistic Nepali society's stability. The cultic honouring of top leadership with 120 kilos of garland during field visit marks the denial of constitutional spirit of popular sovereignty and the start of creeping authoritarianism. The political bosses do not hold any vision, represent only the faction of a political party or electoral constituency, survival-oriented and suffer from historical amnesia. In a word, they are timid on pursuing national initiatives and torn between lust for personal power and institutional imbalance.

Leaders who use national sentiment only for the purpose of personal rise collapse easily when their policies hit the ground realities. The nation's nonstop political instability explains this. Nepali nationalism presupposes national awareness of history, culture and needs of people which are a source of political stability. But an awareness of only political party, social units and particular territory twists social cohesion and external adaptation. 

The ideological teeter-totter of the left and the right being projected in Nepal is a fatal sign given the nation's strategic geography where so many experimental projects of foreign countries are executed. Nepal's neighbours, haunted by the security dilemma, are closely watching with unease their costs as they see their links with local forces, persons, groups and institutions bristling with the revisionist interpretation of national history. For years, the nation's foreign policy became prisoner of internal wrangling and lost an art of balance in the age of anger. A divorce from the historically defined policy of golden mean can easily unravel the tangled aspirations of otherwise united Nepali people into centrifugal pulls risking the fragile social order and peace inciting other countries to limit its policy choices.

Nepal does not have sound think tanks to supply to the leaders knowledge, policy inputs and strategies to take right decisions on vital issues. As a result, national policy often deviated from the constitutional spirit and public opinion. Many of them are disciplinary-bound and consultancy-based, not policy-oriented, with contextual knowledge and feeling of human heart and conscience to those working under adverse condition. The political parties' catch-all tendency has made Nepali leaders schizophrenic. They are torn between socialization of political life in the partisan framework and role occupancy to foster national interests, between sacrifice in justice-oriented stir in the past and current intoxication with power and between opposing ideologies and leaders' coherence in a regime of power-sharing. Evidently, Nepali leaders' political life is personal, empirical and partisan, not impersonal, national and analytic which are desired to transform themselves from bosses, political leaders to statesmanship and apply wisdom to statecraft. A value-sharing civic culture of leadership can form a common background condition to glue the enormity of gaps between public interest and public policy.

Selection

The utility of politics is decided by social interest. Statesman embodies the will of the nation and defends the constitutional doctrine that they have a responsibility to protect and advance the interest of the whole nation and people, not just the fragmented parties and uncompetitive polity. Leadership selection is about the representation and determination of policy for national development but wisdom is essential for the inspiration of people which comes from the synthesis of knowledge, morality and experience in governance. Enlightened leaders in command of authority can seek compliance to their policies, inspire skeptics and opponents, bear duty and keenly confront the implication of their choices for public welfare. 

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/20959}

### In Pursuit of Wellbeing

The bulge of consciousness has widened the concept of wellbeing exposing citizens and leaders to a big picture. Sages, philosophers and scholars have always been engaged in seeking universal values of wellbeing with cluster of themes such as freedom, justice, social esteem, compassion, rights, healthcare, liberation, happiness, social security, economic participation, political opportunities, peace, etc. in a pursuit of decent standards of living. It manifests in different ways around the world upholding various strands of thought and philosophy espousing the wellbeing of citizens under diverse pre-historic and historical traditions. The Vedas say that human beings have an ability to transcend selfishness and attain both humanity and divinity-the higher stage of wellbeing.

Janak, Astavakra, Ved Vyas, Valmiki, Buddha, etc. have set examples of how a great intellectual ferment of wellbeing is secured without coercion. Ancient Nepal espoused four dimensions of human life-dharma (virtuous conduct), artha (wealth), kama (pleasure) and mokchha or nirvana (emancipation) for physical, social, moral and spiritual wellbeing bound up with optimally good life. The last one does not dawn with the resignation to fate, social determinism, envy or ego but by an active and mindful engagement in the public life and removal of all barriers to knowledge, wealth, health, balance and nurturance. True wellbeing comes through enlightenment, innovation and freedom to determine vital choices of life affirming the wisdom of the Upanishad: damayata (self-control), datta (altruism and giving) and dayadhvam (compassion) to those in need of care. These normative compulsions have levelling impulses. It is useful to resolve the inner incongruity of life and ease one's conscience.

The Isha Upanishad issues a wise message," while enjoying the fruits of creation one should not covet for others' possessions. One should partake in the means of livelihood to the minimum and conserve the resources available in the universe for others to meet their requirements." This impels justice across human and natural world spurring the reason to defend what Gautam Buddha and Karl Marx call need-based economy to resolve external incongruity of life. The supreme ethics of science and politics finds its resonance in the ongoing global debate and consensus on sustainable development. Wellbeing is thus linked to outward, material pleasure and inward joy of life linked to pran vital to set off existential life-process.

Wise persons see others like themselves, cultivate creative zeal to gauge wellbeing beyond empirical indicators and measure the quality of life in holistic sense. When human grief vanishes by getting the dignity of life citizens seek to reach the oneness of humanity now somewhat affirmed by the canon of human rights. But it does not fully cherish the cosmic web of life as it is anthropocentric in nature. The will of humanity is governed more by the virtue of duty than rights. In the Nepali context, the prime condition of wellbeing rests on the fulfilment of basic needs, then the attainment of general public goods and finally perfect bliss which can be achieved by higher will affirming the destiny of its civilisation. This perspective demands a control on the wild expression of human nature by legal bounds, inclusive social transformation and common traction on normative and legal issues on the scale of human values that stops the hidden cuffs of cognitive dependence, ends violence in politics, restores ethics in economics and whets the resilience of ecological and social life.

The modern meaning of wellbeing in the nation underpins freedom of Nepalis from the chains of ignorance, basic needs deficits and fear so that they can pursue their rights to live larger lives. It is grounded in the moral and constitutional frame as it helps to confront evils of society for the attainment of freedom, equality, entitlements and adequate social opportunities animating a more enriching way of living lives. The approach to wellbeing is not calculated in the economic system of accounting of growth and habits of material consumption only without the use of democratic ethics. Enlightenment view of human nature considers human as rational being capable of judgment and public action for the prevention of harm and promotion of wellbeing. The contamination of wellbeing in Nepal springs from the unstable condition of self and society generated by the nation's post-traumatic stress disorder and misery of the world that sets political culture clashing with the satisfaction of pent-up needs.

Knowledge of Nepalis about the pain of scarcity is necessary for breaking its causes through duties, accountabilities and justice where the state, citizens and a variety of institutions in-between have to play creative and complementary roles to capture the synergy of progress. An awakening to this helps oneself to acquire power and ability of true self and set the path of wellbeing and self-realisation. The sutto guna, divine virtue of human beings, enables them to become creator of their own destiny and exercise wisdom, not entirely conditioned by tamo (passion) and rajo (spirit and valour) gunas or external compulsion. In a least developed nation like Nepal wealth creation is crucial but not enough to catch the delight of wellbeing. The source of wealth-greed, avarice and undue misuse of nature and poor is simply unsustainable. It creates a biological destiny built in human nature. Such destiny is afflicted by jealously, poverty and insecurity. It hits inner disharmonies and breeds befuddled conviction, profession and law animus to rational consistency with moral high ground.

In the pursuit of wellbeing, the Constitution embodies many social and economic provisions including right to work, education, health, social security and even universal human rights. Ironically about 25 per cent of Nepalis are deprived of the basic necessities of life while about six million youths tormented by the miseries of life are working hard in foreign land to sustain their living and support the national economy. It is important to lift the unfair burden on the life of the poor and re-moralise public life deemed fit for them to belong. Feeding the stomach lifts the heart to long for freedom. Therefore, Nepalis had until recently defined shuva lav, just price as per innate value of things in the market place evoking corporate social responsibility and maintenance of business ethics where civil society can educate about the aim of life.

So long as Nepal continues to practice revenue-based economic model, dream of remittance, tourism, excessive import, aid, investment and careless use of natural and human resources and maintains rich-poor gap, the nation's rise to developing country is hard. Dependence does not sustain the springs of hope for a socialised polity nor nurtures national sovereignty, the collective manifestation of individual freedom. Nepalis must be liberated from the bottom up for creative social initiatives and enterprises so that each of them can explore life's immense possibilities beyond biological survival. The Constitutional vision of right to work supposes a job that pays a liveable wage for everyone. This requires labour market reforms along the line of social development and economic imperatives of ecological balance. It is possible by ending the grubby transitional politics, curbing patronage and shifting politics to democratic affinities- reflection, deliberation, policy making and collective action.

The role of Nepali state lies in promoting the "real economy" to ensure food sovereignty, adaptive skills of its citizens fit for the jobs in technology-driven economy, condition for the realisation of equal rights and duties and enabling them to undertake civic roles. The role of government lies in removing institutional deficiencies by shifting the legal and ethical balance in favour of the ordinary citizens, weak and marginalised while the role of democratic polity lies in widening the public sphere, acquiring capacity to deliver public goods and reaching out to those who no longer have faith in liberal way of life defined by the power of reason for its failure to confront political problems. Wellbeing of Nepalis is relative to their expectation bred by electoral manifestoes of political parties, leaders' promises and constitutional provisions with their ability to pull self and communities together to a higher plane. A person's wellbeing is the result of overall satisfaction with much solidarity with family, community, society, profession, the state to many global networks.

Among the multitude of forces that propel prosperity, knowledge, artificial intelligence, communication, entrepreneurship, connectivity and distributive justice are the vital ones. They empower Nepalis to realise their slumbering potentials, utilise surpluses of the nation, meet challenges and capacitate the state to comply with global obligations. Nothing can stop Nepal from achieving its elevated wellbeing once citizens, imbued with confidence in the power of sovereignty embedded in them and leadership guided by national vision, begin to step forward in a committed way in the implementation of the Constitution and maximisation of welfare provisions entrenched in it. They can change human condition through right decisions in every aspect of life. But they must be cautious enough on who are subverting the polity and allowing the surge of centrifugal geopolitics and clogging the state's outreach at the grassroots.

For Nepalis, wellbeing is more than comfort of existence. It rests on preference compatible with aspirations of what Immanuel Kant says "moral destiny." The decay of religion and ideologies has renewed the principle of utility and contaminated moral atmosphere. But it is restoring human appeal to knowing self that vindicates commonsense and values self-esteem again that sets a reasonable equilibrium between physical, psychological and spiritual state of life vital for animating wellbeing. 

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/31119}

## Media and technology

### Media in Democratization

Media - print, audio, visual and internet - form a part of larger civil society entrusted with the duty to protect human rights, widen the domain of public sphere and contribute to public opinion and democratic will-formation. Awakening of Nepalis to their constitutional rights and ethics of legal duties and their socialisation are keys to consolidate constitutional state capable of achieving governance goals. Nepali media have served vital tasks in democratic innovation and diffusion of its principles and concepts crucial to fortify its institutional pillars, such as polity, political parties, civil society, election and the public and projected national identity to a wider world of nation-states.
One of the oldest media in Nepal such as Gorkhapatra and its sister publication The Rising Nepal have always exposed Nepalis to new ways of thinking to build this nation through the flow of educational contents and adoption of new attitudes needed for social modernisation and economic progress. The recent effort of Gorkahpatra to fuse and adjust to the needs of diverse Nepalis and increase outreach in the periphery have animated the links with major segments of society through their own dialects, cultures and geniuses. Transmitting news, views and opinions across many divides is essential for democratic consciousness of citizens and revival of the public from the mass.

Communicative space
Proliferation of private media and online newspapers with diffused orientations and interest areas has widened the scope of communicative space for the voice and visibility of many groups of society, pooled new loyalties and indulged in competition for public attention. It is helping to maintain a balance between universal spirit of democracy and cultural relativism of Nepali nation. Many journalists imbued with virtuous ethics have fostered democratic spirit even at the risk of their life and liberty. Some are burdened by the source of funding and lack common Nepali sentiment. They are less articulator of public interests while others are more to side of democratic aspirations than constitutionalism.

An enduring moral question of democracy is that it entails healthy and free press to cultivate democratically worthy citizens for freedom of press is fused with social accountability. The normative values of Nepali democracy such as popular sovereignty, social inclusion and negative and positive rights supply creative spirit to politics so central to defend public interests. It enables the nation fit for the world culture. In Nepal, the public functions of media, however, rest on their own framework of ownership, finance, autonomy, control, regulation, transparency and accountability. Their context-sensitivity enables to rationally shape cognition, feeling, emotion and judgment about the state of Nepali democracy and foster legal-rational norms for leaders' behaviour.

As a champion of freedom Nepali media have provided civic awareness to citizens about changing nature of politics, equipped them with participatory information, stimulated active engagement and fostered meaningful dialogues. But in no way they are instrumental in providing ownership on public policies which are mostly fabricated outside the nation. Familiarisation of citizens with various themes hones their inner vigilance enabling to judge the rationality of democratic politics and exercise choice in public affairs. Nepali state can implement Right to Information Act, Working Journalists Act and the Constitution if it holds legitimate monopoly on power to create public order and clip the connectors of Nepali society.

But the protection of journalists' rights, laws, social security, professional dignity and solidarity are allied with the autonomy and capacity of the polity to tolerate independent role of the court, watchdog agencies and the attentive public. It enables media to serve as a lively link between the input and output functions of democracy which makes the interactive political sphere resilient. Solidarity of media associations helps to beat the abuse of their members, enforce labour act and security deficit caused by attack politics. Fragmentation of it along partisan lines stifles the public sphere and their own efficacy. Mediatisation of public sphere has enabled Nepali leaders to communicate more with journalists than among themselves and to the life of citizens.

Media Strategies for Democratisation: Critical information is power and its effective utilisation helps to free Nepalis from the fetters and tutelages and realisation of their 31 constitutional rights and four duties. Civic competence of Nepalis to shape preference rests on basic knowledge and access to the flow of information to the entire web of national life. The direct language media use for communication of the messages can socialise citizens on public issues, provide them autonomous power to deliberate and act without any fear of power constraint. The manifest performances of media on democratisation are:

First, detonation of critical debates in Nepal has birthed a deliberative public essential to keep the dynamic of political life. Informed public opinion depends on critical social dialogues about the conditions of Nepalis, women's issues, social evils, human trafficking, reform in social legislation, health and safety of poor, etc. Elimination of structural injustice can create a level playing field for all. Nepali media thus need to debate about impersonal roles of the state and public institutions, political parties, market and civil society taking into account long-term perspectives of all sides on the political process beyond project setup. This is central to reflect the plurality of opinions and diversity of views and stimulate creative participation of the public in the attainment of common good.

Second, the public sphere of media is ideally regarded autonomous of various interest groups so that every Nepali can share this sphere equally and exercise their right to know ensuring decisions on public affairs transparent. Pluralist character of Nepali media has enabled citizens to shape their political choices and pass valid judgment. By using reflective imagination and deliberation with ordinary citizens they can bridge the gap between their concepts and citizens' world views and engage them in revealing the social truth above the cacophonous noise. A responsible media culture can reform many irrational codes of society and create rational ground to step up social change.

Third, Nepali media continue to activate the passive spectators into active citizens. To be engaged in public affairs means actively express political, legal and policy issues on media platforms creating a stake of every Nepali in democracy. One vital democratic role of media is civic education-- training of Nepalis into the life of citizenship and human rights, respect for others' legitimate views and work for the improvement of government and public institutions. Democratisation helps to broaden their horizon, moderate the views of many identities- caste, class, gender, ethnicity, religions and regions and transform them into an equal citizen of Nepal. Those with partisan prejudice do not generate true consciousness. Instead they indoctrinate, engineer consent, inflate the image of leaders or indulge in disinformation. They are problematic in terms of attaching the trust and loyalty of citizens to democracy.

Fourth, Nepali media have functioned as generators of public trust, reconciliation and peace. The worst affected citizens by direct violence, disruption and structural injustice are poor Nepalis though tax and remittance they contribute to keep the nation's vital economic life going. In a post-conflict nation, like Nepal, media have to pro-actively engage in reformist agenda, shape common backdrop order for a common ground for the resolution of constitutional issues such as type of polity, federalism, governance, judiciary, election, citizenship and democratic dividends. It defines media profession as a normative public craft to expand civic space to capture the soul of democratic values and norms. Resilient functions of media in Nepal rest on non-violent communication and nurturing of bonding and bridging social capital for deepening democracy.

Fifth, bulk of public interest media in Nepal has served to liberate citizens from alien-thought control, feudalism and corporate interest. Democratic politics is not only about the leadership selection for power but also about promoting common good where even ordinary citizens are beneficiary. The robustness of Nepali democracy rests on an easy flow of feedback between the leaders and citizens and revitalisation of public life. Media should release democracy's capacity for social, economic and political integration of society, strengthen national integrity system to control social evils, corruption and impunity control of which make surplus for social investments for livelihood security.

Sixth, public function of Nepali media is to build civic competence of citizens to adapt to ecological, economic and technological change. Information and education provide means for nurturing citizens' life-long learning process with the flow of changes. In this sense, the contents of civic education should be practical in nature because it gives them a critical sense of inquiry in thinking, judgment and action. A democratic process also avoids the pitfall of exclusion and eternal agitation cursing Nepal. Civic space of media freedom is guaranteed in Nepal's constitution. But it is law-based, not lawless and anarchic, which requires civic culture of media persons.

Nepali media have a long-standing promise to a civic culture, a culture that requires not only political equality but also an ability to solve their problems and contribute to social modernisation and democratisation. Fundamentalism, whether market, class, ethnic or religious, removes the common ground among the diverse Nepalis living together in the same space, stokes the spiral of mistrust, distorts communication and risks the nation's relapse into pre-civilised form. The ability of media to inculcate knowledge about the optimisation of concerns of various actors can fortify democratic public life.

Nepalis should be given critical knowledge about changing the nature of ecology, technology, economy and life-choices. Only then, democracy can foster peace through every one's stake in it and instils a sense of justice. Injustice, alienation and invisibility mark the decline of democracy and an atrophy of media's public functions to make democracy for everyone by reaching to even the passive, poor, isolated and alienated ones and engaging in civic action. By providing critical information responsible press nurtures an informed society capable of making vital choices in the public affairs and contributes towards participatory democracy.

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/30916}

### Digitalizing future

In India, the use of the digital biometric identity code was initially optional - and served poor people to claim benefits. The Supreme Court confirmed that the use of the ID system should be voluntary. Nonetheless, it is required for ever more purposes. Civil-society activists warn of privacy breaches and improper surveillance. This is an example of how, in the course of the past ten years, developmental visions related to digitalisation have been getting darker.

From the mid-90s to the Arab spring of 2011, a sense of euphoria was common. Before the 1990s, however, information technology simply did not seem to be relevant for developing countries.

That began to change, when international media became aware of the IT hub that had evolved around Bangalore. Next, internet access spread fast, and, though digital divides persisted, the World Wide Web came ever closer to living up to its name. Then mobile telephony conquered much of Africa. Suddenly, Kenya was pioneering mobile money. Digital technology was making a difference in evermore people's lives, and masses of them were poor.

Mobile phones became commonly used devices even in remote villages. People got access to more information than ever before and started to interact with others who are far away. In many ways, digitalisation was empowering. For example, social media proved essential in the Arab spring. As dictators fell, journalists spoke of "Facebook revolutions". That was then. Platforms that seemed to facilitate free communication 10 years ago, are now infested with disinformation and propaganda. The business models of established media houses are being undermined, to the detriment of quality journalism. Instead of living in "knowledge societies" as we were promised, we seem to understand less and less.

As a general trend, both public administrations and private-sector businesses are computerised. Digital disruption is common, and leaders in both spheres are paying increasingly close attention to what is discussed online, with some doing their best to manipulate public discourse. Authoritarian populism is gaining ground, while the respect for democracy seems to be waning in many places. China's communist regime is leading the trend of monitoring citizens, but other governments seem eager to follow.

At the same time, the corporate powers that dominate the internet today are still largely beyond government control. They are not paying taxes commensurate with their revenues. The top managers cultivate a liberal image, but their lobbyists are really only striving to protect the likes of Google, Facebook, Amazon, Microsoft and Apple from regulation. The algorithms of Facebook and YouTube, which belong to the Google parent company Alphabet, are driving the radicalisation of angry people by offering users ever more extreme content to keep them on the platforms.

Digitalisation is shaping our species' future. We need sensible rules. The forces that dominate the web are far more powerful than most nation states. The only three political entities that still seem able to regulate them are the USA, China and the EU. At this point, only the EU shows a preference for protecting citizens' rights. If other countries want to have an impact, they must forge alliances. That way they can tap technology's still promising potentials and keep a check on the risks. There is no alternative if we do not want to surrender to overwhelming corporate or state power.

Source: Hans Dambowski, \url{http://therisingnepal.org.np/news/34386}

### Media and the Public

Mass media such as print, radio, television and cyberspace are useful mediums to link the word to the world. They elevate life's social bonds and carry out the surveillance functions in society. Three vital tasks of socialisation, integration and adaptation of social and political systems are performed by communications. In an economy, media supply information to 'invisible hand' seeking a balance of supply and demand and alleviating the scarcity of public goods. The knowledge society and economy rest on circular flow of information like in a cybernetic or human nerve system where receivers and senders are linked by signals, networks and feedbacks. Similarly, autonomous media stir citizens' ability to learn, think, feel, perceive and know turning active observer of what is happening around them. These processes have made Nepali citizens highly alert, critical and active participant in the public life. 

Learning habits of media have spurred a synergy of the social and political structures evolved by citizens themselves to pursue their strategic goals. Learners become the future multiplier of knowledge and skills to propel up policy agenda. This assists them to incise undue influence of interest and lobby groups standing as a spoiler of problem solution. An efficient response to rapid socio-economic, technological and political change and growing competition in today's media landscape in Nepal, entails journalists to become a creative part of history. Historical consciousness of the present helps overcome the national habits of forgetfulness and confront today's challenges. The notion of popular sovereignty embedded in the Constitution of Nepal implies the legislative power of citizens. This makes the public a sacred symbol of journalists on whose name they defend their rhythm of idiom, tone and action. Structural freedom of media is, therefore, essential to stimulate the moral consciousness of their power and engage in public's struggle for a reflective gaze. This spreads media's radar and renews the democratic life mini publics of the nation.

The critical questions Nepali media persons usually confront are: Are Nepalis able to exercise equal sovereignty when national media are unfairly distributed in society and their degree of participation in public affairs is determined by the level of their access, influence and control on socio-economic preconditions of modernity? How can Nepali media establish citizens' constitutional right to know through the diffusion of information and innovation if bulk of them are dominated by party affiliation, business community, the regime and geopolitical interests lacking fairness of judgment on matters of national security, liberty, justice and wellbeing? Do media conform to the norms of public sphere and stomach valid criticism of the public or refuse to slit objective truth from power, interest and ideology?

A sober inquiry is central to know how many Nepali media exercise freedom of conscience and plot credible message to citizens and how many of them interpret truth to what they would like to see. In the case of distorted perception they cannot claim moral authority to judge actors and institutions and prepare citizens for democratic habit. On the contrary, the parasitic growth of media becomes unreflectively sensational. In no way does it greet either the return of ordinary public before the structures, processes and system or set the safe future of posterity. It only diverts public attention from the main issues Nepalis face, fragments the nation's political culture and maintain senseless indifference to public's unfulfilled life.

Nationally embedded media struggle to hold the current drift of Nepali society to many directions and rush to the task of nation building. Cross-cultural communication, diffusion of national heritage and culture and loyalty of citizens are vital means for adaptation of the nation in the whirlwind of new geopolitics. Culture enables to predict the behaviour of others. A generational divide exists in Nepali journalism which isolates ideologues from realists and vernacular from other languages. Another divide is between conformist socialisation by old institutions of family, community and religion that opens an opportunity to the nation's varied public life and modern media culture that isolates one set of audience from the other and obscures the link between media ethics, economics, democracy and sovereignty.

The manifest public duties of media as suppliers of news, views, images and amusement stand compelling. They are supposed to free Nepalis from private prejudice, passivism and fatalism and enlist in the public sphere to discuss common problems. Rational public opinion allows citizens to exercise their power of choice and use scientific reason to dispel blind faith and bias whose malaises insult inner vigilance. Democratic crusade of media can liberate truth from the regime's gadgets seeking conformity and link citizens to universal public.

The great feat of Nepali media lies in educating Nepalis to think sincerely about the state of the nation, free them from structural limits, fill democratic values and endow a rewarding life. This is why C. W. Mills mounts a spirited defense of "sociological imagination" for journalists. It is vital to cultivate deliberative public who can rationally decide the choices for Nepali nation. Research revels electronic media violating code of conduct and backing social passivity Nepalis. Their audiences are receding into the circle of family and friends, not forming an interactive public and shaping democratic will for social change. One must know that a multi-cultural society like Nepal cannot hold together without good media infrastructures and laws that provide access of all citizens to information, ease their communication and build right view without which the ability of regime to govern declines.

Politics turns rational if citizens are informed and guided by a lively public sphere, enlightened opinion and general interest formed through reasoned conservation. An equal, open and free public sphere fosters democratic values and contributes to the democratisation of Nepali society. Media's analytic account of public issues and their remedy justify a search for constant progress of human affairs. But this requires them to set aside high political rhetoric where politicians stir hearts and minds of ignorant crowd without uttering any policy messages. This replaces the role of reason which can hardly become a staple of Nepali history. Media need to spur Nepali public's fight to control their destiny and dignity. But if public opinion is monopolised by the media what is left for elected political leaders is constant alienation of electorates which does not augur well for democratic accountability. The public morality of journalists, therefore, rests on their ethical life and the sanctity of their means and workplace. Morality is, after all, the soul of freedom. It negates elusive consciousness considering it a silent enemy that only intoxicates the audience.

Nepali journalists, as interlocutors of the public, need to probe its problems in every moments of life. Social and political pluralism expects an air of media competition and professionalism where public issues get top priority in agenda setting and framing of news and views to visualize the public. Professionalism does not mean blind passion, loss of human feelings and immune to public criticism. In a troubled nation, like Nepal, context-sensitivity is essential to evoke emotional intelligence, conscience, bridging feeling and innovation beyond linear-logical knowledge of cause-effect. This moving consciousness restores an application of intelligence and imagination in reporting, not provoking, events and issues. It cleaves news from advocacy, velocity of ad and entertainment that depoliticise the public. This is why every public office in Nepal recruits one press officer to inform the public so that citizens do not fall in a trap of disinformation. Transparent communication upholds an enlightenment belief in social progress which is essential for the evolution of self-aware society. Invisibility of the public mirrors the failure of media and loss of their editorial freedom. This pulls Nepalis to a culture of silence. Only a live public sphere generated by what J. Habermas calls, "communicative action," can refill democratic spirit of media in Nepal. This action, for him, is "oriented toward reaching understanding," which marshals vital reason to strengthen Nepali democracy.

The public service value of media prompts journalists to uphold their duty to society. Media express the voice of voiceless, the weaker side of the public, such as women, children, powerless, disabled and marginalised and activate the concept of citizen's equality. They make the governing power lawful, visible and accountable. Without responsible media, politics operates in a void, devoid of substantive issues, creative work and critical inquiry. In a one world of many societies, multi-channel communications also open social fractures. Awareness about these fractures, professional learning needs and methods are, therefore, critical to know the changing pattern of global media culture as it has instant implications for Nepal. An informed public can reform Nepali society and leads to a more civic course. It animates ideals, constructive criticism, activities and collective power of society vital to engage in a compromise and peace.

The hurdle to free communication, as Norbert Wiener says, is created by those allied with "the game of power and money." When fusion of this game serves a mediating factor of citizen's life all the systems and sub-systems created to organise citizens in a national space suffer. Pre-set filter, inattention to social issues and limited their ability to inform affect the integrity of the life of journalists. Unless they are stoutly backed by the web of court, their own solidarity across partisan lines and civil society their profession is consumed by a discord of free will and lack of essentials. Nepali journalists' defence of the public thirst for justice rather than reflecting only the institutional biases of their employer can build the civic competence of citizens enthusing in them a feeling that their thinking and behaviour affects the track of public policy. Public accountability equally calls for a diversity of voices and a rough sense of balance in news. It demands disciplining the powerful interest that controls the access of citizens on public goods and new rule of equity vital for a civic culture.

Source: Dev Raj Dahal, \url{http://therisingnepal.org.np/news/26711}
